"useclient";

importImagefrom"next/image";
import{useState}from"react";
import{cn}from"@/lib/utils";

interfaceOptimizedImageProps{
src:string;
alt:string;
width?:number;
height?:number;
className?:string;
priority?:boolean;
fill?:boolean;
sizes?:string;
}

exportfunctionOptimizedImage({
src,
alt,
width,
height,
className,
priority=false,
fill=false,
sizes,
}:OptimizedImageProps){
const[isLoading,setIsLoading]=useState(true);
const[hasError,setHasError]=useState(false);

//Defaultresponsivesizesformobileoptimization
constdefaultSizes=sizes||"(max-width:640px)100vw,(max-width:1024px)50vw,33vw";

if(hasError){
return(
<div
className={cn(
"flexitems-centerjustify-centerbg-mutedtext-muted-foreground",
className
)}
style={!fill?{width,height}:undefined}
>
<spanclassName="text-xs">Imageunavailable</span>
</div>
);
}

return(
<divclassName={cn("relativeoverflow-hidden",className)}>
<Image
src={src}
alt={alt}
width={fill?undefined:width}
height={fill?undefined:height}
fill={fill}
sizes={defaultSizes}
priority={priority}
loading={priority?undefined:"lazy"}
quality={75}//Optimizequalityformobile
onLoad={()=>setIsLoading(false)}
onError={()=>{
setIsLoading(false);
setHasError(true);
}}
className={cn(
"transition-opacityduration-300",
isLoading?"opacity-0":"opacity-100"
)}
/>
{isLoading&&(
<divclassName="absoluteinset-0bg-mutedanimate-pulse"/>
)}
</div>
);
}
