"use***REMOVED***client";

import***REMOVED***Image***REMOVED***from***REMOVED***"next/image";
import***REMOVED***{***REMOVED***useState***REMOVED***}***REMOVED***from***REMOVED***"react";
import***REMOVED***{***REMOVED***cn***REMOVED***}***REMOVED***from***REMOVED***"@/lib/utils";

interface***REMOVED***OptimizedImageProps***REMOVED***{
***REMOVED******REMOVED***src:***REMOVED***string;
***REMOVED******REMOVED***alt:***REMOVED***string;
***REMOVED******REMOVED***width?:***REMOVED***number;
***REMOVED******REMOVED***height?:***REMOVED***number;
***REMOVED******REMOVED***className?:***REMOVED***string;
***REMOVED******REMOVED***priority?:***REMOVED***boolean;
***REMOVED******REMOVED***fill?:***REMOVED***boolean;
***REMOVED******REMOVED***sizes?:***REMOVED***string;
}

export***REMOVED***function***REMOVED***OptimizedImage({
***REMOVED******REMOVED***src,
***REMOVED******REMOVED***alt,
***REMOVED******REMOVED***width,
***REMOVED******REMOVED***height,
***REMOVED******REMOVED***className,
***REMOVED******REMOVED***priority***REMOVED***=***REMOVED***false,
***REMOVED******REMOVED***fill***REMOVED***=***REMOVED***false,
***REMOVED******REMOVED***sizes,
}:***REMOVED***OptimizedImageProps)***REMOVED***{
***REMOVED******REMOVED***const***REMOVED***[isLoading,***REMOVED***setIsLoading]***REMOVED***=***REMOVED***useState(true);
***REMOVED******REMOVED***const***REMOVED***[hasError,***REMOVED***setHasError]***REMOVED***=***REMOVED***useState(false);

***REMOVED******REMOVED***//***REMOVED***Default***REMOVED***responsive***REMOVED***sizes***REMOVED***for***REMOVED***mobile***REMOVED***optimization
***REMOVED******REMOVED***const***REMOVED***defaultSizes***REMOVED***=***REMOVED***sizes***REMOVED***||***REMOVED***"(max-width:***REMOVED***640px)***REMOVED***100vw,***REMOVED***(max-width:***REMOVED***1024px)***REMOVED***50vw,***REMOVED***33vw";

***REMOVED******REMOVED***if***REMOVED***(hasError)***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***return***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<div
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className={cn(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"flex***REMOVED***items-center***REMOVED***justify-center***REMOVED***bg-muted***REMOVED***text-muted-foreground",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***)}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***style={!fill***REMOVED***?***REMOVED***{***REMOVED***width,***REMOVED***height***REMOVED***}***REMOVED***:***REMOVED***undefined}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<span***REMOVED***className="text-xs">Image***REMOVED***unavailable</span>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</div>
***REMOVED******REMOVED******REMOVED******REMOVED***);
***REMOVED******REMOVED***}

***REMOVED******REMOVED***return***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED***<div***REMOVED***className={cn("relative***REMOVED***overflow-hidden",***REMOVED***className)}>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<Image
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***src={src}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***alt={alt}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***width={fill***REMOVED***?***REMOVED***undefined***REMOVED***:***REMOVED***width}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***height={fill***REMOVED***?***REMOVED***undefined***REMOVED***:***REMOVED***height}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***fill={fill}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***sizes={defaultSizes}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***priority={priority}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***loading={priority***REMOVED***?***REMOVED***undefined***REMOVED***:***REMOVED***"lazy"}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***quality={75}***REMOVED***//***REMOVED***Optimize***REMOVED***quality***REMOVED***for***REMOVED***mobile
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***onLoad={()***REMOVED***=>***REMOVED***setIsLoading(false)}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***onError={()***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***setIsLoading(false);
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***setHasError(true);
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***}}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className={cn(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"transition-opacity***REMOVED***duration-300",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***isLoading***REMOVED***?***REMOVED***"opacity-0"***REMOVED***:***REMOVED***"opacity-100"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***)}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***/>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{isLoading***REMOVED***&&***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<div***REMOVED***className="absolute***REMOVED***inset-0***REMOVED***bg-muted***REMOVED***animate-pulse"***REMOVED***/>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***)}
***REMOVED******REMOVED******REMOVED******REMOVED***</div>
***REMOVED******REMOVED***);
}
