"useclient";

import{cn}from"@/lib/utils";

interfaceSkeletonProps{
className?:string;
}

exportfunctionSkeleton({className}:SkeletonProps){
return(
<div
className={cn(
"animate-pulserounded-mdbg-muted",
className
)}
aria-hidden="true"
/>
);
}

exportfunctionSkeletonText({lines=3,className}:{lines?:number;className?:string}){
return(
<divclassName={cn("space-y-2",className)}>
{Array.from({length:lines}).map((_,i)=>(
<Skeleton
key={i}
className={cn(
"h-4",
i===lines-1?"w-3/4":"w-full"
)}
/>
))}
</div>
);
}

exportfunctionSkeletonCard({className}:{className?:string}){
return(
<divclassName={cn("rounded-lgborderbg-cardp-6space-y-4",className)}>
<divclassName="flexitems-startgap-4">
<SkeletonclassName="size-12rounded-full"/>
<divclassName="flex-1space-y-2">
<SkeletonclassName="h-5w-1/3"/>
<SkeletonclassName="h-4w-2/3"/>
</div>
</div>
<SkeletonTextlines={3}/>
</div>
);
}

exportfunctionSkeletonList({count=3,className}:{count?:number;className?:string}){
return(
<divclassName={cn("space-y-3",className)}>
{Array.from({length:count}).map((_,i)=>(
<divkey={i}className="flexitems-centergap-4p-4rounded-lgborder">
<SkeletonclassName="size-10rounded-full"/>
<divclassName="flex-1space-y-2">
<SkeletonclassName="h-4w-1/4"/>
<SkeletonclassName="h-3w-1/2"/>
</div>
<SkeletonclassName="h-8w-20"/>
</div>
))}
</div>
);
}

exportfunctionSkeletonTable({rows=5,cols=4}:{rows?:number;cols?:number}){
return(
<divclassName="space-y-3">
{/*Header*/}
<divclassName="flexgap-4pb-3border-b">
{Array.from({length:cols}).map((_,i)=>(
<Skeletonkey={i}className="h-4flex-1"/>
))}
</div>
{/*Rows*/}
{Array.from({length:rows}).map((_,rowIndex)=>(
<divkey={rowIndex}className="flexgap-4">
{Array.from({length:cols}).map((_,colIndex)=>(
<Skeletonkey={colIndex}className="h-8flex-1"/>
))}
</div>
))}
</div>
);
}
