"use***REMOVED***client";

import***REMOVED***{***REMOVED***cn***REMOVED***}***REMOVED***from***REMOVED***"@/lib/utils";

interface***REMOVED***SkeletonProps***REMOVED***{
***REMOVED******REMOVED***className?:***REMOVED***string;
}

export***REMOVED***function***REMOVED***Skeleton({***REMOVED***className***REMOVED***}:***REMOVED***SkeletonProps)***REMOVED***{
***REMOVED******REMOVED***return***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED***<div
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className={cn(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"animate-pulse***REMOVED***rounded-md***REMOVED***bg-muted",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***)}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***aria-hidden="true"
***REMOVED******REMOVED******REMOVED******REMOVED***/>
***REMOVED******REMOVED***);
}

export***REMOVED***function***REMOVED***SkeletonText({***REMOVED***lines***REMOVED***=***REMOVED***3,***REMOVED***className***REMOVED***}:***REMOVED***{***REMOVED***lines?:***REMOVED***number;***REMOVED***className?:***REMOVED***string***REMOVED***})***REMOVED***{
***REMOVED******REMOVED***return***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED***<div***REMOVED***className={cn("space-y-2",***REMOVED***className)}>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{Array.from({***REMOVED***length:***REMOVED***lines***REMOVED***}).map((_,***REMOVED***i)***REMOVED***=>***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<Skeleton
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***key={i}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className={cn(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"h-4",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***i***REMOVED***===***REMOVED***lines***REMOVED***-***REMOVED***1***REMOVED***?***REMOVED***"w-3/4"***REMOVED***:***REMOVED***"w-full"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***)}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***/>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***))}
***REMOVED******REMOVED******REMOVED******REMOVED***</div>
***REMOVED******REMOVED***);
}

export***REMOVED***function***REMOVED***SkeletonCard({***REMOVED***className***REMOVED***}:***REMOVED***{***REMOVED***className?:***REMOVED***string***REMOVED***})***REMOVED***{
***REMOVED******REMOVED***return***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED***<div***REMOVED***className={cn("rounded-lg***REMOVED***border***REMOVED***bg-card***REMOVED***p-6***REMOVED***space-y-4",***REMOVED***className)}>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<div***REMOVED***className="flex***REMOVED***items-start***REMOVED***gap-4">
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<Skeleton***REMOVED***className="size-12***REMOVED***rounded-full"***REMOVED***/>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<div***REMOVED***className="flex-1***REMOVED***space-y-2">
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<Skeleton***REMOVED***className="h-5***REMOVED***w-1/3"***REMOVED***/>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<Skeleton***REMOVED***className="h-4***REMOVED***w-2/3"***REMOVED***/>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</div>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</div>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<SkeletonText***REMOVED***lines={3}***REMOVED***/>
***REMOVED******REMOVED******REMOVED******REMOVED***</div>
***REMOVED******REMOVED***);
}

export***REMOVED***function***REMOVED***SkeletonList({***REMOVED***count***REMOVED***=***REMOVED***3,***REMOVED***className***REMOVED***}:***REMOVED***{***REMOVED***count?:***REMOVED***number;***REMOVED***className?:***REMOVED***string***REMOVED***})***REMOVED***{
***REMOVED******REMOVED***return***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED***<div***REMOVED***className={cn("space-y-3",***REMOVED***className)}>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{Array.from({***REMOVED***length:***REMOVED***count***REMOVED***}).map((_,***REMOVED***i)***REMOVED***=>***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<div***REMOVED***key={i}***REMOVED***className="flex***REMOVED***items-center***REMOVED***gap-4***REMOVED***p-4***REMOVED***rounded-lg***REMOVED***border">
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<Skeleton***REMOVED***className="size-10***REMOVED***rounded-full"***REMOVED***/>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<div***REMOVED***className="flex-1***REMOVED***space-y-2">
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<Skeleton***REMOVED***className="h-4***REMOVED***w-1/4"***REMOVED***/>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<Skeleton***REMOVED***className="h-3***REMOVED***w-1/2"***REMOVED***/>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</div>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<Skeleton***REMOVED***className="h-8***REMOVED***w-20"***REMOVED***/>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</div>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***))}
***REMOVED******REMOVED******REMOVED******REMOVED***</div>
***REMOVED******REMOVED***);
}

export***REMOVED***function***REMOVED***SkeletonTable({***REMOVED***rows***REMOVED***=***REMOVED***5,***REMOVED***cols***REMOVED***=***REMOVED***4***REMOVED***}:***REMOVED***{***REMOVED***rows?:***REMOVED***number;***REMOVED***cols?:***REMOVED***number***REMOVED***})***REMOVED***{
***REMOVED******REMOVED***return***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED***<div***REMOVED***className="space-y-3">
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{/****REMOVED***Header***REMOVED****/}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<div***REMOVED***className="flex***REMOVED***gap-4***REMOVED***pb-3***REMOVED***border-b">
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{Array.from({***REMOVED***length:***REMOVED***cols***REMOVED***}).map((_,***REMOVED***i)***REMOVED***=>***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<Skeleton***REMOVED***key={i}***REMOVED***className="h-4***REMOVED***flex-1"***REMOVED***/>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***))}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</div>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{/****REMOVED***Rows***REMOVED****/}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{Array.from({***REMOVED***length:***REMOVED***rows***REMOVED***}).map((_,***REMOVED***rowIndex)***REMOVED***=>***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<div***REMOVED***key={rowIndex}***REMOVED***className="flex***REMOVED***gap-4">
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{Array.from({***REMOVED***length:***REMOVED***cols***REMOVED***}).map((_,***REMOVED***colIndex)***REMOVED***=>***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<Skeleton***REMOVED***key={colIndex}***REMOVED***className="h-8***REMOVED***flex-1"***REMOVED***/>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***))}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</div>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***))}
***REMOVED******REMOVED******REMOVED******REMOVED***</div>
***REMOVED******REMOVED***);
}
