"use***REMOVED***client";

import***REMOVED***{***REMOVED***useEffect***REMOVED***}***REMOVED***from***REMOVED***"react";
import***REMOVED***{***REMOVED***useReportWebVitals***REMOVED***}***REMOVED***from***REMOVED***"next/web-vitals";
import***REMOVED***{***REMOVED***reportWebVitals,***REMOVED***rateMetric***REMOVED***}***REMOVED***from***REMOVED***"@/lib/performance";

/**
***REMOVED*******REMOVED***Component***REMOVED***to***REMOVED***report***REMOVED***Web***REMOVED***Vitals***REMOVED***metrics
***REMOVED*******REMOVED***Automatically***REMOVED***tracks***REMOVED***Core***REMOVED***Web***REMOVED***Vitals***REMOVED***and***REMOVED***reports***REMOVED***them
***REMOVED****/
export***REMOVED***function***REMOVED***WebVitalsReporter()***REMOVED***{
***REMOVED******REMOVED***useReportWebVitals((metric)***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***rating***REMOVED***=***REMOVED***rateMetric(metric.name,***REMOVED***metric.value);
***REMOVED******REMOVED******REMOVED******REMOVED***
***REMOVED******REMOVED******REMOVED******REMOVED***reportWebVitals({
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***name:***REMOVED***metric.name,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***value:***REMOVED***metric.value,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***rating,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***delta:***REMOVED***metric.delta,
***REMOVED******REMOVED******REMOVED******REMOVED***});
***REMOVED******REMOVED***});
***REMOVED******REMOVED***
***REMOVED******REMOVED***//***REMOVED***Monitor***REMOVED***long***REMOVED***tasks***REMOVED***in***REMOVED***development
***REMOVED******REMOVED***useEffect(()***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***if***REMOVED***(process.env.NODE_ENV***REMOVED***===***REMOVED***"development")***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***{***REMOVED***monitorLongTasks***REMOVED***}***REMOVED***=***REMOVED***require("@/lib/performance");
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***monitorLongTasks();
***REMOVED******REMOVED******REMOVED******REMOVED***}
***REMOVED******REMOVED***},***REMOVED***[]);
***REMOVED******REMOVED***
***REMOVED******REMOVED***return***REMOVED***null;
}
