"useclient";

importReact,{useState}from"react";
import{Button}from"@/components/ui/button";
import{
Dialog,
DialogContent,
DialogDescription,
DialogFooter,
DialogHeader,
DialogTitle,
}from"@/components/ui/dialog";
import{Ban,Loader2}from"lucide-react";

interfaceCancelButtonProps{
onCancel:()=>Promise<void>;
disabled?:boolean;
className?:string;
}

exportfunctionCancelButton({
onCancel,
disabled=false,
className,
}:CancelButtonProps){
const[showConfirmDialog,setShowConfirmDialog]=useState(false);
const[isCancelling,setIsCancelling]=useState(false);

consthandleCancelClick=()=>{
setShowConfirmDialog(true);
};

consthandleConfirmCancel=async()=>{
setIsCancelling(true);
try{
awaitonCancel();
setShowConfirmDialog(false);
}catch(error){
console.error("Errorcancellingworkflow:",error);
//Errorhandlingisdoneintheparentcomponent
}finally{
setIsCancelling(false);
}
};

consthandleCloseDialog=()=>{
if(!isCancelling){
setShowConfirmDialog(false);
}
};

return(
<>
<Button
variant="destructive"
size="sm"
onClick={handleCancelClick}
disabled={disabled||isCancelling}
className={className}
aria-label="Cancelworkflowexecution"
>
<BanclassName="h-4w-4"/>
CancelWorkflow
</Button>

<Dialogopen={showConfirmDialog}onOpenChange={handleCloseDialog}>
<DialogContent>
<DialogHeader>
<DialogTitle>CancelWorkflow?</DialogTitle>
<DialogDescription>
Areyousureyouwanttocancelthisworkflow?Anystepsthathave
alreadycompletedwillbepreserved,butin-progressandpending
stepswillbecancelled.
</DialogDescription>
</DialogHeader>
<DialogFooter>
<Button
variant="outline"
onClick={handleCloseDialog}
disabled={isCancelling}
>
KeepRunning
</Button>
<Button
variant="destructive"
onClick={handleConfirmCancel}
disabled={isCancelling}
>
{isCancelling?(
<>
<Loader2className="h-4w-4animate-spin"/>
Cancelling...
</>
):(
<>
<BanclassName="h-4w-4"/>
Yes,Cancel
</>
)}
</Button>
</DialogFooter>
</DialogContent>
</Dialog>
</>
);
}
