"useclient";

importReact,{useMemo}from"react";
import{WorkflowState}from"@/types";
import{Progress}from"@/components/ui/progress";
import{AgentIndicator}from"./AgentIndicator";
import{StepProgress}from"./StepProgress";
import{CancelButton}from"./CancelButton";
import{cn}from"@/lib/utils";
import{CheckCircle2,XCircle,Loader2,Ban}from"lucide-react";

interfaceExecutionTrackerProps{
workflow:WorkflowState;
onCancel?:()=>void;
onRetryStep?:(stepId:string)=>void;
className?:string;
}

exportfunctionExecutionTracker({
workflow,
onCancel,
onRetryStep,
className,
}:ExecutionTrackerProps){
//Memoizecalculationstoavoidunnecessaryre-renders
//Thisensuresupdatesoccurwithin500msofstatechange(Requirement2.2)
const{completedSteps,totalSteps,progressPercentage,estimatedTimeRemaining}=useMemo(()=>{
consttotal=workflow.steps.length;
constcompleted=workflow.steps.filter(
(step)=>step.status==="completed"
).length;
constpercentage=total>0?(completed/total)*100:0;

//Calculateestimatedtimeremainingbasedonaveragestepduration
letestimated=0;
if(workflow.startTime&&completed>0){
constelapsedMs=Date.now()-workflow.startTime.getTime();
constavgStepTime=elapsedMs/completed;
constremainingSteps=total-completed;
estimated=Math.ceil((avgStepTime*remainingSteps)/1000);//Converttoseconds
}

return{
completedSteps:completed,
totalSteps:total,
progressPercentage:percentage,
estimatedTimeRemaining:estimated,
};
},[workflow.steps,workflow.startTime]);

constformatTime=(seconds:number):string=>{
if(seconds<60){
return`${seconds}s`;
}
constminutes=Math.floor(seconds/60);
constremainingSeconds=seconds%60;
return`${minutes}m${remainingSeconds}s`;
};

constcurrentStep=workflow.steps.find((step)=>step.status==="running");
constisExecuting=workflow.status==="executing"||workflow.status==="planning";
constcanCancel=isExecuting&&onCancel;

//Calculatewhichstepswerecompletedvscancelled
constcompletedBeforeCancellation=workflow.steps.filter(
(step)=>step.status==="completed"
);
constcancelledSteps=workflow.steps.filter(
(step)=>step.status==="cancelled"
);

return(
<div
className={cn(
"rounded-lgborderbg-cardp-4sm:p-6shadow-sm",
className
)}
role="region"
aria-label="Workflowexecutiontracker"
>
{/*Header-Responsivelayout*/}
<divclassName="mb-3sm:mb-4flexflex-colsm:flex-rowsm:items-centersm:justify-betweengap-2sm:gap-4">
<divclassName="flex-1min-w-0">
<h2className="text-basesm:text-lgfont-semibold">ExecutionProgress</h2>
<spanclassName="text-xssm:text-smtext-muted-foreground"aria-live="polite">
{completedSteps}/{totalSteps}steps
</span>
</div>
{canCancel&&(
<CancelButton
onCancel={async()=>{
if(onCancel){
awaitonCancel();
}
}}
/>
)}
</div>

{/*ProgressBar-Responsivesizing*/}
<divclassName="mb-4sm:mb-6">
<Progress
value={progressPercentage}
className="h-2sm:h-3"
aria-label={`Progress:${Math.round(progressPercentage)}%`}
/>
<divclassName="mt-1.5sm:mt-2flexflex-colxs:flex-rowxs:items-centerxs:justify-betweengap-1xs:gap-2text-2xssm:text-xstext-muted-foreground">
<span>{Math.round(progressPercentage)}%complete</span>
{estimatedTimeRemaining>0&&workflow.status==="executing"&&(
<spanaria-live="polite">
Est.{formatTime(estimatedTimeRemaining)}remaining
</span>
)}
</div>
</div>

{/*CurrentStepIndicator-Responsivepaddingandtext*/}
{currentStep&&(
<divclassName="mb-3sm:mb-4rounded-mdbg-blue-50p-2.5sm:p-3dark:bg-blue-950/20">
<divclassName="flexitems-startsm:items-centergap-2sm:gap-3">
<Loader2className="h-4w-4sm:h-5sm:w-5animate-spintext-blue-500shrink-0mt-0.5sm:mt-0"aria-hidden="true"/>
<divclassName="flex-1min-w-0">
<AgentIndicatoragentName={currentStep.agentName}/>
<pclassName="mt-0.5sm:mt-1text-xssm:text-smtext-muted-foregroundbreak-words">
{currentStep.action}
</p>
</div>
</div>
</div>
)}

{/*StepsList*/}
<divclassName="space-y-2"role="list"aria-label="Workflowsteps">
{workflow.steps.map((step,index)=>(
<StepProgress
key={step.id}
step={step}
stepNumber={index+1}
onRetry={onRetryStep}
/>
))}
</div>

{/*StatusMessage-Responsivepaddingandtext*/}
{workflow.status==="completed"&&(
<div
className="mt-3sm:mt-4rounded-mdbg-green-50p-2.5sm:p-3text-xssm:text-smtext-green-700dark:bg-green-950/20dark:text-green-400"
role="status"
aria-live="polite"
>
<CheckCircle2className="mr-1.5sm:mr-2inlineh-3.5w-3.5sm:h-4sm:w-4"aria-hidden="true"/>
Workflowcompletedsuccessfully
</div>
)}

{workflow.status==="failed"&&(
<div
className="mt-3sm:mt-4rounded-mdbg-red-50p-2.5sm:p-3text-xssm:text-smtext-red-700dark:bg-red-950/20dark:text-red-400"
role="alert"
aria-live="assertive"
>
<XCircleclassName="mr-1.5sm:mr-2inlineh-3.5w-3.5sm:h-4sm:w-4"aria-hidden="true"/>
<spanclassName="break-words">Workflowfailed:{workflow.error||"Unknownerror"}</span>
</div>
)}

{workflow.status==="cancelled"&&(
<div
className="mt-3sm:mt-4rounded-mdbg-orange-50p-2.5sm:p-3dark:bg-orange-950/20"
role="status"
aria-live="polite"
>
<divclassName="flexitems-startgap-1.5sm:gap-2text-xssm:text-smtext-orange-700dark:text-orange-400">
<BanclassName="mt-0.5h-3.5w-3.5sm:h-4sm:w-4shrink-0"aria-hidden="true"/>
<divclassName="flex-1min-w-0">
<pclassName="font-medium">Workflowcancelled</p>
{completedBeforeCancellation.length>0&&(
<pclassName="mt-0.5sm:mt-1text-2xssm:text-xsbreak-words">
{completedBeforeCancellation.length}step(s)completedbeforecancellation.
{cancelledSteps.length>0&&`${cancelledSteps.length}step(s)cancelled.`}
</p>
)}
</div>
</div>
</div>
)}
</div>
);
}
