"use***REMOVED***client";

import***REMOVED***React,***REMOVED***{***REMOVED***useMemo***REMOVED***}***REMOVED***from***REMOVED***"react";
import***REMOVED***{***REMOVED***WorkflowState***REMOVED***}***REMOVED***from***REMOVED***"@/types";
import***REMOVED***{***REMOVED***Progress***REMOVED***}***REMOVED***from***REMOVED***"@/components/ui/progress";
import***REMOVED***{***REMOVED***AgentIndicator***REMOVED***}***REMOVED***from***REMOVED***"./AgentIndicator";
import***REMOVED***{***REMOVED***StepProgress***REMOVED***}***REMOVED***from***REMOVED***"./StepProgress";
import***REMOVED***{***REMOVED***CancelButton***REMOVED***}***REMOVED***from***REMOVED***"./CancelButton";
import***REMOVED***{***REMOVED***cn***REMOVED***}***REMOVED***from***REMOVED***"@/lib/utils";
import***REMOVED***{***REMOVED***CheckCircle2,***REMOVED***XCircle,***REMOVED***Loader2,***REMOVED***Ban***REMOVED***}***REMOVED***from***REMOVED***"lucide-react";

interface***REMOVED***ExecutionTrackerProps***REMOVED***{
***REMOVED******REMOVED***workflow:***REMOVED***WorkflowState;
***REMOVED******REMOVED***onCancel?:***REMOVED***()***REMOVED***=>***REMOVED***void;
***REMOVED******REMOVED***onRetryStep?:***REMOVED***(stepId:***REMOVED***string)***REMOVED***=>***REMOVED***void;
***REMOVED******REMOVED***className?:***REMOVED***string;
}

export***REMOVED***function***REMOVED***ExecutionTracker({
***REMOVED******REMOVED***workflow,
***REMOVED******REMOVED***onCancel,
***REMOVED******REMOVED***onRetryStep,
***REMOVED******REMOVED***className,
}:***REMOVED***ExecutionTrackerProps)***REMOVED***{
***REMOVED******REMOVED***//***REMOVED***Memoize***REMOVED***calculations***REMOVED***to***REMOVED***avoid***REMOVED***unnecessary***REMOVED***re-renders
***REMOVED******REMOVED***//***REMOVED***This***REMOVED***ensures***REMOVED***updates***REMOVED***occur***REMOVED***within***REMOVED***500ms***REMOVED***of***REMOVED***state***REMOVED***change***REMOVED***(Requirement***REMOVED***2.2)
***REMOVED******REMOVED***const***REMOVED***{***REMOVED***completedSteps,***REMOVED***totalSteps,***REMOVED***progressPercentage,***REMOVED***estimatedTimeRemaining***REMOVED***}***REMOVED***=***REMOVED***useMemo(()***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***total***REMOVED***=***REMOVED***workflow.steps.length;
***REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***completed***REMOVED***=***REMOVED***workflow.steps.filter(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***(step)***REMOVED***=>***REMOVED***step.status***REMOVED***===***REMOVED***"completed"
***REMOVED******REMOVED******REMOVED******REMOVED***).length;
***REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***percentage***REMOVED***=***REMOVED***total***REMOVED***>***REMOVED***0***REMOVED***?***REMOVED***(completed***REMOVED***/***REMOVED***total)***REMOVED*******REMOVED***100***REMOVED***:***REMOVED***0;

***REMOVED******REMOVED******REMOVED******REMOVED***//***REMOVED***Calculate***REMOVED***estimated***REMOVED***time***REMOVED***remaining***REMOVED***based***REMOVED***on***REMOVED***average***REMOVED***step***REMOVED***duration
***REMOVED******REMOVED******REMOVED******REMOVED***let***REMOVED***estimated***REMOVED***=***REMOVED***0;
***REMOVED******REMOVED******REMOVED******REMOVED***if***REMOVED***(workflow.startTime***REMOVED***&&***REMOVED***completed***REMOVED***>***REMOVED***0)***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***elapsedMs***REMOVED***=***REMOVED***Date.now()***REMOVED***-***REMOVED***workflow.startTime.getTime();
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***avgStepTime***REMOVED***=***REMOVED***elapsedMs***REMOVED***/***REMOVED***completed;
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***remainingSteps***REMOVED***=***REMOVED***total***REMOVED***-***REMOVED***completed;
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***estimated***REMOVED***=***REMOVED***Math.ceil((avgStepTime***REMOVED*******REMOVED***remainingSteps)***REMOVED***/***REMOVED***1000);***REMOVED***//***REMOVED***Convert***REMOVED***to***REMOVED***seconds
***REMOVED******REMOVED******REMOVED******REMOVED***}

***REMOVED******REMOVED******REMOVED******REMOVED***return***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***completedSteps:***REMOVED***completed,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***totalSteps:***REMOVED***total,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***progressPercentage:***REMOVED***percentage,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***estimatedTimeRemaining:***REMOVED***estimated,
***REMOVED******REMOVED******REMOVED******REMOVED***};
***REMOVED******REMOVED***},***REMOVED***[workflow.steps,***REMOVED***workflow.startTime]);

***REMOVED******REMOVED***const***REMOVED***formatTime***REMOVED***=***REMOVED***(seconds:***REMOVED***number):***REMOVED***string***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***if***REMOVED***(seconds***REMOVED***<***REMOVED***60)***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***return***REMOVED***`${seconds}s`;
***REMOVED******REMOVED******REMOVED******REMOVED***}
***REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***minutes***REMOVED***=***REMOVED***Math.floor(seconds***REMOVED***/***REMOVED***60);
***REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***remainingSeconds***REMOVED***=***REMOVED***seconds***REMOVED***%***REMOVED***60;
***REMOVED******REMOVED******REMOVED******REMOVED***return***REMOVED***`${minutes}m***REMOVED***${remainingSeconds}s`;
***REMOVED******REMOVED***};

***REMOVED******REMOVED***const***REMOVED***currentStep***REMOVED***=***REMOVED***workflow.steps.find((step)***REMOVED***=>***REMOVED***step.status***REMOVED***===***REMOVED***"running");
***REMOVED******REMOVED***const***REMOVED***isExecuting***REMOVED***=***REMOVED***workflow.status***REMOVED***===***REMOVED***"executing"***REMOVED***||***REMOVED***workflow.status***REMOVED***===***REMOVED***"planning";
***REMOVED******REMOVED***const***REMOVED***canCancel***REMOVED***=***REMOVED***isExecuting***REMOVED***&&***REMOVED***onCancel;

***REMOVED******REMOVED***//***REMOVED***Calculate***REMOVED***which***REMOVED***steps***REMOVED***were***REMOVED***completed***REMOVED***vs***REMOVED***cancelled
***REMOVED******REMOVED***const***REMOVED***completedBeforeCancellation***REMOVED***=***REMOVED***workflow.steps.filter(
***REMOVED******REMOVED******REMOVED******REMOVED***(step)***REMOVED***=>***REMOVED***step.status***REMOVED***===***REMOVED***"completed"
***REMOVED******REMOVED***);
***REMOVED******REMOVED***const***REMOVED***cancelledSteps***REMOVED***=***REMOVED***workflow.steps.filter(
***REMOVED******REMOVED******REMOVED******REMOVED***(step)***REMOVED***=>***REMOVED***step.status***REMOVED***===***REMOVED***"cancelled"
***REMOVED******REMOVED***);

***REMOVED******REMOVED***return***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED***<div
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className={cn(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"rounded-lg***REMOVED***border***REMOVED***bg-card***REMOVED***p-4***REMOVED***sm:p-6***REMOVED***shadow-sm",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***)}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***role="region"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***aria-label="Workflow***REMOVED***execution***REMOVED***tracker"
***REMOVED******REMOVED******REMOVED******REMOVED***>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{/****REMOVED***Header***REMOVED***-***REMOVED***Responsive***REMOVED***layout***REMOVED****/}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<div***REMOVED***className="mb-3***REMOVED***sm:mb-4***REMOVED***flex***REMOVED***flex-col***REMOVED***sm:flex-row***REMOVED***sm:items-center***REMOVED***sm:justify-between***REMOVED***gap-2***REMOVED***sm:gap-4">
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<div***REMOVED***className="flex-1***REMOVED***min-w-0">
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<h2***REMOVED***className="text-base***REMOVED***sm:text-lg***REMOVED***font-semibold">Execution***REMOVED***Progress</h2>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<span***REMOVED***className="text-xs***REMOVED***sm:text-sm***REMOVED***text-muted-foreground"***REMOVED***aria-live="polite">
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{completedSteps}***REMOVED***/***REMOVED***{totalSteps}***REMOVED***steps
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</span>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</div>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{canCancel***REMOVED***&&***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<CancelButton
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***onCancel={async***REMOVED***()***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***if***REMOVED***(onCancel)***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***await***REMOVED***onCancel();
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***}}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***/>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***)}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</div>

***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{/****REMOVED***Progress***REMOVED***Bar***REMOVED***-***REMOVED***Responsive***REMOVED***sizing***REMOVED****/}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<div***REMOVED***className="mb-4***REMOVED***sm:mb-6">
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<Progress
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***value={progressPercentage}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className="h-2***REMOVED***sm:h-3"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***aria-label={`Progress:***REMOVED***${Math.round(progressPercentage)}%`}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***/>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<div***REMOVED***className="mt-1.5***REMOVED***sm:mt-2***REMOVED***flex***REMOVED***flex-col***REMOVED***xs:flex-row***REMOVED***xs:items-center***REMOVED***xs:justify-between***REMOVED***gap-1***REMOVED***xs:gap-2***REMOVED***text-2xs***REMOVED***sm:text-xs***REMOVED***text-muted-foreground">
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<span>{Math.round(progressPercentage)}%***REMOVED***complete</span>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{estimatedTimeRemaining***REMOVED***>***REMOVED***0***REMOVED***&&***REMOVED***workflow.status***REMOVED***===***REMOVED***"executing"***REMOVED***&&***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<span***REMOVED***aria-live="polite">
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***Est.***REMOVED***{formatTime(estimatedTimeRemaining)}***REMOVED***remaining
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</span>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***)}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</div>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</div>

***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{/****REMOVED***Current***REMOVED***Step***REMOVED***Indicator***REMOVED***-***REMOVED***Responsive***REMOVED***padding***REMOVED***and***REMOVED***text***REMOVED****/}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{currentStep***REMOVED***&&***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<div***REMOVED***className="mb-3***REMOVED***sm:mb-4***REMOVED***rounded-md***REMOVED***bg-blue-50***REMOVED***p-2.5***REMOVED***sm:p-3***REMOVED***dark:bg-blue-950/20">
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<div***REMOVED***className="flex***REMOVED***items-start***REMOVED***sm:items-center***REMOVED***gap-2***REMOVED***sm:gap-3">
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<Loader2***REMOVED***className="h-4***REMOVED***w-4***REMOVED***sm:h-5***REMOVED***sm:w-5***REMOVED***animate-spin***REMOVED***text-blue-500***REMOVED***shrink-0***REMOVED***mt-0.5***REMOVED***sm:mt-0"***REMOVED***aria-hidden="true"***REMOVED***/>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<div***REMOVED***className="flex-1***REMOVED***min-w-0">
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<AgentIndicator***REMOVED***agentName={currentStep.agentName}***REMOVED***/>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<p***REMOVED***className="mt-0.5***REMOVED***sm:mt-1***REMOVED***text-xs***REMOVED***sm:text-sm***REMOVED***text-muted-foreground***REMOVED***break-words">
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{currentStep.action}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</p>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</div>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</div>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</div>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***)}

***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{/****REMOVED***Steps***REMOVED***List***REMOVED****/}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<div***REMOVED***className="space-y-2"***REMOVED***role="list"***REMOVED***aria-label="Workflow***REMOVED***steps">
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{workflow.steps.map((step,***REMOVED***index)***REMOVED***=>***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<StepProgress
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***key={step.id}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***step={step}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***stepNumber={index***REMOVED***+***REMOVED***1}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***onRetry={onRetryStep}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***/>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***))}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</div>

***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{/****REMOVED***Status***REMOVED***Message***REMOVED***-***REMOVED***Responsive***REMOVED***padding***REMOVED***and***REMOVED***text***REMOVED****/}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{workflow.status***REMOVED***===***REMOVED***"completed"***REMOVED***&&***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<div
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className="mt-3***REMOVED***sm:mt-4***REMOVED***rounded-md***REMOVED***bg-green-50***REMOVED***p-2.5***REMOVED***sm:p-3***REMOVED***text-xs***REMOVED***sm:text-sm***REMOVED***text-green-700***REMOVED***dark:bg-green-950/20***REMOVED***dark:text-green-400"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***role="status"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***aria-live="polite"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<CheckCircle2***REMOVED***className="mr-1.5***REMOVED***sm:mr-2***REMOVED***inline***REMOVED***h-3.5***REMOVED***w-3.5***REMOVED***sm:h-4***REMOVED***sm:w-4"***REMOVED***aria-hidden="true"***REMOVED***/>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***Workflow***REMOVED***completed***REMOVED***successfully
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</div>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***)}

***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{workflow.status***REMOVED***===***REMOVED***"failed"***REMOVED***&&***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<div
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className="mt-3***REMOVED***sm:mt-4***REMOVED***rounded-md***REMOVED***bg-red-50***REMOVED***p-2.5***REMOVED***sm:p-3***REMOVED***text-xs***REMOVED***sm:text-sm***REMOVED***text-red-700***REMOVED***dark:bg-red-950/20***REMOVED***dark:text-red-400"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***role="alert"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***aria-live="assertive"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<XCircle***REMOVED***className="mr-1.5***REMOVED***sm:mr-2***REMOVED***inline***REMOVED***h-3.5***REMOVED***w-3.5***REMOVED***sm:h-4***REMOVED***sm:w-4"***REMOVED***aria-hidden="true"***REMOVED***/>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<span***REMOVED***className="break-words">Workflow***REMOVED***failed:***REMOVED***{workflow.error***REMOVED***||***REMOVED***"Unknown***REMOVED***error"}</span>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</div>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***)}

***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{workflow.status***REMOVED***===***REMOVED***"cancelled"***REMOVED***&&***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<div
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className="mt-3***REMOVED***sm:mt-4***REMOVED***rounded-md***REMOVED***bg-orange-50***REMOVED***p-2.5***REMOVED***sm:p-3***REMOVED***dark:bg-orange-950/20"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***role="status"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***aria-live="polite"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<div***REMOVED***className="flex***REMOVED***items-start***REMOVED***gap-1.5***REMOVED***sm:gap-2***REMOVED***text-xs***REMOVED***sm:text-sm***REMOVED***text-orange-700***REMOVED***dark:text-orange-400">
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<Ban***REMOVED***className="mt-0.5***REMOVED***h-3.5***REMOVED***w-3.5***REMOVED***sm:h-4***REMOVED***sm:w-4***REMOVED***shrink-0"***REMOVED***aria-hidden="true"***REMOVED***/>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<div***REMOVED***className="flex-1***REMOVED***min-w-0">
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<p***REMOVED***className="font-medium">Workflow***REMOVED***cancelled</p>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{completedBeforeCancellation.length***REMOVED***>***REMOVED***0***REMOVED***&&***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<p***REMOVED***className="mt-0.5***REMOVED***sm:mt-1***REMOVED***text-2xs***REMOVED***sm:text-xs***REMOVED***break-words">
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{completedBeforeCancellation.length}***REMOVED***step(s)***REMOVED***completed***REMOVED***before***REMOVED***cancellation.
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{cancelledSteps.length***REMOVED***>***REMOVED***0***REMOVED***&&***REMOVED***`***REMOVED***${cancelledSteps.length}***REMOVED***step(s)***REMOVED***cancelled.`}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</p>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***)}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</div>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</div>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</div>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***)}
***REMOVED******REMOVED******REMOVED******REMOVED***</div>
***REMOVED******REMOVED***);
}
