"useclient";

importReact,{useState}from"react";
import{WorkflowStep}from"@/types";
import{cn}from"@/lib/utils";
import{
CheckCircle2,
Circle,
XCircle,
Loader2,
Ban,
ChevronDown,
ChevronRight,
RotateCw,
}from"lucide-react";
import{Button}from"@/components/ui/button";

interfaceStepProgressProps{
step:WorkflowStep;
stepNumber:number;
onRetry?:(stepId:string)=>void;
className?:string;
}

conststatusIcons={
pending:Circle,
running:Loader2,
completed:CheckCircle2,
failed:XCircle,
cancelled:Ban,
};

conststatusColors={
pending:"text-muted-foreground",
running:"text-blue-500animate-spin",
completed:"text-green-500",
failed:"text-red-500",
cancelled:"text-orange-500",
};

exportfunctionStepProgress({
step,
stepNumber,
onRetry,
className,
}:StepProgressProps){
const[isExpanded,setIsExpanded]=useState(false);
constStatusIcon=statusIcons[step.status];
conststatusColor=statusColors[step.status];

consthasDetails=step.input||step.output||step.error;
constcanExpand=hasDetails&&(step.status==="completed"||step.status==="failed");

consthandleToggle=()=>{
if(canExpand){
setIsExpanded(!isExpanded);
}
};

consthandleRetry=(e:React.MouseEvent)=>{
e.stopPropagation();
if(onRetry){
onRetry(step.id);
}
};

return(
<div
className={cn(
"rounded-mdbordertransition-colors",
step.status==="running"&&"border-blue-200bg-blue-50dark:border-blue-900dark:bg-blue-950/20",
step.status==="completed"&&"border-green-200bg-green-50/50dark:border-green-900dark:bg-green-950/10",
step.status==="failed"&&"border-red-200bg-red-50dark:border-red-900dark:bg-red-950/20",
step.status==="cancelled"&&"border-orange-200bg-orange-50dark:border-orange-900dark:bg-orange-950/20",
step.status==="pending"&&"border-borderbg-card",
className
)}
role="article"
aria-label={`Step${stepNumber}:${step.agentName}`}
>
<div
className={cn(
"flexitems-startgap-3p-4",
canExpand&&"cursor-pointerhover:bg-accent/50"
)}
onClick={handleToggle}
role={canExpand?"button":undefined}
aria-expanded={canExpand?isExpanded:undefined}
tabIndex={canExpand?0:undefined}
onKeyDown={(e)=>{
if(canExpand&&(e.key==="Enter"||e.key==="")){
e.preventDefault();
handleToggle();
}
}}
>
<StatusIcon
className={cn("mt-0.5h-5w-5shrink-0",statusColor)}
aria-label={`Status:${step.status}`}
/>

<divclassName="flex-1min-w-0">
<divclassName="flexitems-centergap-2flex-wrap">
<spanclassName="text-xsfont-mediumtext-muted-foreground">
Step{stepNumber}
</span>
<spanclassName="text-smfont-medium">{step.agentName}</span>
{step.status==="running"&&(
<spanclassName="text-xstext-blue-600dark:text-blue-400">
Inprogress...
</span>
)}
</div>

<pclassName="mt-1text-smtext-muted-foreground">
{step.action}
</p>

{step.error&&(
<divclassName="mt-2flexitems-startgap-2">
<pclassName="flex-1text-smtext-red-600dark:text-red-400"role="alert">
<strong>Error:</strong>{step.error}
</p>
{onRetry&&(
<Button
size="sm"
variant="outline"
onClick={handleRetry}
className="shrink-0"
aria-label="Retrythisstep"
>
<RotateCwclassName="h-3w-3"/>
Retry
</Button>
)}
</div>
)}

{step.startTime&&step.endTime&&(
<pclassName="mt-1text-xstext-muted-foreground">
Duration:{Math.round((step.endTime.getTime()-step.startTime.getTime())/1000)}s
</p>
)}
</div>

{canExpand&&(
<divclassName="shrink-0">
{isExpanded?(
<ChevronDownclassName="h-5w-5text-muted-foreground"aria-hidden="true"/>
):(
<ChevronRightclassName="h-5w-5text-muted-foreground"aria-hidden="true"/>
)}
</div>
)}
</div>

{/*ExpandedDetails*/}
{isExpanded&&canExpand&&(
<divclassName="border-tpx-4py-3space-y-3">
{step.input&&Object.keys(step.input).length>0&&(
<div>
<h4className="text-xsfont-semibolduppercasetext-muted-foregroundmb-2">
Input
</h4>
<preclassName="rounded-mdbg-mutedp-3text-xsoverflow-x-auto">
{JSON.stringify(step.input,null,2)}
</pre>
</div>
)}

{step.output&&Object.keys(step.output).length>0&&(
<div>
<h4className="text-xsfont-semibolduppercasetext-muted-foregroundmb-2">
Output
</h4>
<preclassName="rounded-mdbg-mutedp-3text-xsoverflow-x-auto">
{JSON.stringify(step.output,null,2)}
</pre>
</div>
)}
</div>
)}
</div>
);
}
