import***REMOVED***{***REMOVED***createWorkflow,***REMOVED***updateWorkflow,***REMOVED***addWorkflowHistory***REMOVED***}***REMOVED***from***REMOVED***"@/lib/supabase/queries";
import***REMOVED***{***REMOVED***generateWorkflowPlan***REMOVED***}***REMOVED***from***REMOVED***"@/lib/llm/client";
import***REMOVED***type***REMOVED***{***REMOVED***WorkflowStep***REMOVED***}***REMOVED***from***REMOVED***"@/types";
import***REMOVED***type***REMOVED***{***REMOVED***SupabaseClient***REMOVED***}***REMOVED***from***REMOVED***"@supabase/supabase-js";
import***REMOVED***type***REMOVED***{***REMOVED***Database***REMOVED***}***REMOVED***from***REMOVED***"@/lib/supabase/database.types";

export***REMOVED***interface***REMOVED***WorkflowExecutionResult***REMOVED***{
***REMOVED******REMOVED***workflowId:***REMOVED***string;
***REMOVED******REMOVED***status:***REMOVED***"planning"***REMOVED***|***REMOVED***"executing"***REMOVED***|***REMOVED***"completed"***REMOVED***|***REMOVED***"failed"***REMOVED***|***REMOVED***"cancelled";
***REMOVED******REMOVED***steps:***REMOVED***WorkflowStep[];
***REMOVED******REMOVED***results:***REMOVED***any[];
***REMOVED******REMOVED***error?:***REMOVED***string;
}

/**
***REMOVED*******REMOVED***Create***REMOVED***and***REMOVED***plan***REMOVED***a***REMOVED***new***REMOVED***workflow
***REMOVED*******REMOVED***@param***REMOVED***userId***REMOVED***-***REMOVED***The***REMOVED***authenticated***REMOVED***user's***REMOVED***ID
***REMOVED*******REMOVED***@param***REMOVED***command***REMOVED***-***REMOVED***The***REMOVED***user's***REMOVED***workflow***REMOVED***command
***REMOVED*******REMOVED***@param***REMOVED***serviceClient***REMOVED***-***REMOVED***Supabase***REMOVED***service***REMOVED***role***REMOVED***client***REMOVED***for***REMOVED***database***REMOVED***mutations
***REMOVED****/
export***REMOVED***async***REMOVED***function***REMOVED***createAndPlanWorkflow(
***REMOVED******REMOVED***userId:***REMOVED***string,
***REMOVED******REMOVED***command:***REMOVED***string,
***REMOVED******REMOVED***serviceClient:***REMOVED***SupabaseClient<Database>
):***REMOVED***Promise<{***REMOVED***workflowId:***REMOVED***string;***REMOVED***steps:***REMOVED***WorkflowStep[]***REMOVED***}>***REMOVED***{
***REMOVED******REMOVED***try***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***//***REMOVED***Generate***REMOVED***workflow***REMOVED***plan***REMOVED***using***REMOVED***LLM
***REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***plan***REMOVED***=***REMOVED***await***REMOVED***generateWorkflowPlan(command);

***REMOVED******REMOVED******REMOVED******REMOVED***//***REMOVED***Convert***REMOVED***plan***REMOVED***steps***REMOVED***to***REMOVED***WorkflowStep***REMOVED***format
***REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***steps:***REMOVED***WorkflowStep[]***REMOVED***=***REMOVED***plan.steps.map((step,***REMOVED***index)***REMOVED***=>***REMOVED***({
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***id:***REMOVED***step.id,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***agentName:***REMOVED***step.agentName,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***action:***REMOVED***step.action,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***description:***REMOVED***step.description,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***status:***REMOVED***"pending"***REMOVED***as***REMOVED***const,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***order:***REMOVED***index,
***REMOVED******REMOVED******REMOVED******REMOVED***}));
***REMOVED******REMOVED******REMOVED******REMOVED***
***REMOVED******REMOVED******REMOVED******REMOVED***//***REMOVED***Create***REMOVED***workflow***REMOVED***in***REMOVED***database***REMOVED***using***REMOVED***service***REMOVED***role***REMOVED***client
***REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***workflow***REMOVED***=***REMOVED***await***REMOVED***createWorkflow({
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***user_id:***REMOVED***userId,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***command,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***status:***REMOVED***"planning",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***steps:***REMOVED***steps***REMOVED***as***REMOVED***any,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***results:***REMOVED***[],
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***start_time:***REMOVED***new***REMOVED***Date().toISOString(),
***REMOVED******REMOVED******REMOVED******REMOVED***},***REMOVED***serviceClient);

***REMOVED******REMOVED******REMOVED******REMOVED***console.log(`[Workflow***REMOVED***Service]***REMOVED***Workflow***REMOVED***created***REMOVED***successfully`,***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***operation:***REMOVED***"createAndPlanWorkflow",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***userId,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***workflowId:***REMOVED***workflow.id,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***stepCount:***REMOVED***steps.length,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***command:***REMOVED***command.substring(0,***REMOVED***100),
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***timestamp:***REMOVED***new***REMOVED***Date().toISOString(),
***REMOVED******REMOVED******REMOVED******REMOVED***});

***REMOVED******REMOVED******REMOVED******REMOVED***return***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***workflowId:***REMOVED***workflow.id,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***steps,
***REMOVED******REMOVED******REMOVED******REMOVED***};
***REMOVED******REMOVED***}***REMOVED***catch***REMOVED***(error)***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***console.error(`[Workflow***REMOVED***Service]***REMOVED***Failed***REMOVED***to***REMOVED***create***REMOVED***and***REMOVED***plan***REMOVED***workflow`,***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***operation:***REMOVED***"createAndPlanWorkflow",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***userId,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***error:***REMOVED***error***REMOVED***instanceof***REMOVED***Error***REMOVED***?***REMOVED***error.message***REMOVED***:***REMOVED***"Unknown***REMOVED***error",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***errorStack:***REMOVED***error***REMOVED***instanceof***REMOVED***Error***REMOVED***?***REMOVED***error.stack***REMOVED***:***REMOVED***undefined,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***command:***REMOVED***command.substring(0,***REMOVED***100),
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***commandLength:***REMOVED***command.length,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***message:***REMOVED***"Workflow***REMOVED***creation***REMOVED***failed***REMOVED***during***REMOVED***planning***REMOVED***or***REMOVED***database***REMOVED***insertion",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***timestamp:***REMOVED***new***REMOVED***Date().toISOString(),
***REMOVED******REMOVED******REMOVED******REMOVED***});
***REMOVED******REMOVED******REMOVED******REMOVED***throw***REMOVED***error;
***REMOVED******REMOVED***}
}

/**
***REMOVED*******REMOVED***Execute***REMOVED***a***REMOVED***workflow***REMOVED***step
***REMOVED****/
export***REMOVED***async***REMOVED***function***REMOVED***executeWorkflowStep(
***REMOVED******REMOVED***workflowId:***REMOVED***string,
***REMOVED******REMOVED***stepId:***REMOVED***string,
***REMOVED******REMOVED***accessToken:***REMOVED***string
):***REMOVED***Promise<{***REMOVED***success:***REMOVED***boolean;***REMOVED***output?:***REMOVED***any;***REMOVED***error?:***REMOVED***string***REMOVED***}>***REMOVED***{
***REMOVED******REMOVED***try***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***//***REMOVED***This***REMOVED***is***REMOVED***where***REMOVED***you***REMOVED***would***REMOVED***call***REMOVED***the***REMOVED***appropriate***REMOVED***agent
***REMOVED******REMOVED******REMOVED******REMOVED***//***REMOVED***For***REMOVED***now,***REMOVED***we'll***REMOVED***simulate***REMOVED***execution
***REMOVED******REMOVED******REMOVED******REMOVED***
***REMOVED******REMOVED******REMOVED******REMOVED***//***REMOVED***TODO:***REMOVED***Implement***REMOVED***actual***REMOVED***agent***REMOVED***execution
***REMOVED******REMOVED******REMOVED******REMOVED***//***REMOVED***-***REMOVED***Get***REMOVED***step***REMOVED***details
***REMOVED******REMOVED******REMOVED******REMOVED***//***REMOVED***-***REMOVED***Call***REMOVED***appropriate***REMOVED***agent***REMOVED***(EmailAgent,***REMOVED***DriveAgent,***REMOVED***etc.)
***REMOVED******REMOVED******REMOVED******REMOVED***//***REMOVED***-***REMOVED***Pass***REMOVED***Google***REMOVED***OAuth***REMOVED***access***REMOVED***token
***REMOVED******REMOVED******REMOVED******REMOVED***//***REMOVED***-***REMOVED***Return***REMOVED***results
***REMOVED******REMOVED******REMOVED******REMOVED***
***REMOVED******REMOVED******REMOVED******REMOVED***console.log(`[Workflow***REMOVED***Service]***REMOVED***Workflow***REMOVED***step***REMOVED***executed***REMOVED***successfully`,***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***operation:***REMOVED***"executeWorkflowStep",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***workflowId,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***stepId,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***timestamp:***REMOVED***new***REMOVED***Date().toISOString(),
***REMOVED******REMOVED******REMOVED******REMOVED***});
***REMOVED******REMOVED******REMOVED******REMOVED***
***REMOVED******REMOVED******REMOVED******REMOVED***return***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***success:***REMOVED***true,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***output:***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***message:***REMOVED***"Step***REMOVED***executed***REMOVED***successfully",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***timestamp:***REMOVED***new***REMOVED***Date().toISOString(),
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***},
***REMOVED******REMOVED******REMOVED******REMOVED***};
***REMOVED******REMOVED***}***REMOVED***catch***REMOVED***(error)***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***console.error(`[Workflow***REMOVED***Service]***REMOVED***Workflow***REMOVED***step***REMOVED***execution***REMOVED***failed`,***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***operation:***REMOVED***"executeWorkflowStep",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***workflowId,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***stepId,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***error:***REMOVED***error***REMOVED***instanceof***REMOVED***Error***REMOVED***?***REMOVED***error.message***REMOVED***:***REMOVED***"Unknown***REMOVED***error",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***errorStack:***REMOVED***error***REMOVED***instanceof***REMOVED***Error***REMOVED***?***REMOVED***error.stack***REMOVED***:***REMOVED***undefined,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***message:***REMOVED***"Failed***REMOVED***to***REMOVED***execute***REMOVED***workflow***REMOVED***step",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***timestamp:***REMOVED***new***REMOVED***Date().toISOString(),
***REMOVED******REMOVED******REMOVED******REMOVED***});
***REMOVED******REMOVED******REMOVED******REMOVED***return***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***success:***REMOVED***false,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***error:***REMOVED***error***REMOVED***instanceof***REMOVED***Error***REMOVED***?***REMOVED***error.message***REMOVED***:***REMOVED***"Unknown***REMOVED***error",
***REMOVED******REMOVED******REMOVED******REMOVED***};
***REMOVED******REMOVED***}
}

/**
***REMOVED*******REMOVED***Update***REMOVED***workflow***REMOVED***status
***REMOVED*******REMOVED***@param***REMOVED***workflowId***REMOVED***-***REMOVED***The***REMOVED***workflow***REMOVED***ID***REMOVED***to***REMOVED***update
***REMOVED*******REMOVED***@param***REMOVED***status***REMOVED***-***REMOVED***The***REMOVED***new***REMOVED***status
***REMOVED*******REMOVED***@param***REMOVED***serviceClient***REMOVED***-***REMOVED***Supabase***REMOVED***service***REMOVED***role***REMOVED***client***REMOVED***for***REMOVED***database***REMOVED***mutations
***REMOVED*******REMOVED***@param***REMOVED***updates***REMOVED***-***REMOVED***Optional***REMOVED***updates***REMOVED***to***REMOVED***steps,***REMOVED***results,***REMOVED***or***REMOVED***error
***REMOVED****/
export***REMOVED***async***REMOVED***function***REMOVED***updateWorkflowStatus(
***REMOVED******REMOVED***workflowId:***REMOVED***string,
***REMOVED******REMOVED***status:***REMOVED***"planning"***REMOVED***|***REMOVED***"executing"***REMOVED***|***REMOVED***"completed"***REMOVED***|***REMOVED***"failed"***REMOVED***|***REMOVED***"cancelled",
***REMOVED******REMOVED***serviceClient:***REMOVED***SupabaseClient<Database>,
***REMOVED******REMOVED***updates:***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***steps?:***REMOVED***WorkflowStep[];
***REMOVED******REMOVED******REMOVED******REMOVED***results?:***REMOVED***any[];
***REMOVED******REMOVED******REMOVED******REMOVED***error?:***REMOVED***string;
***REMOVED******REMOVED***}***REMOVED***=***REMOVED***{}
):***REMOVED***Promise<void>***REMOVED***{
***REMOVED******REMOVED***try***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***updateData:***REMOVED***any***REMOVED***=***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***status,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***updated_at:***REMOVED***new***REMOVED***Date().toISOString(),
***REMOVED******REMOVED******REMOVED******REMOVED***};

***REMOVED******REMOVED******REMOVED******REMOVED***if***REMOVED***(updates.steps)***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***updateData.steps***REMOVED***=***REMOVED***updates.steps;
***REMOVED******REMOVED******REMOVED******REMOVED***}

***REMOVED******REMOVED******REMOVED******REMOVED***if***REMOVED***(updates.results)***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***updateData.results***REMOVED***=***REMOVED***updates.results;
***REMOVED******REMOVED******REMOVED******REMOVED***}

***REMOVED******REMOVED******REMOVED******REMOVED***if***REMOVED***(updates.error)***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***updateData.error***REMOVED***=***REMOVED***updates.error;
***REMOVED******REMOVED******REMOVED******REMOVED***}

***REMOVED******REMOVED******REMOVED******REMOVED***if***REMOVED***(status***REMOVED***===***REMOVED***"completed"***REMOVED***||***REMOVED***status***REMOVED***===***REMOVED***"failed"***REMOVED***||***REMOVED***status***REMOVED***===***REMOVED***"cancelled")***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***updateData.end_time***REMOVED***=***REMOVED***new***REMOVED***Date().toISOString();
***REMOVED******REMOVED******REMOVED******REMOVED***}

***REMOVED******REMOVED******REMOVED******REMOVED***//***REMOVED***Use***REMOVED***service***REMOVED***role***REMOVED***client***REMOVED***for***REMOVED***database***REMOVED***update***REMOVED***operations
***REMOVED******REMOVED******REMOVED******REMOVED***await***REMOVED***updateWorkflow(workflowId,***REMOVED***updateData,***REMOVED***serviceClient);

***REMOVED******REMOVED******REMOVED******REMOVED***console.log(`[Workflow***REMOVED***Service]***REMOVED***Workflow***REMOVED***status***REMOVED***updated`,***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***operation:***REMOVED***"updateWorkflowStatus",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***workflowId,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***status,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***hasSteps:***REMOVED***!!updates.steps,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***hasResults:***REMOVED***!!updates.results,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***hasError:***REMOVED***!!updates.error,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***stepCount:***REMOVED***updates.steps?.length,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***resultCount:***REMOVED***updates.results?.length,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***timestamp:***REMOVED***new***REMOVED***Date().toISOString(),
***REMOVED******REMOVED******REMOVED******REMOVED***});
***REMOVED******REMOVED***}***REMOVED***catch***REMOVED***(error)***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***console.error(`[Workflow***REMOVED***Service]***REMOVED***Failed***REMOVED***to***REMOVED***update***REMOVED***workflow***REMOVED***status`,***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***operation:***REMOVED***"updateWorkflowStatus",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***workflowId,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***status,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***error:***REMOVED***error***REMOVED***instanceof***REMOVED***Error***REMOVED***?***REMOVED***error.message***REMOVED***:***REMOVED***"Unknown***REMOVED***error",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***errorStack:***REMOVED***error***REMOVED***instanceof***REMOVED***Error***REMOVED***?***REMOVED***error.stack***REMOVED***:***REMOVED***undefined,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***message:***REMOVED***"Database***REMOVED***update***REMOVED***operation***REMOVED***failed",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***timestamp:***REMOVED***new***REMOVED***Date().toISOString(),
***REMOVED******REMOVED******REMOVED******REMOVED***});
***REMOVED******REMOVED******REMOVED******REMOVED***throw***REMOVED***error;
***REMOVED******REMOVED***}
}

/**
***REMOVED*******REMOVED***Cancel***REMOVED***a***REMOVED***running***REMOVED***workflow
***REMOVED*******REMOVED***@param***REMOVED***workflowId***REMOVED***-***REMOVED***The***REMOVED***workflow***REMOVED***ID***REMOVED***to***REMOVED***cancel
***REMOVED*******REMOVED***@param***REMOVED***serviceClient***REMOVED***-***REMOVED***Supabase***REMOVED***service***REMOVED***role***REMOVED***client***REMOVED***for***REMOVED***database***REMOVED***mutations
***REMOVED****/
export***REMOVED***async***REMOVED***function***REMOVED***cancelWorkflow(
***REMOVED******REMOVED***workflowId:***REMOVED***string,
***REMOVED******REMOVED***serviceClient:***REMOVED***SupabaseClient<Database>
):***REMOVED***Promise<void>***REMOVED***{
***REMOVED******REMOVED***try***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***await***REMOVED***updateWorkflowStatus(workflowId,***REMOVED***"cancelled",***REMOVED***serviceClient);
***REMOVED******REMOVED******REMOVED******REMOVED***
***REMOVED******REMOVED******REMOVED******REMOVED***console.log(`[Workflow***REMOVED***Service]***REMOVED***Workflow***REMOVED***cancelled`,***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***operation:***REMOVED***"cancelWorkflow",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***workflowId,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***timestamp:***REMOVED***new***REMOVED***Date().toISOString(),
***REMOVED******REMOVED******REMOVED******REMOVED***});
***REMOVED******REMOVED***}***REMOVED***catch***REMOVED***(error)***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***console.error(`[Workflow***REMOVED***Service]***REMOVED***Failed***REMOVED***to***REMOVED***cancel***REMOVED***workflow`,***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***operation:***REMOVED***"cancelWorkflow",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***workflowId,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***error:***REMOVED***error***REMOVED***instanceof***REMOVED***Error***REMOVED***?***REMOVED***error.message***REMOVED***:***REMOVED***"Unknown***REMOVED***error",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***errorStack:***REMOVED***error***REMOVED***instanceof***REMOVED***Error***REMOVED***?***REMOVED***error.stack***REMOVED***:***REMOVED***undefined,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***message:***REMOVED***"Workflow***REMOVED***cancellation***REMOVED***failed",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***timestamp:***REMOVED***new***REMOVED***Date().toISOString(),
***REMOVED******REMOVED******REMOVED******REMOVED***});
***REMOVED******REMOVED******REMOVED******REMOVED***throw***REMOVED***error;
***REMOVED******REMOVED***}
}

/**
***REMOVED*******REMOVED***Add***REMOVED***workflow***REMOVED***to***REMOVED***history
***REMOVED*******REMOVED***@param***REMOVED***userId***REMOVED***-***REMOVED***The***REMOVED***user***REMOVED***ID
***REMOVED*******REMOVED***@param***REMOVED***workflowId***REMOVED***-***REMOVED***The***REMOVED***workflow***REMOVED***ID
***REMOVED*******REMOVED***@param***REMOVED***command***REMOVED***-***REMOVED***The***REMOVED***workflow***REMOVED***command
***REMOVED*******REMOVED***@param***REMOVED***status***REMOVED***-***REMOVED***The***REMOVED***workflow***REMOVED***status
***REMOVED*******REMOVED***@param***REMOVED***serviceClient***REMOVED***-***REMOVED***Supabase***REMOVED***service***REMOVED***role***REMOVED***client***REMOVED***for***REMOVED***database***REMOVED***mutations
***REMOVED****/
export***REMOVED***async***REMOVED***function***REMOVED***recordWorkflowHistory(
***REMOVED******REMOVED***userId:***REMOVED***string,
***REMOVED******REMOVED***workflowId:***REMOVED***string,
***REMOVED******REMOVED***command:***REMOVED***string,
***REMOVED******REMOVED***status:***REMOVED***string,
***REMOVED******REMOVED***serviceClient:***REMOVED***SupabaseClient<Database>
):***REMOVED***Promise<void>***REMOVED***{
***REMOVED******REMOVED***try***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***//***REMOVED***Use***REMOVED***service***REMOVED***role***REMOVED***client***REMOVED***for***REMOVED***history***REMOVED***insert***REMOVED***operations
***REMOVED******REMOVED******REMOVED******REMOVED***await***REMOVED***addWorkflowHistory({
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***user_id:***REMOVED***userId,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***workflow_id:***REMOVED***workflowId,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***command,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***status,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***executed_at:***REMOVED***new***REMOVED***Date().toISOString(),
***REMOVED******REMOVED******REMOVED******REMOVED***},***REMOVED***serviceClient);

***REMOVED******REMOVED******REMOVED******REMOVED***console.log(`[Workflow***REMOVED***Service]***REMOVED***Workflow***REMOVED***history***REMOVED***recorded`,***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***operation:***REMOVED***"recordWorkflowHistory",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***userId,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***workflowId,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***status,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***command:***REMOVED***command.substring(0,***REMOVED***100),
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***timestamp:***REMOVED***new***REMOVED***Date().toISOString(),
***REMOVED******REMOVED******REMOVED******REMOVED***});
***REMOVED******REMOVED***}***REMOVED***catch***REMOVED***(error)***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***console.error(`[Workflow***REMOVED***Service]***REMOVED***Failed***REMOVED***to***REMOVED***record***REMOVED***workflow***REMOVED***history`,***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***operation:***REMOVED***"recordWorkflowHistory",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***userId,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***workflowId,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***status,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***error:***REMOVED***error***REMOVED***instanceof***REMOVED***Error***REMOVED***?***REMOVED***error.message***REMOVED***:***REMOVED***"Unknown***REMOVED***error",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***errorStack:***REMOVED***error***REMOVED***instanceof***REMOVED***Error***REMOVED***?***REMOVED***error.stack***REMOVED***:***REMOVED***undefined,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***message:***REMOVED***"History***REMOVED***recording***REMOVED***failed***REMOVED***but***REMOVED***workflow***REMOVED***continues",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***timestamp:***REMOVED***new***REMOVED***Date().toISOString(),
***REMOVED******REMOVED******REMOVED******REMOVED***});
***REMOVED******REMOVED******REMOVED******REMOVED***//***REMOVED***Don't***REMOVED***throw***REMOVED***-***REMOVED***history***REMOVED***recording***REMOVED***shouldn't***REMOVED***fail***REMOVED***the***REMOVED***workflow
***REMOVED******REMOVED***}
}
