import{createWorkflow,updateWorkflow,addWorkflowHistory}from"@/lib/supabase/queries";
import{generateWorkflowPlan}from"@/lib/llm/client";
importtype{WorkflowStep}from"@/types";
importtype{SupabaseClient}from"@supabase/supabase-js";
importtype{Database}from"@/lib/supabase/database.types";

exportinterfaceWorkflowExecutionResult{
workflowId:string;
status:"planning"|"executing"|"completed"|"failed"|"cancelled";
steps:WorkflowStep[];
results:any[];
error?:string;
}

/**
*Createandplananewworkflow
*@paramuserId-Theauthenticateduser'sID
*@paramcommand-Theuser'sworkflowcommand
*@paramserviceClient-Supabaseserviceroleclientfordatabasemutations
*/
exportasyncfunctioncreateAndPlanWorkflow(
userId:string,
command:string,
serviceClient:SupabaseClient<Database>
):Promise<{workflowId:string;steps:WorkflowStep[]}>{
try{
//GenerateworkflowplanusingLLM
constplan=awaitgenerateWorkflowPlan(command);

//ConvertplanstepstoWorkflowStepformat
conststeps:WorkflowStep[]=plan.steps.map((step,index)=>({
id:step.id,
agentName:step.agentName,
action:step.action,
description:step.description,
status:"pending"asconst,
order:index,
}));

//Createworkflowindatabaseusingserviceroleclient
constworkflow=awaitcreateWorkflow({
user_id:userId,
command,
status:"planning",
steps:stepsasany,
results:[],
start_time:newDate().toISOString(),
},serviceClient);

console.log(`[WorkflowService]Workflowcreatedsuccessfully`,{
operation:"createAndPlanWorkflow",
userId,
workflowId:workflow.id,
stepCount:steps.length,
command:command.substring(0,100),
timestamp:newDate().toISOString(),
});

return{
workflowId:workflow.id,
steps,
};
}catch(error){
console.error(`[WorkflowService]Failedtocreateandplanworkflow`,{
operation:"createAndPlanWorkflow",
userId,
error:errorinstanceofError?error.message:"Unknownerror",
errorStack:errorinstanceofError?error.stack:undefined,
command:command.substring(0,100),
commandLength:command.length,
message:"Workflowcreationfailedduringplanningordatabaseinsertion",
timestamp:newDate().toISOString(),
});
throwerror;
}
}

/**
*Executeaworkflowstep
*/
exportasyncfunctionexecuteWorkflowStep(
workflowId:string,
stepId:string,
accessToken:string
):Promise<{success:boolean;output?:any;error?:string}>{
try{
//Thisiswhereyouwouldcalltheappropriateagent
//Fornow,we'llsimulateexecution

//TODO:Implementactualagentexecution
//-Getstepdetails
//-Callappropriateagent(EmailAgent,DriveAgent,etc.)
//-PassGoogleOAuthaccesstoken
//-Returnresults

console.log(`[WorkflowService]Workflowstepexecutedsuccessfully`,{
operation:"executeWorkflowStep",
workflowId,
stepId,
timestamp:newDate().toISOString(),
});

return{
success:true,
output:{
message:"Stepexecutedsuccessfully",
timestamp:newDate().toISOString(),
},
};
}catch(error){
console.error(`[WorkflowService]Workflowstepexecutionfailed`,{
operation:"executeWorkflowStep",
workflowId,
stepId,
error:errorinstanceofError?error.message:"Unknownerror",
errorStack:errorinstanceofError?error.stack:undefined,
message:"Failedtoexecuteworkflowstep",
timestamp:newDate().toISOString(),
});
return{
success:false,
error:errorinstanceofError?error.message:"Unknownerror",
};
}
}

/**
*Updateworkflowstatus
*@paramworkflowId-TheworkflowIDtoupdate
*@paramstatus-Thenewstatus
*@paramserviceClient-Supabaseserviceroleclientfordatabasemutations
*@paramupdates-Optionalupdatestosteps,results,orerror
*/
exportasyncfunctionupdateWorkflowStatus(
workflowId:string,
status:"planning"|"executing"|"completed"|"failed"|"cancelled",
serviceClient:SupabaseClient<Database>,
updates:{
steps?:WorkflowStep[];
results?:any[];
error?:string;
}={}
):Promise<void>{
try{
constupdateData:any={
status,
updated_at:newDate().toISOString(),
};

if(updates.steps){
updateData.steps=updates.steps;
}

if(updates.results){
updateData.results=updates.results;
}

if(updates.error){
updateData.error=updates.error;
}

if(status==="completed"||status==="failed"||status==="cancelled"){
updateData.end_time=newDate().toISOString();
}

//Useserviceroleclientfordatabaseupdateoperations
awaitupdateWorkflow(workflowId,updateData,serviceClient);

console.log(`[WorkflowService]Workflowstatusupdated`,{
operation:"updateWorkflowStatus",
workflowId,
status,
hasSteps:!!updates.steps,
hasResults:!!updates.results,
hasError:!!updates.error,
stepCount:updates.steps?.length,
resultCount:updates.results?.length,
timestamp:newDate().toISOString(),
});
}catch(error){
console.error(`[WorkflowService]Failedtoupdateworkflowstatus`,{
operation:"updateWorkflowStatus",
workflowId,
status,
error:errorinstanceofError?error.message:"Unknownerror",
errorStack:errorinstanceofError?error.stack:undefined,
message:"Databaseupdateoperationfailed",
timestamp:newDate().toISOString(),
});
throwerror;
}
}

/**
*Cancelarunningworkflow
*@paramworkflowId-TheworkflowIDtocancel
*@paramserviceClient-Supabaseserviceroleclientfordatabasemutations
*/
exportasyncfunctioncancelWorkflow(
workflowId:string,
serviceClient:SupabaseClient<Database>
):Promise<void>{
try{
awaitupdateWorkflowStatus(workflowId,"cancelled",serviceClient);

console.log(`[WorkflowService]Workflowcancelled`,{
operation:"cancelWorkflow",
workflowId,
timestamp:newDate().toISOString(),
});
}catch(error){
console.error(`[WorkflowService]Failedtocancelworkflow`,{
operation:"cancelWorkflow",
workflowId,
error:errorinstanceofError?error.message:"Unknownerror",
errorStack:errorinstanceofError?error.stack:undefined,
message:"Workflowcancellationfailed",
timestamp:newDate().toISOString(),
});
throwerror;
}
}

/**
*Addworkflowtohistory
*@paramuserId-TheuserID
*@paramworkflowId-TheworkflowID
*@paramcommand-Theworkflowcommand
*@paramstatus-Theworkflowstatus
*@paramserviceClient-Supabaseserviceroleclientfordatabasemutations
*/
exportasyncfunctionrecordWorkflowHistory(
userId:string,
workflowId:string,
command:string,
status:string,
serviceClient:SupabaseClient<Database>
):Promise<void>{
try{
//Useserviceroleclientforhistoryinsertoperations
awaitaddWorkflowHistory({
user_id:userId,
workflow_id:workflowId,
command,
status,
executed_at:newDate().toISOString(),
},serviceClient);

console.log(`[WorkflowService]Workflowhistoryrecorded`,{
operation:"recordWorkflowHistory",
userId,
workflowId,
status,
command:command.substring(0,100),
timestamp:newDate().toISOString(),
});
}catch(error){
console.error(`[WorkflowService]Failedtorecordworkflowhistory`,{
operation:"recordWorkflowHistory",
userId,
workflowId,
status,
error:errorinstanceofError?error.message:"Unknownerror",
errorStack:errorinstanceofError?error.stack:undefined,
message:"Historyrecordingfailedbutworkflowcontinues",
timestamp:newDate().toISOString(),
});
//Don'tthrow-historyrecordingshouldn'tfailtheworkflow
}
}
