"useclient";

import{usePathname}from"next/navigation";
importLinkfrom"next/link";
import{Home,History,Settings,Zap}from"lucide-react";
import{cn}from"@/lib/utils";
import{Sheet,SheetContent,SheetTrigger}from"@/components/ui/sheet";
import{useState}from"react";
import{Button}from"@/components/ui/button";

constnavItems=[
{
href:"/",
label:"Dashboard",
icon:Home,
},
{
href:"/history",
label:"History",
icon:History,
},
{
href:"/settings",
label:"Settings",
icon:Settings,
},
];

exportfunctionMobileBottomNav(){
constpathname=usePathname();
const[quickActionsOpen,setQuickActionsOpen]=useState(false);

return(
<navclassName="lg:hiddenfixedbottom-0left-0right-0z-50border-tbg-background/95backdrop-blursupports-[backdrop-filter]:bg-background/60">
<divclassName="flexitems-centerjustify-aroundh-16px-2">
{navItems.map((item)=>{
constIcon=item.icon;
constisActive=pathname===item.href;

return(
<Link
key={item.href}
href={item.href}
className={cn(
"flexflex-colitems-centerjustify-centergap-1px-3py-2rounded-lgtransition-colorsmin-w-[64px]",
isActive
?"text-primarybg-primary/10"
:"text-muted-foregroundhover:text-primaryhover:bg-accent"
)}
>
<IconclassName="h-5w-5"/>
<spanclassName="text-xsfont-medium">{item.label}</span>
</Link>
);
})}

{/*QuickActionsSheetTrigger*/}
<Sheetopen={quickActionsOpen}onOpenChange={setQuickActionsOpen}>
<SheetTriggerasChild>
<Button
variant="ghost"
className="flexflex-colitems-centerjustify-centergap-1px-3py-2rounded-lgmin-w-[64px]h-auto"
>
<ZapclassName="h-5w-5"/>
<spanclassName="text-xsfont-medium">Actions</span>
</Button>
</SheetTrigger>
<SheetContentside="bottom"className="h-[80vh]">
<divclassName="py-4">
<h2className="text-lgfont-semiboldmb-4">QuickActions</h2>
<pclassName="text-smtext-muted-foreground">
Quickactionsareavailableondesktop.Usethecommandinputtoenteryour
requestsonmobile.
</p>
</div>
</SheetContent>
</Sheet>
</div>
</nav>
);
}
