"use***REMOVED***client";

import***REMOVED***{***REMOVED***usePathname***REMOVED***}***REMOVED***from***REMOVED***"next/navigation";
import***REMOVED***Link***REMOVED***from***REMOVED***"next/link";
import***REMOVED***{***REMOVED***Home,***REMOVED***History,***REMOVED***Settings,***REMOVED***Zap***REMOVED***}***REMOVED***from***REMOVED***"lucide-react";
import***REMOVED***{***REMOVED***cn***REMOVED***}***REMOVED***from***REMOVED***"@/lib/utils";
import***REMOVED***{***REMOVED***Sheet,***REMOVED***SheetContent,***REMOVED***SheetTrigger***REMOVED***}***REMOVED***from***REMOVED***"@/components/ui/sheet";
import***REMOVED***{***REMOVED***useState***REMOVED***}***REMOVED***from***REMOVED***"react";
import***REMOVED***{***REMOVED***Button***REMOVED***}***REMOVED***from***REMOVED***"@/components/ui/button";

const***REMOVED***navItems***REMOVED***=***REMOVED***[
***REMOVED******REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***href:***REMOVED***"/",
***REMOVED******REMOVED******REMOVED******REMOVED***label:***REMOVED***"Dashboard",
***REMOVED******REMOVED******REMOVED******REMOVED***icon:***REMOVED***Home,
***REMOVED******REMOVED***},
***REMOVED******REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***href:***REMOVED***"/history",
***REMOVED******REMOVED******REMOVED******REMOVED***label:***REMOVED***"History",
***REMOVED******REMOVED******REMOVED******REMOVED***icon:***REMOVED***History,
***REMOVED******REMOVED***},
***REMOVED******REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***href:***REMOVED***"/settings",
***REMOVED******REMOVED******REMOVED******REMOVED***label:***REMOVED***"Settings",
***REMOVED******REMOVED******REMOVED******REMOVED***icon:***REMOVED***Settings,
***REMOVED******REMOVED***},
];

export***REMOVED***function***REMOVED***MobileBottomNav()***REMOVED***{
***REMOVED******REMOVED***const***REMOVED***pathname***REMOVED***=***REMOVED***usePathname();
***REMOVED******REMOVED***const***REMOVED***[quickActionsOpen,***REMOVED***setQuickActionsOpen]***REMOVED***=***REMOVED***useState(false);

***REMOVED******REMOVED***return***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED***<nav***REMOVED***className="lg:hidden***REMOVED***fixed***REMOVED***bottom-0***REMOVED***left-0***REMOVED***right-0***REMOVED***z-50***REMOVED***border-t***REMOVED***bg-background/95***REMOVED***backdrop-blur***REMOVED***supports-[backdrop-filter]:bg-background/60">
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<div***REMOVED***className="flex***REMOVED***items-center***REMOVED***justify-around***REMOVED***h-16***REMOVED***px-2">
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{navItems.map((item)***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***Icon***REMOVED***=***REMOVED***item.icon;
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***isActive***REMOVED***=***REMOVED***pathname***REMOVED***===***REMOVED***item.href;

***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***return***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<Link
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***key={item.href}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***href={item.href}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className={cn(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"flex***REMOVED***flex-col***REMOVED***items-center***REMOVED***justify-center***REMOVED***gap-1***REMOVED***px-3***REMOVED***py-2***REMOVED***rounded-lg***REMOVED***transition-colors***REMOVED***min-w-[64px]",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***isActive
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***?***REMOVED***"text-primary***REMOVED***bg-primary/10"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***:***REMOVED***"text-muted-foreground***REMOVED***hover:text-primary***REMOVED***hover:bg-accent"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***)}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<Icon***REMOVED***className="h-5***REMOVED***w-5"***REMOVED***/>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<span***REMOVED***className="text-xs***REMOVED***font-medium">{item.label}</span>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</Link>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***);
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***})}

***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{/****REMOVED***Quick***REMOVED***Actions***REMOVED***Sheet***REMOVED***Trigger***REMOVED****/}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<Sheet***REMOVED***open={quickActionsOpen}***REMOVED***onOpenChange={setQuickActionsOpen}>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<SheetTrigger***REMOVED***asChild>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<Button
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***variant="ghost"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className="flex***REMOVED***flex-col***REMOVED***items-center***REMOVED***justify-center***REMOVED***gap-1***REMOVED***px-3***REMOVED***py-2***REMOVED***rounded-lg***REMOVED***min-w-[64px]***REMOVED***h-auto"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<Zap***REMOVED***className="h-5***REMOVED***w-5"***REMOVED***/>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<span***REMOVED***className="text-xs***REMOVED***font-medium">Actions</span>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</Button>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</SheetTrigger>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<SheetContent***REMOVED***side="bottom"***REMOVED***className="h-[80vh]">
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<div***REMOVED***className="py-4">
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<h2***REMOVED***className="text-lg***REMOVED***font-semibold***REMOVED***mb-4">Quick***REMOVED***Actions</h2>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<p***REMOVED***className="text-sm***REMOVED***text-muted-foreground">
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***Quick***REMOVED***actions***REMOVED***are***REMOVED***available***REMOVED***on***REMOVED***desktop.***REMOVED***Use***REMOVED***the***REMOVED***command***REMOVED***input***REMOVED***to***REMOVED***enter***REMOVED***your
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***requests***REMOVED***on***REMOVED***mobile.
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</p>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</div>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</SheetContent>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</Sheet>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</div>
***REMOVED******REMOVED******REMOVED******REMOVED***</nav>
***REMOVED******REMOVED***);
}
