"use***REMOVED***client";

import***REMOVED***{***REMOVED***useState,***REMOVED***useEffect,***REMOVED***useRef,***REMOVED***TouchEvent***REMOVED***}***REMOVED***from***REMOVED***"react";
import***REMOVED***{***REMOVED***cn***REMOVED***}***REMOVED***from***REMOVED***"@/lib/utils";
import***REMOVED***{***REMOVED***useReducedMotion***REMOVED***}***REMOVED***from***REMOVED***"@/hooks/useReducedMotion";
import***REMOVED***{***REMOVED***ChevronUp,***REMOVED***ChevronDown***REMOVED***}***REMOVED***from***REMOVED***"lucide-react";

interface***REMOVED***MobileBottomSheetProps***REMOVED***{
***REMOVED******REMOVED***children:***REMOVED***React.ReactNode;
***REMOVED******REMOVED***isOpen?:***REMOVED***boolean;
***REMOVED******REMOVED***onOpenChange?:***REMOVED***(open:***REMOVED***boolean)***REMOVED***=>***REMOVED***void;
***REMOVED******REMOVED***title?:***REMOVED***string;
***REMOVED******REMOVED***className?:***REMOVED***string;
}

type***REMOVED***SheetState***REMOVED***=***REMOVED***"collapsed"***REMOVED***|***REMOVED***"peek"***REMOVED***|***REMOVED***"expanded";

export***REMOVED***function***REMOVED***MobileBottomSheet({
***REMOVED******REMOVED***children,
***REMOVED******REMOVED***isOpen***REMOVED***=***REMOVED***false,
***REMOVED******REMOVED***onOpenChange,
***REMOVED******REMOVED***title***REMOVED***=***REMOVED***"Execution***REMOVED***Progress",
***REMOVED******REMOVED***className,
}:***REMOVED***MobileBottomSheetProps)***REMOVED***{
***REMOVED******REMOVED***const***REMOVED***[sheetState,***REMOVED***setSheetState]***REMOVED***=***REMOVED***useState<SheetState>(
***REMOVED******REMOVED******REMOVED******REMOVED***isOpen***REMOVED***?***REMOVED***"peek"***REMOVED***:***REMOVED***"collapsed"
***REMOVED******REMOVED***);
***REMOVED******REMOVED***const***REMOVED***[touchStart,***REMOVED***setTouchStart]***REMOVED***=***REMOVED***useState<number***REMOVED***|***REMOVED***null>(null);
***REMOVED******REMOVED***const***REMOVED***[touchEnd,***REMOVED***setTouchEnd]***REMOVED***=***REMOVED***useState<number***REMOVED***|***REMOVED***null>(null);
***REMOVED******REMOVED***const***REMOVED***sheetRef***REMOVED***=***REMOVED***useRef<HTMLDivElement>(null);
***REMOVED******REMOVED***const***REMOVED***prefersReducedMotion***REMOVED***=***REMOVED***useReducedMotion();

***REMOVED******REMOVED***//***REMOVED***Minimum***REMOVED***swipe***REMOVED***distance***REMOVED***(in***REMOVED***px)***REMOVED***to***REMOVED***trigger***REMOVED***state***REMOVED***change
***REMOVED******REMOVED***const***REMOVED***minSwipeDistance***REMOVED***=***REMOVED***50;
***REMOVED******REMOVED***
***REMOVED******REMOVED***//***REMOVED***Animation***REMOVED***duration***REMOVED***based***REMOVED***on***REMOVED***motion***REMOVED***preference
***REMOVED******REMOVED***const***REMOVED***transitionDuration***REMOVED***=***REMOVED***prefersReducedMotion***REMOVED***?***REMOVED***"0.01ms"***REMOVED***:***REMOVED***"300ms";

***REMOVED******REMOVED***useEffect(()***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***if***REMOVED***(isOpen***REMOVED***&&***REMOVED***sheetState***REMOVED***===***REMOVED***"collapsed")***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***setSheetState("peek");
***REMOVED******REMOVED******REMOVED******REMOVED***}***REMOVED***else***REMOVED***if***REMOVED***(!isOpen***REMOVED***&&***REMOVED***sheetState***REMOVED***!==***REMOVED***"collapsed")***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***setSheetState("collapsed");
***REMOVED******REMOVED******REMOVED******REMOVED***}
***REMOVED******REMOVED***},***REMOVED***[isOpen,***REMOVED***sheetState]);

***REMOVED******REMOVED***const***REMOVED***handleTouchStart***REMOVED***=***REMOVED***(e:***REMOVED***TouchEvent)***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***setTouchEnd(null);
***REMOVED******REMOVED******REMOVED******REMOVED***setTouchStart(e.targetTouches[0].clientY);
***REMOVED******REMOVED***};

***REMOVED******REMOVED***const***REMOVED***handleTouchMove***REMOVED***=***REMOVED***(e:***REMOVED***TouchEvent)***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***setTouchEnd(e.targetTouches[0].clientY);
***REMOVED******REMOVED***};

***REMOVED******REMOVED***const***REMOVED***handleTouchEnd***REMOVED***=***REMOVED***()***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***if***REMOVED***(!touchStart***REMOVED***||***REMOVED***!touchEnd)***REMOVED***return;

***REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***distance***REMOVED***=***REMOVED***touchStart***REMOVED***-***REMOVED***touchEnd;
***REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***isSwipeUp***REMOVED***=***REMOVED***distance***REMOVED***>***REMOVED***minSwipeDistance;
***REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***isSwipeDown***REMOVED***=***REMOVED***distance***REMOVED***<***REMOVED***-minSwipeDistance;

***REMOVED******REMOVED******REMOVED******REMOVED***if***REMOVED***(isSwipeUp)***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***//***REMOVED***Swipe***REMOVED***up
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***if***REMOVED***(sheetState***REMOVED***===***REMOVED***"collapsed")***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***setSheetState("peek");
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***onOpenChange?.(true);
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***}***REMOVED***else***REMOVED***if***REMOVED***(sheetState***REMOVED***===***REMOVED***"peek")***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***setSheetState("expanded");
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***}
***REMOVED******REMOVED******REMOVED******REMOVED***}***REMOVED***else***REMOVED***if***REMOVED***(isSwipeDown)***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***//***REMOVED***Swipe***REMOVED***down
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***if***REMOVED***(sheetState***REMOVED***===***REMOVED***"expanded")***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***setSheetState("peek");
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***}***REMOVED***else***REMOVED***if***REMOVED***(sheetState***REMOVED***===***REMOVED***"peek")***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***setSheetState("collapsed");
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***onOpenChange?.(false);
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***}
***REMOVED******REMOVED******REMOVED******REMOVED***}

***REMOVED******REMOVED******REMOVED******REMOVED***setTouchStart(null);
***REMOVED******REMOVED******REMOVED******REMOVED***setTouchEnd(null);
***REMOVED******REMOVED***};

***REMOVED******REMOVED***const***REMOVED***handleToggle***REMOVED***=***REMOVED***()***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***if***REMOVED***(sheetState***REMOVED***===***REMOVED***"collapsed")***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***setSheetState("peek");
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***onOpenChange?.(true);
***REMOVED******REMOVED******REMOVED******REMOVED***}***REMOVED***else***REMOVED***if***REMOVED***(sheetState***REMOVED***===***REMOVED***"peek")***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***setSheetState("expanded");
***REMOVED******REMOVED******REMOVED******REMOVED***}***REMOVED***else***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***setSheetState("peek");
***REMOVED******REMOVED******REMOVED******REMOVED***}
***REMOVED******REMOVED***};

***REMOVED******REMOVED***const***REMOVED***handleCollapse***REMOVED***=***REMOVED***()***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***setSheetState("collapsed");
***REMOVED******REMOVED******REMOVED******REMOVED***onOpenChange?.(false);
***REMOVED******REMOVED***};

***REMOVED******REMOVED***//***REMOVED***Calculate***REMOVED***height***REMOVED***based***REMOVED***on***REMOVED***state
***REMOVED******REMOVED***const***REMOVED***getHeight***REMOVED***=***REMOVED***()***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***switch***REMOVED***(sheetState)***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***case***REMOVED***"collapsed":
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***return***REMOVED***"0px";
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***case***REMOVED***"peek":
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***return***REMOVED***"30vh";***REMOVED***//***REMOVED***Show***REMOVED***partial***REMOVED***content
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***case***REMOVED***"expanded":
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***return***REMOVED***"85vh";***REMOVED***//***REMOVED***Almost***REMOVED***full***REMOVED***screen
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***default:
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***return***REMOVED***"0px";
***REMOVED******REMOVED******REMOVED******REMOVED***}
***REMOVED******REMOVED***};

***REMOVED******REMOVED***//***REMOVED***Only***REMOVED***show***REMOVED***on***REMOVED***mobile***REMOVED***(<***REMOVED***768px)
***REMOVED******REMOVED***return***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED***<div
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***ref={sheetRef}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className={cn(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"fixed***REMOVED***bottom-0***REMOVED***left-0***REMOVED***right-0***REMOVED***z-50***REMOVED***lg:hidden",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"bg-background***REMOVED***border-t***REMOVED***shadow-2xl***REMOVED***rounded-t-2xl",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"ease-out",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***)}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***style={{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***height:***REMOVED***getHeight(),
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***transform:***REMOVED***sheetState***REMOVED***===***REMOVED***"collapsed"***REMOVED***?***REMOVED***"translateY(100%)"***REMOVED***:***REMOVED***"translateY(0)",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***transition:***REMOVED***`all***REMOVED***${transitionDuration}`,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***}}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***role="dialog"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***aria-label={title}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***aria-hidden={sheetState***REMOVED***===***REMOVED***"collapsed"}
***REMOVED******REMOVED******REMOVED******REMOVED***>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{/****REMOVED***Drag***REMOVED***Handle***REMOVED****/}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<div
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className="flex***REMOVED***flex-col***REMOVED***items-center***REMOVED***pt-3***REMOVED***pb-2***REMOVED***cursor-pointer***REMOVED***touch-none"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***onTouchStart={handleTouchStart}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***onTouchMove={handleTouchMove}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***onTouchEnd={handleTouchEnd}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***onClick={handleToggle}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***role="button"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***aria-label={
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***sheetState***REMOVED***===***REMOVED***"expanded"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***?***REMOVED***"Collapse***REMOVED***sheet"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***:***REMOVED***sheetState***REMOVED***===***REMOVED***"peek"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***?***REMOVED***"Expand***REMOVED***sheet"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***:***REMOVED***"Open***REMOVED***sheet"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{/****REMOVED***Visual***REMOVED***drag***REMOVED***indicator***REMOVED****/}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<div***REMOVED***className="w-12***REMOVED***h-1.5***REMOVED***bg-muted-foreground/30***REMOVED***rounded-full***REMOVED***mb-2"***REMOVED***/>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{/****REMOVED***Title***REMOVED***and***REMOVED***toggle***REMOVED***button***REMOVED****/}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<div***REMOVED***className="flex***REMOVED***items-center***REMOVED***justify-between***REMOVED***w-full***REMOVED***px-4***REMOVED***pb-2">
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<h3***REMOVED***className="text-sm***REMOVED***font-semibold">{title}</h3>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<button
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***onClick={(e)***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***e.stopPropagation();
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***if***REMOVED***(sheetState***REMOVED***===***REMOVED***"collapsed")***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***setSheetState("peek");
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***onOpenChange?.(true);
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***}***REMOVED***else***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***handleCollapse();
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***}}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className="p-1***REMOVED***rounded-md***REMOVED***hover:bg-accent***REMOVED***transition-colors"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***aria-label={sheetState***REMOVED***===***REMOVED***"collapsed"***REMOVED***?***REMOVED***"Open***REMOVED***sheet"***REMOVED***:***REMOVED***"Close***REMOVED***sheet"}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{sheetState***REMOVED***===***REMOVED***"collapsed"***REMOVED***?***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<ChevronUp***REMOVED***className="h-5***REMOVED***w-5"***REMOVED***/>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***)***REMOVED***:***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<ChevronDown***REMOVED***className="h-5***REMOVED***w-5"***REMOVED***/>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***)}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</button>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</div>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</div>

***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{/****REMOVED***Content***REMOVED****/}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<div
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className={cn(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"overflow-y-auto***REMOVED***px-4***REMOVED***pb-4",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***sheetState***REMOVED***===***REMOVED***"peek"***REMOVED***?***REMOVED***"h-[calc(30vh-60px)]"***REMOVED***:***REMOVED***"h-[calc(85vh-60px)]"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***)}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***style={{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***transition:***REMOVED***`height***REMOVED***${transitionDuration}`,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***}}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{children}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</div>

***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{/****REMOVED***Backdrop***REMOVED***for***REMOVED***expanded***REMOVED***state***REMOVED****/}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{sheetState***REMOVED***===***REMOVED***"expanded"***REMOVED***&&***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<div
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className="fixed***REMOVED***inset-0***REMOVED***bg-black/20***REMOVED***-z-10"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***onClick={()***REMOVED***=>***REMOVED***setSheetState("peek")}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***aria-hidden="true"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***/>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***)}
***REMOVED******REMOVED******REMOVED******REMOVED***</div>
***REMOVED******REMOVED***);
}
