"useclient";

import{useState,useEffect}from"react";
import{Button}from"@/components/ui/button";
import{
Mail,
FileText,
Calendar,
BarChart3,
Star,
Clock,
ChevronLeft,
ChevronRight,
Search,
}from"lucide-react";
importtype{QuickAction}from"@/types";
import{QuickActionsStorage}from"@/lib/quickActions";
import{QuickActionParameterModal}from"./QuickActionParameterModal";

interfaceQuickActionsSidebarProps{
onActionSelect:(template:string)=>void;
isCollapsed?:boolean;
onToggleCollapse?:()=>void;
}

consticonMap={
Mail,
FileText,
Calendar,
BarChart3,
Star,
Clock,
};

exportfunctionQuickActionsSidebar({
onActionSelect,
isCollapsed=false,
onToggleCollapse,
}:QuickActionsSidebarProps){
const[actions,setActions]=useState<QuickAction[]>([]);
const[searchQuery,setSearchQuery]=useState("");
const[selectedAction,setSelectedAction]=useState<QuickAction|null>(null);
const[isParameterModalOpen,setIsParameterModalOpen]=useState(false);

//Loadactionsfromstorageonmount
useEffect(()=>{
setActions(QuickActionsStorage.getQuickActions());
},[]);

//Filteractionsbasedonsearch
constfilteredActions=searchQuery
?QuickActionsStorage.searchActions(searchQuery)
:actions;

//Getfavorites(fromfilteredactions)
constfavorites=filteredActions.filter((action)=>action.isFavorite);

//Getrecentactions(top5byusagecount)
constrecentActions=QuickActionsStorage.getRecentActions(5).filter((action)=>
filteredActions.some((fa)=>fa.id===action.id)
);

//Groupbycategory
constactionsByCategory=filteredActions.reduce(
(acc,action)=>{
if(!acc[action.category]){
acc[action.category]=[];
}
acc[action.category].push(action);
returnacc;
},
{}asRecord<string,QuickAction[]>
);

consthandleActionClick=(action:QuickAction)=>{
//Checkifactionrequiresparameters
if(action.parameters&&action.parameters.length>0){
setSelectedAction(action);
setIsParameterModalOpen(true);
return;
}

//Incrementusagecount
QuickActionsStorage.incrementUsage(action.id);

//Updatelocalstate
setActions(QuickActionsStorage.getQuickActions());

//Triggercallback
onActionSelect(action.template);
};

consthandleParameterSubmit=(filledTemplate:string)=>{
if(selectedAction){
//Incrementusagecount
QuickActionsStorage.incrementUsage(selectedAction.id);

//Updatelocalstate
setActions(QuickActionsStorage.getQuickActions());

//Triggercallbackwithfilledtemplate
onActionSelect(filledTemplate);
}
};

consthandleToggleFavorite=(actionId:string,event:React.MouseEvent)=>{
//Preventtriggeringtheactionclick
event.stopPropagation();

//Togglefavoriteinstorage
QuickActionsStorage.toggleFavorite(actionId);

//Updatelocalstate
setActions(QuickActionsStorage.getQuickActions());
};

if(isCollapsed){
return(
<asideclassName="hiddenlg:flexw-16flex-colborder-rbg-muted/40"aria-label="Quickactionssidebar">
<divclassName="flexh-16items-centerjustify-centerborder-b">
<Button
variant="ghost"
size="icon"
onClick={onToggleCollapse}
className="h-9w-9"
aria-label="Expandsidebar"
>
<ChevronRightclassName="h-4w-4"aria-hidden="true"/>
</Button>
</div>
<navclassName="flexflex-colitems-centergap-4py-4"aria-label="Quickactions">
<Buttonvariant="ghost"size="icon"aria-label="QuickActions">
<StarclassName="h-5w-5"aria-hidden="true"/>
</Button>
<Buttonvariant="ghost"size="icon"aria-label="Recent">
<ClockclassName="h-5w-5"aria-hidden="true"/>
</Button>
</nav>
</aside>
);
}

return(
<asideclassName="hiddenlg:flexw-80flex-colborder-rbg-muted/40"aria-label="Quickactionssidebar">
{/*Header*/}
<divclassName="flexh-16items-centerjustify-betweenborder-bpx-4">
<h2className="text-lgfont-semibold">QuickActions</h2>
<Button
variant="ghost"
size="icon"
onClick={onToggleCollapse}
className="h-9w-9"
aria-label="Collapsesidebar"
>
<ChevronLeftclassName="h-4w-4"aria-hidden="true"/>
</Button>
</div>

{/*Search*/}
<divclassName="p-4border-b">
<divclassName="relative">
<SearchclassName="absoluteleft-3top-1/2h-4w-4-translate-y-1/2text-muted-foreground"aria-hidden="true"/>
<input
type="search"
placeholder="Searchactions..."
value={searchQuery}
onChange={(e)=>setSearchQuery(e.target.value)}
className="w-fullrounded-mdborderbg-backgroundpl-9pr-3py-2text-smfocus:outline-nonefocus:ring-2focus:ring-ringfocus:ring-offset-2"
aria-label="Searchquickactions"
/>
</div>
</div>

{/*ScrollableContent*/}
<divclassName="flex-1overflow-y-auto">
{/*FavoritesSection*/}
{favorites.length>0&&(
<divclassName="p-4border-b">
<divclassName="flexitems-centergap-2mb-3">
<StarclassName="h-4w-4text-yellow-500fill-yellow-500"/>
<h3className="text-smfont-semibold">Favorites</h3>
</div>
<divclassName="space-y-2">
{favorites.map((action)=>(
<QuickActionButton
key={action.id}
action={action}
onClick={()=>handleActionClick(action)}
onToggleFavorite={handleToggleFavorite}
/>
))}
</div>
</div>
)}

{/*RecentSection*/}
{recentActions.length>0&&(
<divclassName="p-4border-b">
<divclassName="flexitems-centergap-2mb-3">
<ClockclassName="h-4w-4text-muted-foreground"/>
<h3className="text-smfont-semibold">Recent</h3>
</div>
<divclassName="space-y-2">
{recentActions.map((action)=>(
<QuickActionButton
key={action.id}
action={action}
onClick={()=>handleActionClick(action)}
onToggleFavorite={handleToggleFavorite}
/>
))}
</div>
</div>
)}

{/*Categories*/}
{Object.entries(actionsByCategory).map(([category,categoryActions])=>(
<divkey={category}className="p-4border-b">
<h3className="text-smfont-semiboldmb-3capitalize">{category}</h3>
<divclassName="space-y-2">
{categoryActions.map((action)=>(
<QuickActionButton
key={action.id}
action={action}
onClick={()=>handleActionClick(action)}
onToggleFavorite={handleToggleFavorite}
/>
))}
</div>
</div>
))}
</div>

{/*ParameterModal*/}
<QuickActionParameterModal
action={selectedAction}
open={isParameterModalOpen}
onClose={()=>{
setIsParameterModalOpen(false);
setSelectedAction(null);
}}
onSubmit={handleParameterSubmit}
/>
</aside>
);
}

functionQuickActionButton({
action,
onClick,
onToggleFavorite,
}:{
action:QuickAction;
onClick:()=>void;
onToggleFavorite:(actionId:string,event:React.MouseEvent)=>void;
}){
constIcon=iconMap[action.iconaskeyoftypeoficonMap]||FileText;

return(
<button
onClick={onClick}
className="w-fullflexitems-startgap-3rounded-lgborderbg-cardp-3text-lefttransition-colorshover:bg-accenthover:text-accent-foregroundgrouprelativefocus:outline-nonefocus:ring-2focus:ring-ringfocus:ring-offset-2"
aria-label={`${action.title}:${action.description}`}
>
<divclassName="flexh-8w-8shrink-0items-centerjustify-centerrounded-mdbg-primary/10"aria-hidden="true">
<IconclassName="h-4w-4text-primary"/>
</div>
<divclassName="flex-1min-w-0">
<pclassName="text-smfont-mediumleading-nonemb-1">{action.title}</p>
<pclassName="text-xstext-muted-foregroundline-clamp-2">
{action.description}
</p>
</div>
<button
onClick={(e)=>onToggleFavorite(action.id,e)}
className="absolutetop-2right-2p-1rounded-mdopacity-0group-hover:opacity-100group-focus-within:opacity-100transition-opacityhover:bg-accentfocus:opacity-100focus:outline-nonefocus:ring-2focus:ring-ringfocus:ring-offset-2"
aria-label={action.isFavorite?`Remove${action.title}fromfavorites`:`Add${action.title}tofavorites`}
tabIndex={0}
>
<Star
className={`h-4w-4${
action.isFavorite
?"fill-yellow-500text-yellow-500"
:"text-muted-foreground"
}`}
aria-hidden="true"
/>
</button>
</button>
);
}
