"useclient";

import{useState}from"react";
importLinkfrom"next/link";
import{useSupabaseAuth}from"@/contexts/SupabaseAuthContext";
import{Button}from"@/components/ui/button";
import{
DropdownMenu,
DropdownMenuContent,
DropdownMenuItem,
DropdownMenuLabel,
DropdownMenuSeparator,
DropdownMenuTrigger,
}from"@/components/ui/dropdown-menu";
import{Avatar,AvatarFallback}from"@/components/ui/avatar";
import{Sheet,SheetContent,SheetTrigger}from"@/components/ui/sheet";
import{Menu,Home,History,Settings,LogOut,CheckCircle2,XCircle}from"lucide-react";

exportfunctionTopNavigation(){
const{user,googleOAuthStatus,signOut}=useSupabaseAuth();
const[mobileMenuOpen,setMobileMenuOpen]=useState(false);

constisConnected=googleOAuthStatus?.isConnected??false;
constuserEmail=user?.email??"";
constuserInitials=userEmail
.split("@")[0]
.split(".")
.map((n)=>n[0])
.join("")
.toUpperCase()
.slice(0,2);

constnavigationLinks=[
{href:"/dashboard",label:"Dashboard",icon:Home},
{href:"/history",label:"History",icon:History},
{href:"/settings",label:"Settings",icon:Settings},
];

consthandleLogout=async()=>{
try{
awaitsignOut();
}catch(error){
console.error("Logoutfailed:",error);
}
};

return(
<headerclassName="stickytop-0z-50w-fullborder-bbg-background/95backdrop-blursupports-[backdrop-filter]:bg-background/60">
<divclassName="containerflexh-16items-centerjustify-betweenpx-4">
{/*Logo*/}
<divclassName="flexitems-centergap-6">
<Linkhref="/dashboard"className="flexitems-centergap-2">
<divclassName="flexh-8w-8items-centerjustify-centerrounded-lgbg-primarytext-primary-foregroundfont-boldtext-sm"aria-hidden="true">
A
</div>
<spanclassName="hiddenfont-boldsm:inline-block">AURA</span>
</Link>

{/*DesktopNavigation-Usingsemanticnavelement*/}
<navclassName="hiddenmd:flexitems-centergap-6"aria-label="Mainnavigation">
{navigationLinks.map((link)=>(
<Link
key={link.href}
href={link.href}
className="text-smfont-mediumtext-muted-foregroundtransition-colorshover:text-primaryfocus:outline-nonefocus:ring-2focus:ring-ringfocus:ring-offset-2rounded-smpx-2py-1"
>
{link.label}
</Link>
))}
</nav>
</div>

{/*RightSide:OAuthStatus+UserMenu*/}
<divclassName="flexitems-centergap-4">
{/*OAuthConnectionStatus*/}
<divclassName="hiddensm:flexitems-centergap-2text-sm">
{isConnected?(
<>
<CheckCircle2className="h-4w-4text-green-600"/>
<spanclassName="text-muted-foreground">Connected</span>
</>
):(
<>
<XCircleclassName="h-4w-4text-red-600"/>
<spanclassName="text-muted-foreground">Disconnected</span>
</>
)}
</div>

{/*UserProfileDropdown-Desktop*/}
<divclassName="hiddenmd:block">
<DropdownMenu>
<DropdownMenuTriggerasChild>
<Buttonvariant="ghost"className="relativeh-9w-9rounded-full">
<AvatarclassName="h-9w-9">
<AvatarFallback>{userInitials}</AvatarFallback>
</Avatar>
</Button>
</DropdownMenuTrigger>
<DropdownMenuContentclassName="w-56"align="end"forceMount>
<DropdownMenuLabelclassName="font-normal">
<divclassName="flexflex-colspace-y-1">
<pclassName="text-smfont-mediumleading-none">Account</p>
<pclassName="text-xsleading-nonetext-muted-foreground">
{userEmail}
</p>
</div>
</DropdownMenuLabel>
<DropdownMenuSeparator/>
<DropdownMenuItemasChild>
<Linkhref="/dashboard"className="cursor-pointer">
<HomeclassName="mr-2h-4w-4"/>
Dashboard
</Link>
</DropdownMenuItem>
<DropdownMenuItemasChild>
<Linkhref="/history"className="cursor-pointer">
<HistoryclassName="mr-2h-4w-4"/>
History
</Link>
</DropdownMenuItem>
<DropdownMenuItemasChild>
<Linkhref="/settings"className="cursor-pointer">
<SettingsclassName="mr-2h-4w-4"/>
Settings
</Link>
</DropdownMenuItem>
<DropdownMenuSeparator/>
<DropdownMenuItem
className="cursor-pointertext-red-600"
onClick={handleLogout}
>
<LogOutclassName="mr-2h-4w-4"/>
Disconnect
</DropdownMenuItem>
</DropdownMenuContent>
</DropdownMenu>
</div>

{/*MobileHamburgerMenu*/}
<divclassName="md:hidden">
<Sheetopen={mobileMenuOpen}onOpenChange={setMobileMenuOpen}>
<SheetTriggerasChild>
<Buttonvariant="ghost"size="icon">
<MenuclassName="h-5w-5"/>
<spanclassName="sr-only">Togglemenu</span>
</Button>
</SheetTrigger>
<SheetContentside="right"className="w-[300px]sm:w-[400px]">
<divclassName="flexflex-colgap-6py-6">
{/*UserInfo*/}
<divclassName="flexitems-centergap-3pb-4border-b">
<AvatarclassName="h-12w-12">
<AvatarFallback>{userInitials}</AvatarFallback>
</Avatar>
<divclassName="flexflex-col">
<pclassName="text-smfont-medium">Account</p>
<pclassName="text-xstext-muted-foreground">{userEmail}</p>
</div>
</div>

{/*OAuthStatus*/}
<divclassName="flexitems-centergap-2text-smpb-4border-b">
{isConnected?(
<>
<CheckCircle2className="h-4w-4text-green-600"/>
<spanclassName="text-muted-foreground">ConnectedtoGoogle</span>
</>
):(
<>
<XCircleclassName="h-4w-4text-red-600"/>
<spanclassName="text-muted-foreground">NotConnected</span>
</>
)}
</div>

{/*NavigationLinks*/}
<navclassName="flexflex-colgap-2">
{navigationLinks.map((link)=>{
constIcon=link.icon;
return(
<Link
key={link.href}
href={link.href}
onClick={()=>setMobileMenuOpen(false)}
className="flexitems-centergap-3rounded-lgpx-3py-2text-smfont-mediumtransition-colorshover:bg-accent"
>
<IconclassName="h-4w-4"/>
{link.label}
</Link>
);
})}
</nav>

{/*DisconnectButton*/}
<Button
variant="destructive"
className="mt-auto"
onClick={()=>{
handleLogout();
setMobileMenuOpen(false);
}}
>
<LogOutclassName="mr-2h-4w-4"/>
Disconnect
</Button>
</div>
</SheetContent>
</Sheet>
</div>
</div>
</div>
</header>
);
}
