import***REMOVED***{***REMOVED***NextRequest***REMOVED***}***REMOVED***from***REMOVED***"next/server";
import***REMOVED***type***REMOVED***{***REMOVED***SSEEvent,***REMOVED***WorkflowStep***REMOVED***}***REMOVED***from***REMOVED***"@/types";

//***REMOVED***Simulated***REMOVED***workflow***REMOVED***execution
//***REMOVED***In***REMOVED***production,***REMOVED***this***REMOVED***would***REMOVED***connect***REMOVED***to***REMOVED***the***REMOVED***backend***REMOVED***BFF's***REMOVED***SSE***REMOVED***stream
async***REMOVED***function***REMOVED***simulateWorkflowExecution(
***REMOVED******REMOVED***workflowId:***REMOVED***string,
***REMOVED******REMOVED***steps:***REMOVED***WorkflowStep[],
***REMOVED******REMOVED***encoder:***REMOVED***TextEncoder,
***REMOVED******REMOVED***controller:***REMOVED***ReadableStreamDefaultController
)***REMOVED***{
***REMOVED******REMOVED***const***REMOVED***sendEvent***REMOVED***=***REMOVED***(event:***REMOVED***SSEEvent)***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***data***REMOVED***=***REMOVED***`event:***REMOVED***${event.type}\ndata:***REMOVED***${JSON.stringify(event)}\n\n`;
***REMOVED******REMOVED******REMOVED******REMOVED***controller.enqueue(encoder.encode(data));
***REMOVED******REMOVED***};

***REMOVED******REMOVED***//***REMOVED***Simulate***REMOVED***step***REMOVED***execution***REMOVED***with***REMOVED***delays
***REMOVED******REMOVED***for***REMOVED***(let***REMOVED***i***REMOVED***=***REMOVED***0;***REMOVED***i***REMOVED***<***REMOVED***steps.length;***REMOVED***i++)***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***step***REMOVED***=***REMOVED***steps[i];
***REMOVED******REMOVED******REMOVED******REMOVED***
***REMOVED******REMOVED******REMOVED******REMOVED***//***REMOVED***Check***REMOVED***if***REMOVED***workflow***REMOVED***was***REMOVED***cancelled
***REMOVED******REMOVED******REMOVED******REMOVED***//***REMOVED***In***REMOVED***production,***REMOVED***this***REMOVED***would***REMOVED***check***REMOVED***the***REMOVED***database***REMOVED***or***REMOVED***message***REMOVED***queue
***REMOVED******REMOVED******REMOVED******REMOVED***
***REMOVED******REMOVED******REMOVED******REMOVED***//***REMOVED***Step***REMOVED***start
***REMOVED******REMOVED******REMOVED******REMOVED***await***REMOVED***new***REMOVED***Promise((resolve)***REMOVED***=>***REMOVED***setTimeout(resolve,***REMOVED***500));
***REMOVED******REMOVED******REMOVED******REMOVED***sendEvent({
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***type:***REMOVED***"step_start",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***stepId:***REMOVED***step.id,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***data:***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***...step,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***status:***REMOVED***"running",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***startTime:***REMOVED***new***REMOVED***Date(),
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***},
***REMOVED******REMOVED******REMOVED******REMOVED***});

***REMOVED******REMOVED******REMOVED******REMOVED***//***REMOVED***Simulate***REMOVED***step***REMOVED***execution
***REMOVED******REMOVED******REMOVED******REMOVED***await***REMOVED***new***REMOVED***Promise((resolve)***REMOVED***=>***REMOVED***setTimeout(resolve,***REMOVED***2000));

***REMOVED******REMOVED******REMOVED******REMOVED***//***REMOVED***Step***REMOVED***complete
***REMOVED******REMOVED******REMOVED******REMOVED***sendEvent({
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***type:***REMOVED***"step_complete",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***stepId:***REMOVED***step.id,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***data:***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***...step,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***status:***REMOVED***"completed",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***endTime:***REMOVED***new***REMOVED***Date(),
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***output:***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***message:***REMOVED***`${step.agentName}***REMOVED***completed***REMOVED***successfully`,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***result:***REMOVED***`Mock***REMOVED***result***REMOVED***for***REMOVED***${step.action}`,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***},
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***},
***REMOVED******REMOVED******REMOVED******REMOVED***});
***REMOVED******REMOVED***}

***REMOVED******REMOVED***//***REMOVED***Workflow***REMOVED***complete
***REMOVED******REMOVED***await***REMOVED***new***REMOVED***Promise((resolve)***REMOVED***=>***REMOVED***setTimeout(resolve,***REMOVED***500));
***REMOVED******REMOVED***const***REMOVED***completeData***REMOVED***=***REMOVED***JSON.stringify({
***REMOVED******REMOVED******REMOVED******REMOVED***workflowId,
***REMOVED******REMOVED******REMOVED******REMOVED***status:***REMOVED***"completed",
***REMOVED******REMOVED******REMOVED******REMOVED***results:***REMOVED***[
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***id:***REMOVED***`result_${workflowId}_1`,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***type:***REMOVED***"document",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***title:***REMOVED***"Generated***REMOVED***Document",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***preview:***REMOVED***"This***REMOVED***is***REMOVED***a***REMOVED***mock***REMOVED***document***REMOVED***generated***REMOVED***by***REMOVED***the***REMOVED***workflow...",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***url:***REMOVED***"https://docs.google.com/document/d/mock",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***metadata:***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***createdAt:***REMOVED***new***REMOVED***Date().toISOString(),
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***},
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***},
***REMOVED******REMOVED******REMOVED******REMOVED***],
***REMOVED******REMOVED***});
***REMOVED******REMOVED***controller.enqueue(encoder.encode(`event:***REMOVED***workflow_complete\ndata:***REMOVED***${completeData}\n\n`));
}

export***REMOVED***async***REMOVED***function***REMOVED***GET(request:***REMOVED***NextRequest)***REMOVED***{
***REMOVED******REMOVED***const***REMOVED***searchParams***REMOVED***=***REMOVED***request.nextUrl.searchParams;
***REMOVED******REMOVED***const***REMOVED***workflowId***REMOVED***=***REMOVED***searchParams.get("workflowId");

***REMOVED******REMOVED***if***REMOVED***(!workflowId)***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***return***REMOVED***new***REMOVED***Response("Workflow***REMOVED***ID***REMOVED***is***REMOVED***required",***REMOVED***{***REMOVED***status:***REMOVED***400***REMOVED***});
***REMOVED******REMOVED***}

***REMOVED******REMOVED***//***REMOVED***Create***REMOVED***a***REMOVED***readable***REMOVED***stream***REMOVED***for***REMOVED***SSE
***REMOVED******REMOVED***const***REMOVED***encoder***REMOVED***=***REMOVED***new***REMOVED***TextEncoder();
***REMOVED******REMOVED***
***REMOVED******REMOVED***const***REMOVED***stream***REMOVED***=***REMOVED***new***REMOVED***ReadableStream({
***REMOVED******REMOVED******REMOVED******REMOVED***async***REMOVED***start(controller)***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***//***REMOVED***Send***REMOVED***initial***REMOVED***connection***REMOVED***message
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***controller.enqueue(encoder.encode(`:***REMOVED***Connected***REMOVED***to***REMOVED***workflow***REMOVED***${workflowId}\n\n`));

***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***try***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***//***REMOVED***Mock***REMOVED***workflow***REMOVED***steps
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***//***REMOVED***In***REMOVED***production,***REMOVED***this***REMOVED***would***REMOVED***fetch***REMOVED***from***REMOVED***database***REMOVED***or***REMOVED***backend
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***steps:***REMOVED***WorkflowStep[]***REMOVED***=***REMOVED***[
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***id:***REMOVED***`step_${workflowId}_1`,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***agentName:***REMOVED***"Planning***REMOVED***Agent",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***action:***REMOVED***"Analyzing***REMOVED***command***REMOVED***and***REMOVED***creating***REMOVED***execution***REMOVED***plan",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***status:***REMOVED***"pending",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***},
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***id:***REMOVED***`step_${workflowId}_2`,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***agentName:***REMOVED***"Email***REMOVED***Agent",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***action:***REMOVED***"Processing***REMOVED***email-related***REMOVED***tasks",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***status:***REMOVED***"pending",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***},
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***id:***REMOVED***`step_${workflowId}_3`,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***agentName:***REMOVED***"Drive***REMOVED***Agent",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***action:***REMOVED***"Managing***REMOVED***documents***REMOVED***and***REMOVED***files",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***status:***REMOVED***"pending",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***},
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***];

***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***//***REMOVED***Simulate***REMOVED***workflow***REMOVED***execution
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***await***REMOVED***simulateWorkflowExecution(workflowId,***REMOVED***steps,***REMOVED***encoder,***REMOVED***controller);
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***controller.close();
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***}***REMOVED***catch***REMOVED***(error)***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***console.error("Error***REMOVED***in***REMOVED***SSE***REMOVED***stream:",***REMOVED***error);
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***//***REMOVED***Send***REMOVED***error***REMOVED***event
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***errorEvent:***REMOVED***SSEEvent***REMOVED***=***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***type:***REMOVED***"step_error",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***stepId:***REMOVED***"unknown",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***data:***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***id:***REMOVED***"error",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***agentName:***REMOVED***"System",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***action:***REMOVED***"Error***REMOVED***occurred",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***status:***REMOVED***"failed",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***error:***REMOVED***error***REMOVED***instanceof***REMOVED***Error***REMOVED***?***REMOVED***error.message***REMOVED***:***REMOVED***"Unknown***REMOVED***error",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***},
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***};
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***controller.enqueue(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***encoder.encode(`event:***REMOVED***step_error\ndata:***REMOVED***${JSON.stringify(errorEvent)}\n\n`)
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***);
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***controller.close();
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***}
***REMOVED******REMOVED******REMOVED******REMOVED***},
***REMOVED******REMOVED******REMOVED******REMOVED***
***REMOVED******REMOVED******REMOVED******REMOVED***cancel()***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***console.log("SSE***REMOVED***stream***REMOVED***cancelled***REMOVED***by***REMOVED***client");
***REMOVED******REMOVED******REMOVED******REMOVED***},
***REMOVED******REMOVED***});

***REMOVED******REMOVED***//***REMOVED***Return***REMOVED***SSE***REMOVED***response***REMOVED***with***REMOVED***appropriate***REMOVED***headers
***REMOVED******REMOVED***return***REMOVED***new***REMOVED***Response(stream,***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***headers:***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"Content-Type":***REMOVED***"text/event-stream",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"Cache-Control":***REMOVED***"no-cache,***REMOVED***no-transform",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"Connection":***REMOVED***"keep-alive",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"X-Accel-Buffering":***REMOVED***"no",***REMOVED***//***REMOVED***Disable***REMOVED***buffering***REMOVED***in***REMOVED***nginx
***REMOVED******REMOVED******REMOVED******REMOVED***},
***REMOVED******REMOVED***});
}
