importtype{Metadata}from"next";
import{Geist,Geist_Mono}from"next/font/google";
import"./globals.css";
import{SupabaseAuthProvider}from"@/contexts/SupabaseAuthContext";
import{WorkflowProvider}from"@/contexts/WorkflowContext";
import{
ErrorBoundary,
ToastProvider,
SwrProvider,
ServiceWorkerRegistration,
WebVitalsReporter,
}from"@/components/shared";

constgeistSans=Geist({
variable:"--font-geist-sans",
subsets:["latin"],
});

constgeistMono=Geist_Mono({
variable:"--font-geist-mono",
subsets:["latin"],
});

exportconstmetadata:Metadata={
title:"AURA-AgenticUnifiedReasoningAssistant",
description:"AI-poweredworkflowautomationforGoogleWorkspace",
manifest:"/manifest.json",
themeColor:"#000000",
appleWebApp:{
capable:true,
statusBarStyle:"default",
title:"AURA",
},
};

exportdefaultfunctionRootLayout({
children,
}:Readonly<{
children:React.ReactNode;
}>){
return(
<htmllang="en">
<bodyclassName={`${geistSans.variable}${geistMono.variable}antialiased`}>
<ServiceWorkerRegistration/>
<WebVitalsReporter/>
<ErrorBoundary>
<SwrProvider>
<SupabaseAuthProvider>
<ToastProvider>
<WorkflowProvider>{children}</WorkflowProvider>
</ToastProvider>
</SupabaseAuthProvider>
</SwrProvider>
</ErrorBoundary>
</body>
</html>
);
}
