import***REMOVED*******REMOVED***as***REMOVED***React***REMOVED***from***REMOVED***"react"
import***REMOVED***{***REMOVED***Slot***REMOVED***}***REMOVED***from***REMOVED***"@radix-ui/react-slot"
import***REMOVED***{***REMOVED***cva,***REMOVED***type***REMOVED***VariantProps***REMOVED***}***REMOVED***from***REMOVED***"class-variance-authority"

import***REMOVED***{***REMOVED***cn***REMOVED***}***REMOVED***from***REMOVED***"@/lib/utils"

const***REMOVED***buttonVariants***REMOVED***=***REMOVED***cva(
***REMOVED******REMOVED***"inline-flex***REMOVED***items-center***REMOVED***justify-center***REMOVED***gap-2***REMOVED***whitespace-nowrap***REMOVED***rounded-md***REMOVED***text-sm***REMOVED***font-medium***REMOVED***transition-all***REMOVED***disabled:pointer-events-none***REMOVED***disabled:opacity-50***REMOVED***[&_svg]:pointer-events-none***REMOVED***[&_svg:not([class*='size-'])]:size-4***REMOVED***shrink-0***REMOVED***[&_svg]:shrink-0***REMOVED***outline-none***REMOVED***focus-visible:border-ring***REMOVED***focus-visible:ring-ring/50***REMOVED***focus-visible:ring-[3px]***REMOVED***aria-invalid:ring-destructive/20***REMOVED***dark:aria-invalid:ring-destructive/40***REMOVED***aria-invalid:border-destructive",
***REMOVED******REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***variants:***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***variant:***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***default:***REMOVED***"bg-primary***REMOVED***text-primary-foreground***REMOVED***hover:bg-primary/90",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***destructive:
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"bg-destructive***REMOVED***text-white***REMOVED***hover:bg-destructive/90***REMOVED***focus-visible:ring-destructive/20***REMOVED***dark:focus-visible:ring-destructive/40***REMOVED***dark:bg-destructive/60",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***outline:
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"border***REMOVED***bg-background***REMOVED***shadow-xs***REMOVED***hover:bg-accent***REMOVED***hover:text-accent-foreground***REMOVED***dark:bg-input/30***REMOVED***dark:border-input***REMOVED***dark:hover:bg-input/50",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***secondary:
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"bg-secondary***REMOVED***text-secondary-foreground***REMOVED***hover:bg-secondary/80",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***ghost:
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"hover:bg-accent***REMOVED***hover:text-accent-foreground***REMOVED***dark:hover:bg-accent/50",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***link:***REMOVED***"text-primary***REMOVED***underline-offset-4***REMOVED***hover:underline",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***},
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***size:***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***default:***REMOVED***"h-9***REMOVED***px-4***REMOVED***py-2***REMOVED***has-[>svg]:px-3",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***sm:***REMOVED***"h-8***REMOVED***rounded-md***REMOVED***gap-1.5***REMOVED***px-3***REMOVED***has-[>svg]:px-2.5",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***lg:***REMOVED***"h-10***REMOVED***rounded-md***REMOVED***px-6***REMOVED***has-[>svg]:px-4",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***icon:***REMOVED***"size-9",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"icon-sm":***REMOVED***"size-8",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"icon-lg":***REMOVED***"size-10",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***},
***REMOVED******REMOVED******REMOVED******REMOVED***},
***REMOVED******REMOVED******REMOVED******REMOVED***defaultVariants:***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***variant:***REMOVED***"default",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***size:***REMOVED***"default",
***REMOVED******REMOVED******REMOVED******REMOVED***},
***REMOVED******REMOVED***}
)

function***REMOVED***Button({
***REMOVED******REMOVED***className,
***REMOVED******REMOVED***variant,
***REMOVED******REMOVED***size,
***REMOVED******REMOVED***asChild***REMOVED***=***REMOVED***false,
***REMOVED******REMOVED***...props
}:***REMOVED***React.ComponentProps<"button">***REMOVED***&
***REMOVED******REMOVED***VariantProps<typeof***REMOVED***buttonVariants>***REMOVED***&***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***asChild?:***REMOVED***boolean
***REMOVED******REMOVED***})***REMOVED***{
***REMOVED******REMOVED***const***REMOVED***Comp***REMOVED***=***REMOVED***asChild***REMOVED***?***REMOVED***Slot***REMOVED***:***REMOVED***"button"

***REMOVED******REMOVED***return***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED***<Comp
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***data-slot="button"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className={cn(buttonVariants({***REMOVED***variant,***REMOVED***size,***REMOVED***className***REMOVED***}))}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{...props}
***REMOVED******REMOVED******REMOVED******REMOVED***/>
***REMOVED******REMOVED***)
}

export***REMOVED***{***REMOVED***Button,***REMOVED***buttonVariants***REMOVED***}
