"use***REMOVED***client"

import***REMOVED*******REMOVED***as***REMOVED***React***REMOVED***from***REMOVED***"react"
import***REMOVED*******REMOVED***as***REMOVED***DialogPrimitive***REMOVED***from***REMOVED***"@radix-ui/react-dialog"
import***REMOVED***{***REMOVED***XIcon***REMOVED***}***REMOVED***from***REMOVED***"lucide-react"

import***REMOVED***{***REMOVED***cn***REMOVED***}***REMOVED***from***REMOVED***"@/lib/utils"

function***REMOVED***Dialog({
***REMOVED******REMOVED***...props
}:***REMOVED***React.ComponentProps<typeof***REMOVED***DialogPrimitive.Root>)***REMOVED***{
***REMOVED******REMOVED***return***REMOVED***<DialogPrimitive.Root***REMOVED***data-slot="dialog"***REMOVED***{...props}***REMOVED***/>
}

function***REMOVED***DialogTrigger({
***REMOVED******REMOVED***...props
}:***REMOVED***React.ComponentProps<typeof***REMOVED***DialogPrimitive.Trigger>)***REMOVED***{
***REMOVED******REMOVED***return***REMOVED***<DialogPrimitive.Trigger***REMOVED***data-slot="dialog-trigger"***REMOVED***{...props}***REMOVED***/>
}

function***REMOVED***DialogPortal({
***REMOVED******REMOVED***...props
}:***REMOVED***React.ComponentProps<typeof***REMOVED***DialogPrimitive.Portal>)***REMOVED***{
***REMOVED******REMOVED***return***REMOVED***<DialogPrimitive.Portal***REMOVED***data-slot="dialog-portal"***REMOVED***{...props}***REMOVED***/>
}

function***REMOVED***DialogClose({
***REMOVED******REMOVED***...props
}:***REMOVED***React.ComponentProps<typeof***REMOVED***DialogPrimitive.Close>)***REMOVED***{
***REMOVED******REMOVED***return***REMOVED***<DialogPrimitive.Close***REMOVED***data-slot="dialog-close"***REMOVED***{...props}***REMOVED***/>
}

function***REMOVED***DialogOverlay({
***REMOVED******REMOVED***className,
***REMOVED******REMOVED***...props
}:***REMOVED***React.ComponentProps<typeof***REMOVED***DialogPrimitive.Overlay>)***REMOVED***{
***REMOVED******REMOVED***return***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED***<DialogPrimitive.Overlay
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***data-slot="dialog-overlay"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className={cn(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"data-[state=open]:animate-in***REMOVED***data-[state=closed]:animate-out***REMOVED***data-[state=closed]:fade-out-0***REMOVED***data-[state=open]:fade-in-0***REMOVED***fixed***REMOVED***inset-0***REMOVED***z-50***REMOVED***bg-black/50",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***)}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{...props}
***REMOVED******REMOVED******REMOVED******REMOVED***/>
***REMOVED******REMOVED***)
}

function***REMOVED***DialogContent({
***REMOVED******REMOVED***className,
***REMOVED******REMOVED***children,
***REMOVED******REMOVED***showCloseButton***REMOVED***=***REMOVED***true,
***REMOVED******REMOVED***...props
}:***REMOVED***React.ComponentProps<typeof***REMOVED***DialogPrimitive.Content>***REMOVED***&***REMOVED***{
***REMOVED******REMOVED***showCloseButton?:***REMOVED***boolean
})***REMOVED***{
***REMOVED******REMOVED***return***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED***<DialogPortal***REMOVED***data-slot="dialog-portal">
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<DialogOverlay***REMOVED***/>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<DialogPrimitive.Content
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***data-slot="dialog-content"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className={cn(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"bg-background***REMOVED***data-[state=open]:animate-in***REMOVED***data-[state=closed]:animate-out***REMOVED***data-[state=closed]:fade-out-0***REMOVED***data-[state=open]:fade-in-0***REMOVED***data-[state=closed]:zoom-out-95***REMOVED***data-[state=open]:zoom-in-95***REMOVED***fixed***REMOVED***top-[50%]***REMOVED***left-[50%]***REMOVED***z-50***REMOVED***grid***REMOVED***w-full***REMOVED***max-w-[calc(100%-2rem)]***REMOVED***translate-x-[-50%]***REMOVED***translate-y-[-50%]***REMOVED***gap-4***REMOVED***rounded-lg***REMOVED***border***REMOVED***p-6***REMOVED***shadow-lg***REMOVED***duration-200***REMOVED***sm:max-w-lg",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***)}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{...props}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{children}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{showCloseButton***REMOVED***&&***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<DialogPrimitive.Close
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***data-slot="dialog-close"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className="ring-offset-background***REMOVED***focus:ring-ring***REMOVED***data-[state=open]:bg-accent***REMOVED***data-[state=open]:text-muted-foreground***REMOVED***absolute***REMOVED***top-4***REMOVED***right-4***REMOVED***rounded-xs***REMOVED***opacity-70***REMOVED***transition-opacity***REMOVED***hover:opacity-100***REMOVED***focus:ring-2***REMOVED***focus:ring-offset-2***REMOVED***focus:outline-hidden***REMOVED***disabled:pointer-events-none***REMOVED***[&_svg]:pointer-events-none***REMOVED***[&_svg]:shrink-0***REMOVED***[&_svg:not([class*='size-'])]:size-4"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<XIcon***REMOVED***/>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<span***REMOVED***className="sr-only">Close</span>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</DialogPrimitive.Close>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***)}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</DialogPrimitive.Content>
***REMOVED******REMOVED******REMOVED******REMOVED***</DialogPortal>
***REMOVED******REMOVED***)
}

function***REMOVED***DialogHeader({***REMOVED***className,***REMOVED***...props***REMOVED***}:***REMOVED***React.ComponentProps<"div">)***REMOVED***{
***REMOVED******REMOVED***return***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED***<div
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***data-slot="dialog-header"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className={cn("flex***REMOVED***flex-col***REMOVED***gap-2***REMOVED***text-center***REMOVED***sm:text-left",***REMOVED***className)}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{...props}
***REMOVED******REMOVED******REMOVED******REMOVED***/>
***REMOVED******REMOVED***)
}

function***REMOVED***DialogFooter({***REMOVED***className,***REMOVED***...props***REMOVED***}:***REMOVED***React.ComponentProps<"div">)***REMOVED***{
***REMOVED******REMOVED***return***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED***<div
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***data-slot="dialog-footer"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className={cn(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"flex***REMOVED***flex-col-reverse***REMOVED***gap-2***REMOVED***sm:flex-row***REMOVED***sm:justify-end",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***)}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{...props}
***REMOVED******REMOVED******REMOVED******REMOVED***/>
***REMOVED******REMOVED***)
}

function***REMOVED***DialogTitle({
***REMOVED******REMOVED***className,
***REMOVED******REMOVED***...props
}:***REMOVED***React.ComponentProps<typeof***REMOVED***DialogPrimitive.Title>)***REMOVED***{
***REMOVED******REMOVED***return***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED***<DialogPrimitive.Title
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***data-slot="dialog-title"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className={cn("text-lg***REMOVED***leading-none***REMOVED***font-semibold",***REMOVED***className)}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{...props}
***REMOVED******REMOVED******REMOVED******REMOVED***/>
***REMOVED******REMOVED***)
}

function***REMOVED***DialogDescription({
***REMOVED******REMOVED***className,
***REMOVED******REMOVED***...props
}:***REMOVED***React.ComponentProps<typeof***REMOVED***DialogPrimitive.Description>)***REMOVED***{
***REMOVED******REMOVED***return***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED***<DialogPrimitive.Description
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***data-slot="dialog-description"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className={cn("text-muted-foreground***REMOVED***text-sm",***REMOVED***className)}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{...props}
***REMOVED******REMOVED******REMOVED******REMOVED***/>
***REMOVED******REMOVED***)
}

export***REMOVED***{
***REMOVED******REMOVED***Dialog,
***REMOVED******REMOVED***DialogClose,
***REMOVED******REMOVED***DialogContent,
***REMOVED******REMOVED***DialogDescription,
***REMOVED******REMOVED***DialogFooter,
***REMOVED******REMOVED***DialogHeader,
***REMOVED******REMOVED***DialogOverlay,
***REMOVED******REMOVED***DialogPortal,
***REMOVED******REMOVED***DialogTitle,
***REMOVED******REMOVED***DialogTrigger,
}
