"useclient"

import*asReactfrom"react"
import*asSheetPrimitivefrom"@radix-ui/react-dialog"
import{XIcon}from"lucide-react"

import{cn}from"@/lib/utils"

functionSheet({...props}:React.ComponentProps<typeofSheetPrimitive.Root>){
return<SheetPrimitive.Rootdata-slot="sheet"{...props}/>
}

functionSheetTrigger({
...props
}:React.ComponentProps<typeofSheetPrimitive.Trigger>){
return<SheetPrimitive.Triggerdata-slot="sheet-trigger"{...props}/>
}

functionSheetClose({
...props
}:React.ComponentProps<typeofSheetPrimitive.Close>){
return<SheetPrimitive.Closedata-slot="sheet-close"{...props}/>
}

functionSheetPortal({
...props
}:React.ComponentProps<typeofSheetPrimitive.Portal>){
return<SheetPrimitive.Portaldata-slot="sheet-portal"{...props}/>
}

functionSheetOverlay({
className,
...props
}:React.ComponentProps<typeofSheetPrimitive.Overlay>){
return(
<SheetPrimitive.Overlay
data-slot="sheet-overlay"
className={cn(
"data-[state=open]:animate-indata-[state=closed]:animate-outdata-[state=closed]:fade-out-0data-[state=open]:fade-in-0fixedinset-0z-50bg-black/50",
className
)}
{...props}
/>
)
}

functionSheetContent({
className,
children,
side="right",
...props
}:React.ComponentProps<typeofSheetPrimitive.Content>&{
side?:"top"|"right"|"bottom"|"left"
}){
return(
<SheetPortal>
<SheetOverlay/>
<SheetPrimitive.Content
data-slot="sheet-content"
className={cn(
"bg-backgrounddata-[state=open]:animate-indata-[state=closed]:animate-outfixedz-50flexflex-colgap-4shadow-lgtransitionease-in-outdata-[state=closed]:duration-300data-[state=open]:duration-500",
side==="right"&&
"data-[state=closed]:slide-out-to-rightdata-[state=open]:slide-in-from-rightinset-y-0right-0h-fullw-3/4border-lsm:max-w-sm",
side==="left"&&
"data-[state=closed]:slide-out-to-leftdata-[state=open]:slide-in-from-leftinset-y-0left-0h-fullw-3/4border-rsm:max-w-sm",
side==="top"&&
"data-[state=closed]:slide-out-to-topdata-[state=open]:slide-in-from-topinset-x-0top-0h-autoborder-b",
side==="bottom"&&
"data-[state=closed]:slide-out-to-bottomdata-[state=open]:slide-in-from-bottominset-x-0bottom-0h-autoborder-t",
className
)}
{...props}
>
{children}
<SheetPrimitive.CloseclassName="ring-offset-backgroundfocus:ring-ringdata-[state=open]:bg-secondaryabsolutetop-4right-4rounded-xsopacity-70transition-opacityhover:opacity-100focus:ring-2focus:ring-offset-2focus:outline-hiddendisabled:pointer-events-none">
<XIconclassName="size-4"/>
<spanclassName="sr-only">Close</span>
</SheetPrimitive.Close>
</SheetPrimitive.Content>
</SheetPortal>
)
}

functionSheetHeader({className,...props}:React.ComponentProps<"div">){
return(
<div
data-slot="sheet-header"
className={cn("flexflex-colgap-1.5p-4",className)}
{...props}
/>
)
}

functionSheetFooter({className,...props}:React.ComponentProps<"div">){
return(
<div
data-slot="sheet-footer"
className={cn("mt-autoflexflex-colgap-2p-4",className)}
{...props}
/>
)
}

functionSheetTitle({
className,
...props
}:React.ComponentProps<typeofSheetPrimitive.Title>){
return(
<SheetPrimitive.Title
data-slot="sheet-title"
className={cn("text-foregroundfont-semibold",className)}
{...props}
/>
)
}

functionSheetDescription({
className,
...props
}:React.ComponentProps<typeofSheetPrimitive.Description>){
return(
<SheetPrimitive.Description
data-slot="sheet-description"
className={cn("text-muted-foregroundtext-sm",className)}
{...props}
/>
)
}

export{
Sheet,
SheetTrigger,
SheetClose,
SheetContent,
SheetHeader,
SheetFooter,
SheetTitle,
SheetDescription,
}
