"use***REMOVED***client"

import***REMOVED*******REMOVED***as***REMOVED***React***REMOVED***from***REMOVED***"react"
import***REMOVED*******REMOVED***as***REMOVED***SheetPrimitive***REMOVED***from***REMOVED***"@radix-ui/react-dialog"
import***REMOVED***{***REMOVED***XIcon***REMOVED***}***REMOVED***from***REMOVED***"lucide-react"

import***REMOVED***{***REMOVED***cn***REMOVED***}***REMOVED***from***REMOVED***"@/lib/utils"

function***REMOVED***Sheet({***REMOVED***...props***REMOVED***}:***REMOVED***React.ComponentProps<typeof***REMOVED***SheetPrimitive.Root>)***REMOVED***{
***REMOVED******REMOVED***return***REMOVED***<SheetPrimitive.Root***REMOVED***data-slot="sheet"***REMOVED***{...props}***REMOVED***/>
}

function***REMOVED***SheetTrigger({
***REMOVED******REMOVED***...props
}:***REMOVED***React.ComponentProps<typeof***REMOVED***SheetPrimitive.Trigger>)***REMOVED***{
***REMOVED******REMOVED***return***REMOVED***<SheetPrimitive.Trigger***REMOVED***data-slot="sheet-trigger"***REMOVED***{...props}***REMOVED***/>
}

function***REMOVED***SheetClose({
***REMOVED******REMOVED***...props
}:***REMOVED***React.ComponentProps<typeof***REMOVED***SheetPrimitive.Close>)***REMOVED***{
***REMOVED******REMOVED***return***REMOVED***<SheetPrimitive.Close***REMOVED***data-slot="sheet-close"***REMOVED***{...props}***REMOVED***/>
}

function***REMOVED***SheetPortal({
***REMOVED******REMOVED***...props
}:***REMOVED***React.ComponentProps<typeof***REMOVED***SheetPrimitive.Portal>)***REMOVED***{
***REMOVED******REMOVED***return***REMOVED***<SheetPrimitive.Portal***REMOVED***data-slot="sheet-portal"***REMOVED***{...props}***REMOVED***/>
}

function***REMOVED***SheetOverlay({
***REMOVED******REMOVED***className,
***REMOVED******REMOVED***...props
}:***REMOVED***React.ComponentProps<typeof***REMOVED***SheetPrimitive.Overlay>)***REMOVED***{
***REMOVED******REMOVED***return***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED***<SheetPrimitive.Overlay
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***data-slot="sheet-overlay"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className={cn(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"data-[state=open]:animate-in***REMOVED***data-[state=closed]:animate-out***REMOVED***data-[state=closed]:fade-out-0***REMOVED***data-[state=open]:fade-in-0***REMOVED***fixed***REMOVED***inset-0***REMOVED***z-50***REMOVED***bg-black/50",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***)}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{...props}
***REMOVED******REMOVED******REMOVED******REMOVED***/>
***REMOVED******REMOVED***)
}

function***REMOVED***SheetContent({
***REMOVED******REMOVED***className,
***REMOVED******REMOVED***children,
***REMOVED******REMOVED***side***REMOVED***=***REMOVED***"right",
***REMOVED******REMOVED***...props
}:***REMOVED***React.ComponentProps<typeof***REMOVED***SheetPrimitive.Content>***REMOVED***&***REMOVED***{
***REMOVED******REMOVED***side?:***REMOVED***"top"***REMOVED***|***REMOVED***"right"***REMOVED***|***REMOVED***"bottom"***REMOVED***|***REMOVED***"left"
})***REMOVED***{
***REMOVED******REMOVED***return***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED***<SheetPortal>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<SheetOverlay***REMOVED***/>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<SheetPrimitive.Content
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***data-slot="sheet-content"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className={cn(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"bg-background***REMOVED***data-[state=open]:animate-in***REMOVED***data-[state=closed]:animate-out***REMOVED***fixed***REMOVED***z-50***REMOVED***flex***REMOVED***flex-col***REMOVED***gap-4***REMOVED***shadow-lg***REMOVED***transition***REMOVED***ease-in-out***REMOVED***data-[state=closed]:duration-300***REMOVED***data-[state=open]:duration-500",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***side***REMOVED***===***REMOVED***"right"***REMOVED***&&
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"data-[state=closed]:slide-out-to-right***REMOVED***data-[state=open]:slide-in-from-right***REMOVED***inset-y-0***REMOVED***right-0***REMOVED***h-full***REMOVED***w-3/4***REMOVED***border-l***REMOVED***sm:max-w-sm",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***side***REMOVED***===***REMOVED***"left"***REMOVED***&&
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"data-[state=closed]:slide-out-to-left***REMOVED***data-[state=open]:slide-in-from-left***REMOVED***inset-y-0***REMOVED***left-0***REMOVED***h-full***REMOVED***w-3/4***REMOVED***border-r***REMOVED***sm:max-w-sm",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***side***REMOVED***===***REMOVED***"top"***REMOVED***&&
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"data-[state=closed]:slide-out-to-top***REMOVED***data-[state=open]:slide-in-from-top***REMOVED***inset-x-0***REMOVED***top-0***REMOVED***h-auto***REMOVED***border-b",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***side***REMOVED***===***REMOVED***"bottom"***REMOVED***&&
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"data-[state=closed]:slide-out-to-bottom***REMOVED***data-[state=open]:slide-in-from-bottom***REMOVED***inset-x-0***REMOVED***bottom-0***REMOVED***h-auto***REMOVED***border-t",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***)}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{...props}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{children}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<SheetPrimitive.Close***REMOVED***className="ring-offset-background***REMOVED***focus:ring-ring***REMOVED***data-[state=open]:bg-secondary***REMOVED***absolute***REMOVED***top-4***REMOVED***right-4***REMOVED***rounded-xs***REMOVED***opacity-70***REMOVED***transition-opacity***REMOVED***hover:opacity-100***REMOVED***focus:ring-2***REMOVED***focus:ring-offset-2***REMOVED***focus:outline-hidden***REMOVED***disabled:pointer-events-none">
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<XIcon***REMOVED***className="size-4"***REMOVED***/>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<span***REMOVED***className="sr-only">Close</span>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</SheetPrimitive.Close>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</SheetPrimitive.Content>
***REMOVED******REMOVED******REMOVED******REMOVED***</SheetPortal>
***REMOVED******REMOVED***)
}

function***REMOVED***SheetHeader({***REMOVED***className,***REMOVED***...props***REMOVED***}:***REMOVED***React.ComponentProps<"div">)***REMOVED***{
***REMOVED******REMOVED***return***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED***<div
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***data-slot="sheet-header"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className={cn("flex***REMOVED***flex-col***REMOVED***gap-1.5***REMOVED***p-4",***REMOVED***className)}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{...props}
***REMOVED******REMOVED******REMOVED******REMOVED***/>
***REMOVED******REMOVED***)
}

function***REMOVED***SheetFooter({***REMOVED***className,***REMOVED***...props***REMOVED***}:***REMOVED***React.ComponentProps<"div">)***REMOVED***{
***REMOVED******REMOVED***return***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED***<div
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***data-slot="sheet-footer"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className={cn("mt-auto***REMOVED***flex***REMOVED***flex-col***REMOVED***gap-2***REMOVED***p-4",***REMOVED***className)}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{...props}
***REMOVED******REMOVED******REMOVED******REMOVED***/>
***REMOVED******REMOVED***)
}

function***REMOVED***SheetTitle({
***REMOVED******REMOVED***className,
***REMOVED******REMOVED***...props
}:***REMOVED***React.ComponentProps<typeof***REMOVED***SheetPrimitive.Title>)***REMOVED***{
***REMOVED******REMOVED***return***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED***<SheetPrimitive.Title
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***data-slot="sheet-title"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className={cn("text-foreground***REMOVED***font-semibold",***REMOVED***className)}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{...props}
***REMOVED******REMOVED******REMOVED******REMOVED***/>
***REMOVED******REMOVED***)
}

function***REMOVED***SheetDescription({
***REMOVED******REMOVED***className,
***REMOVED******REMOVED***...props
}:***REMOVED***React.ComponentProps<typeof***REMOVED***SheetPrimitive.Description>)***REMOVED***{
***REMOVED******REMOVED***return***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED***<SheetPrimitive.Description
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***data-slot="sheet-description"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className={cn("text-muted-foreground***REMOVED***text-sm",***REMOVED***className)}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{...props}
***REMOVED******REMOVED******REMOVED******REMOVED***/>
***REMOVED******REMOVED***)
}

export***REMOVED***{
***REMOVED******REMOVED***Sheet,
***REMOVED******REMOVED***SheetTrigger,
***REMOVED******REMOVED***SheetClose,
***REMOVED******REMOVED***SheetContent,
***REMOVED******REMOVED***SheetHeader,
***REMOVED******REMOVED***SheetFooter,
***REMOVED******REMOVED***SheetTitle,
***REMOVED******REMOVED***SheetDescription,
}
