/**
***REMOVED*******REMOVED***Performance***REMOVED***monitoring***REMOVED***utilities
***REMOVED*******REMOVED***Tracks***REMOVED***Core***REMOVED***Web***REMOVED***Vitals***REMOVED***and***REMOVED***custom***REMOVED***metrics
***REMOVED****/

export***REMOVED***interface***REMOVED***PerformanceMetric***REMOVED***{
***REMOVED******REMOVED***name:***REMOVED***string;
***REMOVED******REMOVED***value:***REMOVED***number;
***REMOVED******REMOVED***rating:***REMOVED***"good"***REMOVED***|***REMOVED***"needs-improvement"***REMOVED***|***REMOVED***"poor";
***REMOVED******REMOVED***delta?:***REMOVED***number;
}

/**
***REMOVED*******REMOVED***Report***REMOVED***Web***REMOVED***Vitals***REMOVED***to***REMOVED***console***REMOVED***(can***REMOVED***be***REMOVED***extended***REMOVED***to***REMOVED***send***REMOVED***to***REMOVED***analytics)
***REMOVED****/
export***REMOVED***function***REMOVED***reportWebVitals(metric:***REMOVED***PerformanceMetric)***REMOVED***{
***REMOVED******REMOVED***//***REMOVED***Log***REMOVED***to***REMOVED***console***REMOVED***in***REMOVED***development
***REMOVED******REMOVED***if***REMOVED***(process.env.NODE_ENV***REMOVED***===***REMOVED***"development")***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***console.log(`[Performance]***REMOVED***${metric.name}:`,***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***value:***REMOVED***metric.value,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***rating:***REMOVED***metric.rating,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***delta:***REMOVED***metric.delta,
***REMOVED******REMOVED******REMOVED******REMOVED***});
***REMOVED******REMOVED***}

***REMOVED******REMOVED***//***REMOVED***In***REMOVED***production,***REMOVED***send***REMOVED***to***REMOVED***analytics***REMOVED***service
***REMOVED******REMOVED***//***REMOVED***Example:***REMOVED***sendToAnalytics(metric);
}

/**
***REMOVED*******REMOVED***Get***REMOVED***Core***REMOVED***Web***REMOVED***Vitals***REMOVED***thresholds
***REMOVED****/
export***REMOVED***const***REMOVED***webVitalsThresholds***REMOVED***=***REMOVED***{
***REMOVED******REMOVED***FCP:***REMOVED***{***REMOVED***good:***REMOVED***1800,***REMOVED***poor:***REMOVED***3000***REMOVED***},***REMOVED***//***REMOVED***First***REMOVED***Contentful***REMOVED***Paint
***REMOVED******REMOVED***LCP:***REMOVED***{***REMOVED***good:***REMOVED***2500,***REMOVED***poor:***REMOVED***4000***REMOVED***},***REMOVED***//***REMOVED***Largest***REMOVED***Contentful***REMOVED***Paint
***REMOVED******REMOVED***FID:***REMOVED***{***REMOVED***good:***REMOVED***100,***REMOVED***poor:***REMOVED***300***REMOVED***},***REMOVED***//***REMOVED***First***REMOVED***Input***REMOVED***Delay
***REMOVED******REMOVED***CLS:***REMOVED***{***REMOVED***good:***REMOVED***0.1,***REMOVED***poor:***REMOVED***0.25***REMOVED***},***REMOVED***//***REMOVED***Cumulative***REMOVED***Layout***REMOVED***Shift
***REMOVED******REMOVED***TTFB:***REMOVED***{***REMOVED***good:***REMOVED***800,***REMOVED***poor:***REMOVED***1800***REMOVED***},***REMOVED***//***REMOVED***Time***REMOVED***to***REMOVED***First***REMOVED***Byte
***REMOVED******REMOVED***INP:***REMOVED***{***REMOVED***good:***REMOVED***200,***REMOVED***poor:***REMOVED***500***REMOVED***},***REMOVED***//***REMOVED***Interaction***REMOVED***to***REMOVED***Next***REMOVED***Paint
};

/**
***REMOVED*******REMOVED***Rate***REMOVED***a***REMOVED***metric***REMOVED***value
***REMOVED****/
export***REMOVED***function***REMOVED***rateMetric(
***REMOVED******REMOVED***name:***REMOVED***string,
***REMOVED******REMOVED***value:***REMOVED***number
):***REMOVED***"good"***REMOVED***|***REMOVED***"needs-improvement"***REMOVED***|***REMOVED***"poor"***REMOVED***{
***REMOVED******REMOVED***const***REMOVED***thresholds***REMOVED***=***REMOVED***webVitalsThresholds[name***REMOVED***as***REMOVED***keyof***REMOVED***typeof***REMOVED***webVitalsThresholds];
***REMOVED******REMOVED***
***REMOVED******REMOVED***if***REMOVED***(!thresholds)***REMOVED***return***REMOVED***"good";
***REMOVED******REMOVED***
***REMOVED******REMOVED***if***REMOVED***(value***REMOVED***<=***REMOVED***thresholds.good)***REMOVED***return***REMOVED***"good";
***REMOVED******REMOVED***if***REMOVED***(value***REMOVED***<=***REMOVED***thresholds.poor)***REMOVED***return***REMOVED***"needs-improvement";
***REMOVED******REMOVED***return***REMOVED***"poor";
}

/**
***REMOVED*******REMOVED***Measure***REMOVED***custom***REMOVED***performance***REMOVED***metric
***REMOVED****/
export***REMOVED***function***REMOVED***measurePerformance(name:***REMOVED***string,***REMOVED***fn:***REMOVED***()***REMOVED***=>***REMOVED***void***REMOVED***|***REMOVED***Promise<void>)***REMOVED***{
***REMOVED******REMOVED***const***REMOVED***startTime***REMOVED***=***REMOVED***performance.now();
***REMOVED******REMOVED***
***REMOVED******REMOVED***const***REMOVED***result***REMOVED***=***REMOVED***fn();
***REMOVED******REMOVED***
***REMOVED******REMOVED***if***REMOVED***(result***REMOVED***instanceof***REMOVED***Promise)***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***return***REMOVED***result.then(()***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***duration***REMOVED***=***REMOVED***performance.now()***REMOVED***-***REMOVED***startTime;
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***console.log(`[Performance]***REMOVED***${name}:***REMOVED***${duration.toFixed(2)}ms`);
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***return***REMOVED***duration;
***REMOVED******REMOVED******REMOVED******REMOVED***});
***REMOVED******REMOVED***}
***REMOVED******REMOVED***
***REMOVED******REMOVED***const***REMOVED***duration***REMOVED***=***REMOVED***performance.now()***REMOVED***-***REMOVED***startTime;
***REMOVED******REMOVED***console.log(`[Performance]***REMOVED***${name}:***REMOVED***${duration.toFixed(2)}ms`);
***REMOVED******REMOVED***return***REMOVED***duration;
}

/**
***REMOVED*******REMOVED***Check***REMOVED***if***REMOVED***user***REMOVED***prefers***REMOVED***reduced***REMOVED***motion
***REMOVED****/
export***REMOVED***function***REMOVED***prefersReducedMotion():***REMOVED***boolean***REMOVED***{
***REMOVED******REMOVED***if***REMOVED***(typeof***REMOVED***window***REMOVED***===***REMOVED***"undefined")***REMOVED***return***REMOVED***false;
***REMOVED******REMOVED***
***REMOVED******REMOVED***return***REMOVED***window.matchMedia("(prefers-reduced-motion:***REMOVED***reduce)").matches;
}

/**
***REMOVED*******REMOVED***Get***REMOVED***connection***REMOVED***information
***REMOVED****/
export***REMOVED***function***REMOVED***getConnectionInfo()***REMOVED***{
***REMOVED******REMOVED***if***REMOVED***(typeof***REMOVED***navigator***REMOVED***===***REMOVED***"undefined"***REMOVED***||***REMOVED***!("connection"***REMOVED***in***REMOVED***navigator))***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***return***REMOVED***null;
***REMOVED******REMOVED***}
***REMOVED******REMOVED***
***REMOVED******REMOVED***const***REMOVED***connection***REMOVED***=***REMOVED***(navigator***REMOVED***as***REMOVED***any).connection;
***REMOVED******REMOVED***
***REMOVED******REMOVED***return***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***effectiveType:***REMOVED***connection.effectiveType,***REMOVED***//***REMOVED***'4g',***REMOVED***'3g',***REMOVED***'2g',***REMOVED***'slow-2g'
***REMOVED******REMOVED******REMOVED******REMOVED***downlink:***REMOVED***connection.downlink,***REMOVED***//***REMOVED***Mbps
***REMOVED******REMOVED******REMOVED******REMOVED***rtt:***REMOVED***connection.rtt,***REMOVED***//***REMOVED***Round***REMOVED***trip***REMOVED***time***REMOVED***in***REMOVED***ms
***REMOVED******REMOVED******REMOVED******REMOVED***saveData:***REMOVED***connection.saveData,***REMOVED***//***REMOVED***Data***REMOVED***saver***REMOVED***mode
***REMOVED******REMOVED***};
}

/**
***REMOVED*******REMOVED***Adaptive***REMOVED***loading***REMOVED***based***REMOVED***on***REMOVED***connection
***REMOVED****/
export***REMOVED***function***REMOVED***shouldLoadHeavyResources():***REMOVED***boolean***REMOVED***{
***REMOVED******REMOVED***const***REMOVED***connection***REMOVED***=***REMOVED***getConnectionInfo();
***REMOVED******REMOVED***
***REMOVED******REMOVED***if***REMOVED***(!connection)***REMOVED***return***REMOVED***true;
***REMOVED******REMOVED***
***REMOVED******REMOVED***//***REMOVED***Don't***REMOVED***load***REMOVED***heavy***REMOVED***resources***REMOVED***on***REMOVED***slow***REMOVED***connections***REMOVED***or***REMOVED***data***REMOVED***saver***REMOVED***mode
***REMOVED******REMOVED***if***REMOVED***(connection.saveData)***REMOVED***return***REMOVED***false;
***REMOVED******REMOVED***if***REMOVED***(connection.effectiveType***REMOVED***===***REMOVED***"slow-2g"***REMOVED***||***REMOVED***connection.effectiveType***REMOVED***===***REMOVED***"2g")***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***return***REMOVED***false;
***REMOVED******REMOVED***}
***REMOVED******REMOVED***
***REMOVED******REMOVED***return***REMOVED***true;
}

/**
***REMOVED*******REMOVED***Monitor***REMOVED***long***REMOVED***tasks***REMOVED***(>***REMOVED***50ms)
***REMOVED****/
export***REMOVED***function***REMOVED***monitorLongTasks()***REMOVED***{
***REMOVED******REMOVED***if***REMOVED***(typeof***REMOVED***window***REMOVED***===***REMOVED***"undefined"***REMOVED***||***REMOVED***!("PerformanceObserver"***REMOVED***in***REMOVED***window))***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***return;
***REMOVED******REMOVED***}
***REMOVED******REMOVED***
***REMOVED******REMOVED***try***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***observer***REMOVED***=***REMOVED***new***REMOVED***PerformanceObserver((list)***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***for***REMOVED***(const***REMOVED***entry***REMOVED***of***REMOVED***list.getEntries())***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***console.warn(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***`[Performance]***REMOVED***Long***REMOVED***task***REMOVED***detected:***REMOVED***${entry.duration.toFixed(2)}ms`,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***entry
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***);
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***}
***REMOVED******REMOVED******REMOVED******REMOVED***});
***REMOVED******REMOVED******REMOVED******REMOVED***
***REMOVED******REMOVED******REMOVED******REMOVED***observer.observe({***REMOVED***entryTypes:***REMOVED***["longtask"]***REMOVED***});
***REMOVED******REMOVED***}***REMOVED***catch***REMOVED***(error)***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***//***REMOVED***Long***REMOVED***task***REMOVED***API***REMOVED***not***REMOVED***supported
***REMOVED******REMOVED***}
}

/**
***REMOVED*******REMOVED***Get***REMOVED***memory***REMOVED***usage***REMOVED***(if***REMOVED***available)
***REMOVED****/
export***REMOVED***function***REMOVED***getMemoryUsage()***REMOVED***{
***REMOVED******REMOVED***if***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED***typeof***REMOVED***window***REMOVED***===***REMOVED***"undefined"***REMOVED***||
***REMOVED******REMOVED******REMOVED******REMOVED***!("performance"***REMOVED***in***REMOVED***window)***REMOVED***||
***REMOVED******REMOVED******REMOVED******REMOVED***!("memory"***REMOVED***in***REMOVED***(performance***REMOVED***as***REMOVED***any))
***REMOVED******REMOVED***)***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***return***REMOVED***null;
***REMOVED******REMOVED***}
***REMOVED******REMOVED***
***REMOVED******REMOVED***const***REMOVED***memory***REMOVED***=***REMOVED***(performance***REMOVED***as***REMOVED***any).memory;
***REMOVED******REMOVED***
***REMOVED******REMOVED***return***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***usedJSHeapSize:***REMOVED***memory.usedJSHeapSize,
***REMOVED******REMOVED******REMOVED******REMOVED***totalJSHeapSize:***REMOVED***memory.totalJSHeapSize,
***REMOVED******REMOVED******REMOVED******REMOVED***jsHeapSizeLimit:***REMOVED***memory.jsHeapSizeLimit,
***REMOVED******REMOVED******REMOVED******REMOVED***usagePercent:***REMOVED***(memory.usedJSHeapSize***REMOVED***/***REMOVED***memory.jsHeapSizeLimit)***REMOVED*******REMOVED***100,
***REMOVED******REMOVED***};
}
