import***REMOVED***type***REMOVED***{***REMOVED***QuickAction,***REMOVED***QuickActionCategory***REMOVED***}***REMOVED***from***REMOVED***"@/types";

//***REMOVED***Storage***REMOVED***keys
const***REMOVED***STORAGE_KEYS***REMOVED***=***REMOVED***{
***REMOVED******REMOVED***FAVORITES:***REMOVED***"aura_quick_actions_favorites",
***REMOVED******REMOVED***USAGE_COUNTS:***REMOVED***"aura_quick_actions_usage",
}***REMOVED***as***REMOVED***const;

//***REMOVED***Default***REMOVED***quick***REMOVED***action***REMOVED***templates***REMOVED***(8+***REMOVED***actions)
export***REMOVED***const***REMOVED***DEFAULT_QUICK_ACTIONS:***REMOVED***QuickAction[]***REMOVED***=***REMOVED***[
***REMOVED******REMOVED***//***REMOVED***Email***REMOVED***actions
***REMOVED******REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***id:***REMOVED***"email-1",
***REMOVED******REMOVED******REMOVED******REMOVED***title:***REMOVED***"Summarize***REMOVED***Emails",
***REMOVED******REMOVED******REMOVED******REMOVED***description:***REMOVED***"Get***REMOVED***a***REMOVED***summary***REMOVED***of***REMOVED***unread***REMOVED***emails***REMOVED***from***REMOVED***the***REMOVED***last***REMOVED***24***REMOVED***hours",
***REMOVED******REMOVED******REMOVED******REMOVED***template:***REMOVED***"Summarize***REMOVED***all***REMOVED***unread***REMOVED***emails***REMOVED***from***REMOVED***the***REMOVED***last***REMOVED***24***REMOVED***hours",
***REMOVED******REMOVED******REMOVED******REMOVED***icon:***REMOVED***"Mail",
***REMOVED******REMOVED******REMOVED******REMOVED***category:***REMOVED***"email",
***REMOVED******REMOVED******REMOVED******REMOVED***isFavorite:***REMOVED***false,
***REMOVED******REMOVED******REMOVED******REMOVED***usageCount:***REMOVED***0,
***REMOVED******REMOVED***},
***REMOVED******REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***id:***REMOVED***"email-2",
***REMOVED******REMOVED******REMOVED******REMOVED***title:***REMOVED***"Draft***REMOVED***Response",
***REMOVED******REMOVED******REMOVED******REMOVED***description:***REMOVED***"Draft***REMOVED***a***REMOVED***professional***REMOVED***email***REMOVED***response",
***REMOVED******REMOVED******REMOVED******REMOVED***template:***REMOVED***"Draft***REMOVED***a***REMOVED***professional***REMOVED***response***REMOVED***to***REMOVED***my***REMOVED***most***REMOVED***recent***REMOVED***unread***REMOVED***email",
***REMOVED******REMOVED******REMOVED******REMOVED***icon:***REMOVED***"Mail",
***REMOVED******REMOVED******REMOVED******REMOVED***category:***REMOVED***"email",
***REMOVED******REMOVED******REMOVED******REMOVED***isFavorite:***REMOVED***false,
***REMOVED******REMOVED******REMOVED******REMOVED***usageCount:***REMOVED***0,
***REMOVED******REMOVED***},
***REMOVED******REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***id:***REMOVED***"email-3",
***REMOVED******REMOVED******REMOVED******REMOVED***title:***REMOVED***"Find***REMOVED***Important***REMOVED***Emails",
***REMOVED******REMOVED******REMOVED******REMOVED***description:***REMOVED***"Find***REMOVED***emails***REMOVED***marked***REMOVED***as***REMOVED***important***REMOVED***or***REMOVED***urgent",
***REMOVED******REMOVED******REMOVED******REMOVED***template:***REMOVED***"Find***REMOVED***all***REMOVED***important***REMOVED***or***REMOVED***urgent***REMOVED***emails***REMOVED***from***REMOVED***the***REMOVED***last***REMOVED***week",
***REMOVED******REMOVED******REMOVED******REMOVED***icon:***REMOVED***"Mail",
***REMOVED******REMOVED******REMOVED******REMOVED***category:***REMOVED***"email",
***REMOVED******REMOVED******REMOVED******REMOVED***isFavorite:***REMOVED***false,
***REMOVED******REMOVED******REMOVED******REMOVED***usageCount:***REMOVED***0,
***REMOVED******REMOVED***},
***REMOVED******REMOVED***
***REMOVED******REMOVED***//***REMOVED***Docs***REMOVED***actions
***REMOVED******REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***id:***REMOVED***"docs-1",
***REMOVED******REMOVED******REMOVED******REMOVED***title:***REMOVED***"Create***REMOVED***Meeting***REMOVED***Notes",
***REMOVED******REMOVED******REMOVED******REMOVED***description:***REMOVED***"Generate***REMOVED***meeting***REMOVED***notes***REMOVED***document***REMOVED***from***REMOVED***calendar***REMOVED***event",
***REMOVED******REMOVED******REMOVED******REMOVED***template:***REMOVED***"Create***REMOVED***a***REMOVED***meeting***REMOVED***notes***REMOVED***document***REMOVED***for***REMOVED***my***REMOVED***next***REMOVED***calendar***REMOVED***event",
***REMOVED******REMOVED******REMOVED******REMOVED***icon:***REMOVED***"FileText",
***REMOVED******REMOVED******REMOVED******REMOVED***category:***REMOVED***"docs",
***REMOVED******REMOVED******REMOVED******REMOVED***isFavorite:***REMOVED***false,
***REMOVED******REMOVED******REMOVED******REMOVED***usageCount:***REMOVED***0,
***REMOVED******REMOVED***},
***REMOVED******REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***id:***REMOVED***"docs-2",
***REMOVED******REMOVED******REMOVED******REMOVED***title:***REMOVED***"Create***REMOVED***Report",
***REMOVED******REMOVED******REMOVED******REMOVED***description:***REMOVED***"Generate***REMOVED***a***REMOVED***weekly***REMOVED***report***REMOVED***document",
***REMOVED******REMOVED******REMOVED******REMOVED***template:***REMOVED***"Create***REMOVED***a***REMOVED***weekly***REMOVED***report***REMOVED***document***REMOVED***summarizing***REMOVED***my***REMOVED***activities",
***REMOVED******REMOVED******REMOVED******REMOVED***icon:***REMOVED***"FileText",
***REMOVED******REMOVED******REMOVED******REMOVED***category:***REMOVED***"docs",
***REMOVED******REMOVED******REMOVED******REMOVED***isFavorite:***REMOVED***false,
***REMOVED******REMOVED******REMOVED******REMOVED***usageCount:***REMOVED***0,
***REMOVED******REMOVED***},
***REMOVED******REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***id:***REMOVED***"docs-3",
***REMOVED******REMOVED******REMOVED******REMOVED***title:***REMOVED***"Organize***REMOVED***Files",
***REMOVED******REMOVED******REMOVED******REMOVED***description:***REMOVED***"Organize***REMOVED***recent***REMOVED***Drive***REMOVED***files***REMOVED***into***REMOVED***folders",
***REMOVED******REMOVED******REMOVED******REMOVED***template:***REMOVED***"Organize***REMOVED***my***REMOVED***recent***REMOVED***Drive***REMOVED***files***REMOVED***into***REMOVED***appropriate***REMOVED***folders***REMOVED***by***REMOVED***topic",
***REMOVED******REMOVED******REMOVED******REMOVED***icon:***REMOVED***"FileText",
***REMOVED******REMOVED******REMOVED******REMOVED***category:***REMOVED***"docs",
***REMOVED******REMOVED******REMOVED******REMOVED***isFavorite:***REMOVED***false,
***REMOVED******REMOVED******REMOVED******REMOVED***usageCount:***REMOVED***0,
***REMOVED******REMOVED***},
***REMOVED******REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***id:***REMOVED***"docs-4",
***REMOVED******REMOVED******REMOVED******REMOVED***title:***REMOVED***"Create***REMOVED***Document***REMOVED***from***REMOVED***Email",
***REMOVED******REMOVED******REMOVED******REMOVED***description:***REMOVED***"Convert***REMOVED***email***REMOVED***thread***REMOVED***into***REMOVED***a***REMOVED***document",
***REMOVED******REMOVED******REMOVED******REMOVED***template:***REMOVED***"Create***REMOVED***a***REMOVED***Google***REMOVED***Doc***REMOVED***from***REMOVED***my***REMOVED***latest***REMOVED***email***REMOVED***thread***REMOVED***with***REMOVED***action***REMOVED***items",
***REMOVED******REMOVED******REMOVED******REMOVED***icon:***REMOVED***"FileText",
***REMOVED******REMOVED******REMOVED******REMOVED***category:***REMOVED***"docs",
***REMOVED******REMOVED******REMOVED******REMOVED***isFavorite:***REMOVED***false,
***REMOVED******REMOVED******REMOVED******REMOVED***usageCount:***REMOVED***0,
***REMOVED******REMOVED***},
***REMOVED******REMOVED***
***REMOVED******REMOVED***//***REMOVED***Calendar***REMOVED***actions
***REMOVED******REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***id:***REMOVED***"calendar-1",
***REMOVED******REMOVED******REMOVED******REMOVED***title:***REMOVED***"Schedule***REMOVED***Follow-up",
***REMOVED******REMOVED******REMOVED******REMOVED***description:***REMOVED***"Schedule***REMOVED***a***REMOVED***follow-up***REMOVED***meeting***REMOVED***based***REMOVED***on***REMOVED***email***REMOVED***thread",
***REMOVED******REMOVED******REMOVED******REMOVED***template:***REMOVED***"Schedule***REMOVED***a***REMOVED***follow-up***REMOVED***meeting***REMOVED***based***REMOVED***on***REMOVED***my***REMOVED***latest***REMOVED***email***REMOVED***thread",
***REMOVED******REMOVED******REMOVED******REMOVED***icon:***REMOVED***"Calendar",
***REMOVED******REMOVED******REMOVED******REMOVED***category:***REMOVED***"calendar",
***REMOVED******REMOVED******REMOVED******REMOVED***isFavorite:***REMOVED***false,
***REMOVED******REMOVED******REMOVED******REMOVED***usageCount:***REMOVED***0,
***REMOVED******REMOVED***},
***REMOVED******REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***id:***REMOVED***"calendar-2",
***REMOVED******REMOVED******REMOVED******REMOVED***title:***REMOVED***"Find***REMOVED***Available***REMOVED***Slots",
***REMOVED******REMOVED******REMOVED******REMOVED***description:***REMOVED***"Find***REMOVED***available***REMOVED***meeting***REMOVED***times***REMOVED***this***REMOVED***week",
***REMOVED******REMOVED******REMOVED******REMOVED***template:***REMOVED***"Find***REMOVED***all***REMOVED***available***REMOVED***{duration}-hour***REMOVED***meeting***REMOVED***slots***REMOVED***in***REMOVED***my***REMOVED***calendar***REMOVED***{timeframe}",
***REMOVED******REMOVED******REMOVED******REMOVED***icon:***REMOVED***"Calendar",
***REMOVED******REMOVED******REMOVED******REMOVED***category:***REMOVED***"calendar",
***REMOVED******REMOVED******REMOVED******REMOVED***isFavorite:***REMOVED***false,
***REMOVED******REMOVED******REMOVED******REMOVED***usageCount:***REMOVED***0,
***REMOVED******REMOVED******REMOVED******REMOVED***parameters:***REMOVED***[
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***name:***REMOVED***"duration",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***label:***REMOVED***"Meeting***REMOVED***Duration***REMOVED***(hours)",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***type:***REMOVED***"number",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***placeholder:***REMOVED***"1",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***required:***REMOVED***true,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***defaultValue:***REMOVED***"1",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***},
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***name:***REMOVED***"timeframe",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***label:***REMOVED***"Timeframe",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***type:***REMOVED***"text",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***placeholder:***REMOVED***"this***REMOVED***week",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***required:***REMOVED***true,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***defaultValue:***REMOVED***"this***REMOVED***week",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***},
***REMOVED******REMOVED******REMOVED******REMOVED***],
***REMOVED******REMOVED***},
***REMOVED******REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***id:***REMOVED***"calendar-3",
***REMOVED******REMOVED******REMOVED******REMOVED***title:***REMOVED***"Summarize***REMOVED***Today's***REMOVED***Schedule",
***REMOVED******REMOVED******REMOVED******REMOVED***description:***REMOVED***"Get***REMOVED***a***REMOVED***summary***REMOVED***of***REMOVED***today's***REMOVED***meetings***REMOVED***and***REMOVED***events",
***REMOVED******REMOVED******REMOVED******REMOVED***template:***REMOVED***"Summarize***REMOVED***all***REMOVED***my***REMOVED***meetings***REMOVED***and***REMOVED***events***REMOVED***scheduled***REMOVED***for***REMOVED***today",
***REMOVED******REMOVED******REMOVED******REMOVED***icon:***REMOVED***"Calendar",
***REMOVED******REMOVED******REMOVED******REMOVED***category:***REMOVED***"calendar",
***REMOVED******REMOVED******REMOVED******REMOVED***isFavorite:***REMOVED***false,
***REMOVED******REMOVED******REMOVED******REMOVED***usageCount:***REMOVED***0,
***REMOVED******REMOVED***},
***REMOVED******REMOVED***
***REMOVED******REMOVED***//***REMOVED***Analysis***REMOVED***actions
***REMOVED******REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***id:***REMOVED***"analysis-1",
***REMOVED******REMOVED******REMOVED******REMOVED***title:***REMOVED***"Analyze***REMOVED***Spreadsheet",
***REMOVED******REMOVED******REMOVED******REMOVED***description:***REMOVED***"Generate***REMOVED***insights***REMOVED***from***REMOVED***spreadsheet***REMOVED***data",
***REMOVED******REMOVED******REMOVED******REMOVED***template:***REMOVED***"Analyze***REMOVED***the***REMOVED***data***REMOVED***in***REMOVED***my***REMOVED***latest***REMOVED***spreadsheet***REMOVED***and***REMOVED***provide***REMOVED***insights",
***REMOVED******REMOVED******REMOVED******REMOVED***icon:***REMOVED***"BarChart3",
***REMOVED******REMOVED******REMOVED******REMOVED***category:***REMOVED***"analysis",
***REMOVED******REMOVED******REMOVED******REMOVED***isFavorite:***REMOVED***false,
***REMOVED******REMOVED******REMOVED******REMOVED***usageCount:***REMOVED***0,
***REMOVED******REMOVED***},
***REMOVED******REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***id:***REMOVED***"analysis-2",
***REMOVED******REMOVED******REMOVED******REMOVED***title:***REMOVED***"Create***REMOVED***Chart***REMOVED***from***REMOVED***Data",
***REMOVED******REMOVED******REMOVED******REMOVED***description:***REMOVED***"Generate***REMOVED***visualizations***REMOVED***from***REMOVED***spreadsheet***REMOVED***data",
***REMOVED******REMOVED******REMOVED******REMOVED***template:***REMOVED***"Create***REMOVED***charts***REMOVED***and***REMOVED***visualizations***REMOVED***from***REMOVED***my***REMOVED***latest***REMOVED***spreadsheet***REMOVED***data",
***REMOVED******REMOVED******REMOVED******REMOVED***icon:***REMOVED***"BarChart3",
***REMOVED******REMOVED******REMOVED******REMOVED***category:***REMOVED***"analysis",
***REMOVED******REMOVED******REMOVED******REMOVED***isFavorite:***REMOVED***false,
***REMOVED******REMOVED******REMOVED******REMOVED***usageCount:***REMOVED***0,
***REMOVED******REMOVED***},
***REMOVED******REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***id:***REMOVED***"analysis-3",
***REMOVED******REMOVED******REMOVED******REMOVED***title:***REMOVED***"Email***REMOVED***Analytics",
***REMOVED******REMOVED******REMOVED******REMOVED***description:***REMOVED***"Analyze***REMOVED***email***REMOVED***patterns***REMOVED***and***REMOVED***statistics",
***REMOVED******REMOVED******REMOVED******REMOVED***template:***REMOVED***"Analyze***REMOVED***my***REMOVED***email***REMOVED***patterns***REMOVED***from***REMOVED***the***REMOVED***last***REMOVED***month***REMOVED***and***REMOVED***provide***REMOVED***statistics",
***REMOVED******REMOVED******REMOVED******REMOVED***icon:***REMOVED***"BarChart3",
***REMOVED******REMOVED******REMOVED******REMOVED***category:***REMOVED***"analysis",
***REMOVED******REMOVED******REMOVED******REMOVED***isFavorite:***REMOVED***false,
***REMOVED******REMOVED******REMOVED******REMOVED***usageCount:***REMOVED***0,
***REMOVED******REMOVED***},
];

//***REMOVED***Storage***REMOVED***utilities
export***REMOVED***const***REMOVED***QuickActionsStorage***REMOVED***=***REMOVED***{
***REMOVED******REMOVED***/**
***REMOVED******REMOVED******REMOVED*******REMOVED***Get***REMOVED***favorite***REMOVED***action***REMOVED***IDs***REMOVED***from***REMOVED***localStorage
***REMOVED******REMOVED******REMOVED****/
***REMOVED******REMOVED***getFavorites():***REMOVED***string[]***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***if***REMOVED***(typeof***REMOVED***window***REMOVED***===***REMOVED***"undefined")***REMOVED***return***REMOVED***[];
***REMOVED******REMOVED******REMOVED******REMOVED***
***REMOVED******REMOVED******REMOVED******REMOVED***try***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***stored***REMOVED***=***REMOVED***localStorage.getItem(STORAGE_KEYS.FAVORITES);
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***return***REMOVED***stored***REMOVED***?***REMOVED***JSON.parse(stored)***REMOVED***:***REMOVED***[];
***REMOVED******REMOVED******REMOVED******REMOVED***}***REMOVED***catch***REMOVED***(error)***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***console.error("Error***REMOVED***reading***REMOVED***favorites***REMOVED***from***REMOVED***localStorage:",***REMOVED***error);
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***return***REMOVED***[];
***REMOVED******REMOVED******REMOVED******REMOVED***}
***REMOVED******REMOVED***},

***REMOVED******REMOVED***/**
***REMOVED******REMOVED******REMOVED*******REMOVED***Save***REMOVED***favorite***REMOVED***action***REMOVED***IDs***REMOVED***to***REMOVED***localStorage
***REMOVED******REMOVED******REMOVED*******REMOVED***Maximum***REMOVED***20***REMOVED***favorites***REMOVED***per***REMOVED***user
***REMOVED******REMOVED******REMOVED****/
***REMOVED******REMOVED***saveFavorites(favoriteIds:***REMOVED***string[]):***REMOVED***void***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***if***REMOVED***(typeof***REMOVED***window***REMOVED***===***REMOVED***"undefined")***REMOVED***return;
***REMOVED******REMOVED******REMOVED******REMOVED***
***REMOVED******REMOVED******REMOVED******REMOVED***try***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***//***REMOVED***Limit***REMOVED***to***REMOVED***20***REMOVED***favorites
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***limited***REMOVED***=***REMOVED***favoriteIds.slice(0,***REMOVED***20);
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***localStorage.setItem(STORAGE_KEYS.FAVORITES,***REMOVED***JSON.stringify(limited));
***REMOVED******REMOVED******REMOVED******REMOVED***}***REMOVED***catch***REMOVED***(error)***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***console.error("Error***REMOVED***saving***REMOVED***favorites***REMOVED***to***REMOVED***localStorage:",***REMOVED***error);
***REMOVED******REMOVED******REMOVED******REMOVED***}
***REMOVED******REMOVED***},

***REMOVED******REMOVED***/**
***REMOVED******REMOVED******REMOVED*******REMOVED***Toggle***REMOVED***favorite***REMOVED***status***REMOVED***for***REMOVED***an***REMOVED***action
***REMOVED******REMOVED******REMOVED****/
***REMOVED******REMOVED***toggleFavorite(actionId:***REMOVED***string):***REMOVED***string[]***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***favorites***REMOVED***=***REMOVED***this.getFavorites();
***REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***index***REMOVED***=***REMOVED***favorites.indexOf(actionId);
***REMOVED******REMOVED******REMOVED******REMOVED***
***REMOVED******REMOVED******REMOVED******REMOVED***if***REMOVED***(index***REMOVED***>***REMOVED***-1)***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***//***REMOVED***Remove***REMOVED***from***REMOVED***favorites
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***favorites.splice(index,***REMOVED***1);
***REMOVED******REMOVED******REMOVED******REMOVED***}***REMOVED***else***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***//***REMOVED***Add***REMOVED***to***REMOVED***favorites***REMOVED***(check***REMOVED***limit)
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***if***REMOVED***(favorites.length***REMOVED***<***REMOVED***20)***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***favorites.push(actionId);
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***}***REMOVED***else***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***console.warn("Maximum***REMOVED***of***REMOVED***20***REMOVED***favorites***REMOVED***reached");
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***return***REMOVED***favorites;
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***}
***REMOVED******REMOVED******REMOVED******REMOVED***}
***REMOVED******REMOVED******REMOVED******REMOVED***
***REMOVED******REMOVED******REMOVED******REMOVED***this.saveFavorites(favorites);
***REMOVED******REMOVED******REMOVED******REMOVED***return***REMOVED***favorites;
***REMOVED******REMOVED***},

***REMOVED******REMOVED***/**
***REMOVED******REMOVED******REMOVED*******REMOVED***Get***REMOVED***usage***REMOVED***counts***REMOVED***from***REMOVED***localStorage
***REMOVED******REMOVED******REMOVED****/
***REMOVED******REMOVED***getUsageCounts():***REMOVED***Record<string,***REMOVED***number>***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***if***REMOVED***(typeof***REMOVED***window***REMOVED***===***REMOVED***"undefined")***REMOVED***return***REMOVED***{};
***REMOVED******REMOVED******REMOVED******REMOVED***
***REMOVED******REMOVED******REMOVED******REMOVED***try***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***stored***REMOVED***=***REMOVED***localStorage.getItem(STORAGE_KEYS.USAGE_COUNTS);
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***return***REMOVED***stored***REMOVED***?***REMOVED***JSON.parse(stored)***REMOVED***:***REMOVED***{};
***REMOVED******REMOVED******REMOVED******REMOVED***}***REMOVED***catch***REMOVED***(error)***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***console.error("Error***REMOVED***reading***REMOVED***usage***REMOVED***counts***REMOVED***from***REMOVED***localStorage:",***REMOVED***error);
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***return***REMOVED***{};
***REMOVED******REMOVED******REMOVED******REMOVED***}
***REMOVED******REMOVED***},

***REMOVED******REMOVED***/**
***REMOVED******REMOVED******REMOVED*******REMOVED***Save***REMOVED***usage***REMOVED***counts***REMOVED***to***REMOVED***localStorage
***REMOVED******REMOVED******REMOVED****/
***REMOVED******REMOVED***saveUsageCounts(counts:***REMOVED***Record<string,***REMOVED***number>):***REMOVED***void***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***if***REMOVED***(typeof***REMOVED***window***REMOVED***===***REMOVED***"undefined")***REMOVED***return;
***REMOVED******REMOVED******REMOVED******REMOVED***
***REMOVED******REMOVED******REMOVED******REMOVED***try***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***localStorage.setItem(STORAGE_KEYS.USAGE_COUNTS,***REMOVED***JSON.stringify(counts));
***REMOVED******REMOVED******REMOVED******REMOVED***}***REMOVED***catch***REMOVED***(error)***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***console.error("Error***REMOVED***saving***REMOVED***usage***REMOVED***counts***REMOVED***to***REMOVED***localStorage:",***REMOVED***error);
***REMOVED******REMOVED******REMOVED******REMOVED***}
***REMOVED******REMOVED***},

***REMOVED******REMOVED***/**
***REMOVED******REMOVED******REMOVED*******REMOVED***Increment***REMOVED***usage***REMOVED***count***REMOVED***for***REMOVED***an***REMOVED***action
***REMOVED******REMOVED******REMOVED****/
***REMOVED******REMOVED***incrementUsage(actionId:***REMOVED***string):***REMOVED***number***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***counts***REMOVED***=***REMOVED***this.getUsageCounts();
***REMOVED******REMOVED******REMOVED******REMOVED***counts[actionId]***REMOVED***=***REMOVED***(counts[actionId]***REMOVED***||***REMOVED***0)***REMOVED***+***REMOVED***1;
***REMOVED******REMOVED******REMOVED******REMOVED***this.saveUsageCounts(counts);
***REMOVED******REMOVED******REMOVED******REMOVED***return***REMOVED***counts[actionId];
***REMOVED******REMOVED***},

***REMOVED******REMOVED***/**
***REMOVED******REMOVED******REMOVED*******REMOVED***Get***REMOVED***all***REMOVED***quick***REMOVED***actions***REMOVED***with***REMOVED***favorites***REMOVED***and***REMOVED***usage***REMOVED***counts***REMOVED***applied
***REMOVED******REMOVED******REMOVED****/
***REMOVED******REMOVED***getQuickActions():***REMOVED***QuickAction[]***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***favorites***REMOVED***=***REMOVED***this.getFavorites();
***REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***usageCounts***REMOVED***=***REMOVED***this.getUsageCounts();
***REMOVED******REMOVED******REMOVED******REMOVED***
***REMOVED******REMOVED******REMOVED******REMOVED***return***REMOVED***DEFAULT_QUICK_ACTIONS.map((action)***REMOVED***=>***REMOVED***({
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***...action,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***isFavorite:***REMOVED***favorites.includes(action.id),
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***usageCount:***REMOVED***usageCounts[action.id]***REMOVED***||***REMOVED***0,
***REMOVED******REMOVED******REMOVED******REMOVED***}));
***REMOVED******REMOVED***},

***REMOVED******REMOVED***/**
***REMOVED******REMOVED******REMOVED*******REMOVED***Get***REMOVED***favorite***REMOVED***actions
***REMOVED******REMOVED******REMOVED****/
***REMOVED******REMOVED***getFavoriteActions():***REMOVED***QuickAction[]***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***actions***REMOVED***=***REMOVED***this.getQuickActions();
***REMOVED******REMOVED******REMOVED******REMOVED***return***REMOVED***actions.filter((action)***REMOVED***=>***REMOVED***action.isFavorite);
***REMOVED******REMOVED***},

***REMOVED******REMOVED***/**
***REMOVED******REMOVED******REMOVED*******REMOVED***Get***REMOVED***recent***REMOVED***actions***REMOVED***(sorted***REMOVED***by***REMOVED***usage***REMOVED***count,***REMOVED***top***REMOVED***5)
***REMOVED******REMOVED******REMOVED****/
***REMOVED******REMOVED***getRecentActions(limit:***REMOVED***number***REMOVED***=***REMOVED***5):***REMOVED***QuickAction[]***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***actions***REMOVED***=***REMOVED***this.getQuickActions();
***REMOVED******REMOVED******REMOVED******REMOVED***return***REMOVED***actions
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***.filter((action)***REMOVED***=>***REMOVED***action.usageCount***REMOVED***>***REMOVED***0)
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***.sort((a,***REMOVED***b)***REMOVED***=>***REMOVED***b.usageCount***REMOVED***-***REMOVED***a.usageCount)
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***.slice(0,***REMOVED***limit);
***REMOVED******REMOVED***},

***REMOVED******REMOVED***/**
***REMOVED******REMOVED******REMOVED*******REMOVED***Get***REMOVED***actions***REMOVED***by***REMOVED***category
***REMOVED******REMOVED******REMOVED****/
***REMOVED******REMOVED***getActionsByCategory(category:***REMOVED***QuickActionCategory):***REMOVED***QuickAction[]***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***actions***REMOVED***=***REMOVED***this.getQuickActions();
***REMOVED******REMOVED******REMOVED******REMOVED***return***REMOVED***actions.filter((action)***REMOVED***=>***REMOVED***action.category***REMOVED***===***REMOVED***category);
***REMOVED******REMOVED***},

***REMOVED******REMOVED***/**
***REMOVED******REMOVED******REMOVED*******REMOVED***Search***REMOVED***actions***REMOVED***by***REMOVED***query
***REMOVED******REMOVED******REMOVED****/
***REMOVED******REMOVED***searchActions(query:***REMOVED***string):***REMOVED***QuickAction[]***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***if***REMOVED***(!query.trim())***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***return***REMOVED***this.getQuickActions();
***REMOVED******REMOVED******REMOVED******REMOVED***}
***REMOVED******REMOVED******REMOVED******REMOVED***
***REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***actions***REMOVED***=***REMOVED***this.getQuickActions();
***REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***lowerQuery***REMOVED***=***REMOVED***query.toLowerCase();
***REMOVED******REMOVED******REMOVED******REMOVED***
***REMOVED******REMOVED******REMOVED******REMOVED***return***REMOVED***actions.filter(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***(action)***REMOVED***=>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***action.title.toLowerCase().includes(lowerQuery)***REMOVED***||
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***action.description.toLowerCase().includes(lowerQuery)***REMOVED***||
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***action.template.toLowerCase().includes(lowerQuery)
***REMOVED******REMOVED******REMOVED******REMOVED***);
***REMOVED******REMOVED***},

***REMOVED******REMOVED***/**
***REMOVED******REMOVED******REMOVED*******REMOVED***Clear***REMOVED***all***REMOVED***storage***REMOVED***(for***REMOVED***testing***REMOVED***or***REMOVED***reset)
***REMOVED******REMOVED******REMOVED****/
***REMOVED******REMOVED***clearStorage():***REMOVED***void***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***if***REMOVED***(typeof***REMOVED***window***REMOVED***===***REMOVED***"undefined")***REMOVED***return;
***REMOVED******REMOVED******REMOVED******REMOVED***
***REMOVED******REMOVED******REMOVED******REMOVED***try***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***localStorage.removeItem(STORAGE_KEYS.FAVORITES);
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***localStorage.removeItem(STORAGE_KEYS.USAGE_COUNTS);
***REMOVED******REMOVED******REMOVED******REMOVED***}***REMOVED***catch***REMOVED***(error)***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***console.error("Error***REMOVED***clearing***REMOVED***quick***REMOVED***actions***REMOVED***storage:",***REMOVED***error);
***REMOVED******REMOVED******REMOVED******REMOVED***}
***REMOVED******REMOVED***},
};
