importtype{QuickAction,QuickActionCategory}from"@/types";

//Storagekeys
constSTORAGE_KEYS={
FAVORITES:"aura_quick_actions_favorites",
USAGE_COUNTS:"aura_quick_actions_usage",
}asconst;

//Defaultquickactiontemplates(8+actions)
exportconstDEFAULT_QUICK_ACTIONS:QuickAction[]=[
//Emailactions
{
id:"email-1",
title:"SummarizeEmails",
description:"Getasummaryofunreademailsfromthelast24hours",
template:"Summarizeallunreademailsfromthelast24hours",
icon:"Mail",
category:"email",
isFavorite:false,
usageCount:0,
},
{
id:"email-2",
title:"DraftResponse",
description:"Draftaprofessionalemailresponse",
template:"Draftaprofessionalresponsetomymostrecentunreademail",
icon:"Mail",
category:"email",
isFavorite:false,
usageCount:0,
},
{
id:"email-3",
title:"FindImportantEmails",
description:"Findemailsmarkedasimportantorurgent",
template:"Findallimportantorurgentemailsfromthelastweek",
icon:"Mail",
category:"email",
isFavorite:false,
usageCount:0,
},

//Docsactions
{
id:"docs-1",
title:"CreateMeetingNotes",
description:"Generatemeetingnotesdocumentfromcalendarevent",
template:"Createameetingnotesdocumentformynextcalendarevent",
icon:"FileText",
category:"docs",
isFavorite:false,
usageCount:0,
},
{
id:"docs-2",
title:"CreateReport",
description:"Generateaweeklyreportdocument",
template:"Createaweeklyreportdocumentsummarizingmyactivities",
icon:"FileText",
category:"docs",
isFavorite:false,
usageCount:0,
},
{
id:"docs-3",
title:"OrganizeFiles",
description:"OrganizerecentDrivefilesintofolders",
template:"OrganizemyrecentDrivefilesintoappropriatefoldersbytopic",
icon:"FileText",
category:"docs",
isFavorite:false,
usageCount:0,
},
{
id:"docs-4",
title:"CreateDocumentfromEmail",
description:"Convertemailthreadintoadocument",
template:"CreateaGoogleDocfrommylatestemailthreadwithactionitems",
icon:"FileText",
category:"docs",
isFavorite:false,
usageCount:0,
},

//Calendaractions
{
id:"calendar-1",
title:"ScheduleFollow-up",
description:"Scheduleafollow-upmeetingbasedonemailthread",
template:"Scheduleafollow-upmeetingbasedonmylatestemailthread",
icon:"Calendar",
category:"calendar",
isFavorite:false,
usageCount:0,
},
{
id:"calendar-2",
title:"FindAvailableSlots",
description:"Findavailablemeetingtimesthisweek",
template:"Findallavailable{duration}-hourmeetingslotsinmycalendar{timeframe}",
icon:"Calendar",
category:"calendar",
isFavorite:false,
usageCount:0,
parameters:[
{
name:"duration",
label:"MeetingDuration(hours)",
type:"number",
placeholder:"1",
required:true,
defaultValue:"1",
},
{
name:"timeframe",
label:"Timeframe",
type:"text",
placeholder:"thisweek",
required:true,
defaultValue:"thisweek",
},
],
},
{
id:"calendar-3",
title:"SummarizeToday'sSchedule",
description:"Getasummaryoftoday'smeetingsandevents",
template:"Summarizeallmymeetingsandeventsscheduledfortoday",
icon:"Calendar",
category:"calendar",
isFavorite:false,
usageCount:0,
},

//Analysisactions
{
id:"analysis-1",
title:"AnalyzeSpreadsheet",
description:"Generateinsightsfromspreadsheetdata",
template:"Analyzethedatainmylatestspreadsheetandprovideinsights",
icon:"BarChart3",
category:"analysis",
isFavorite:false,
usageCount:0,
},
{
id:"analysis-2",
title:"CreateChartfromData",
description:"Generatevisualizationsfromspreadsheetdata",
template:"Createchartsandvisualizationsfrommylatestspreadsheetdata",
icon:"BarChart3",
category:"analysis",
isFavorite:false,
usageCount:0,
},
{
id:"analysis-3",
title:"EmailAnalytics",
description:"Analyzeemailpatternsandstatistics",
template:"Analyzemyemailpatternsfromthelastmonthandprovidestatistics",
icon:"BarChart3",
category:"analysis",
isFavorite:false,
usageCount:0,
},
];

//Storageutilities
exportconstQuickActionsStorage={
/**
*GetfavoriteactionIDsfromlocalStorage
*/
getFavorites():string[]{
if(typeofwindow==="undefined")return[];

try{
conststored=localStorage.getItem(STORAGE_KEYS.FAVORITES);
returnstored?JSON.parse(stored):[];
}catch(error){
console.error("ErrorreadingfavoritesfromlocalStorage:",error);
return[];
}
},

/**
*SavefavoriteactionIDstolocalStorage
*Maximum20favoritesperuser
*/
saveFavorites(favoriteIds:string[]):void{
if(typeofwindow==="undefined")return;

try{
//Limitto20favorites
constlimited=favoriteIds.slice(0,20);
localStorage.setItem(STORAGE_KEYS.FAVORITES,JSON.stringify(limited));
}catch(error){
console.error("ErrorsavingfavoritestolocalStorage:",error);
}
},

/**
*Togglefavoritestatusforanaction
*/
toggleFavorite(actionId:string):string[]{
constfavorites=this.getFavorites();
constindex=favorites.indexOf(actionId);

if(index>-1){
//Removefromfavorites
favorites.splice(index,1);
}else{
//Addtofavorites(checklimit)
if(favorites.length<20){
favorites.push(actionId);
}else{
console.warn("Maximumof20favoritesreached");
returnfavorites;
}
}

this.saveFavorites(favorites);
returnfavorites;
},

/**
*GetusagecountsfromlocalStorage
*/
getUsageCounts():Record<string,number>{
if(typeofwindow==="undefined")return{};

try{
conststored=localStorage.getItem(STORAGE_KEYS.USAGE_COUNTS);
returnstored?JSON.parse(stored):{};
}catch(error){
console.error("ErrorreadingusagecountsfromlocalStorage:",error);
return{};
}
},

/**
*SaveusagecountstolocalStorage
*/
saveUsageCounts(counts:Record<string,number>):void{
if(typeofwindow==="undefined")return;

try{
localStorage.setItem(STORAGE_KEYS.USAGE_COUNTS,JSON.stringify(counts));
}catch(error){
console.error("ErrorsavingusagecountstolocalStorage:",error);
}
},

/**
*Incrementusagecountforanaction
*/
incrementUsage(actionId:string):number{
constcounts=this.getUsageCounts();
counts[actionId]=(counts[actionId]||0)+1;
this.saveUsageCounts(counts);
returncounts[actionId];
},

/**
*Getallquickactionswithfavoritesandusagecountsapplied
*/
getQuickActions():QuickAction[]{
constfavorites=this.getFavorites();
constusageCounts=this.getUsageCounts();

returnDEFAULT_QUICK_ACTIONS.map((action)=>({
...action,
isFavorite:favorites.includes(action.id),
usageCount:usageCounts[action.id]||0,
}));
},

/**
*Getfavoriteactions
*/
getFavoriteActions():QuickAction[]{
constactions=this.getQuickActions();
returnactions.filter((action)=>action.isFavorite);
},

/**
*Getrecentactions(sortedbyusagecount,top5)
*/
getRecentActions(limit:number=5):QuickAction[]{
constactions=this.getQuickActions();
returnactions
.filter((action)=>action.usageCount>0)
.sort((a,b)=>b.usageCount-a.usageCount)
.slice(0,limit);
},

/**
*Getactionsbycategory
*/
getActionsByCategory(category:QuickActionCategory):QuickAction[]{
constactions=this.getQuickActions();
returnactions.filter((action)=>action.category===category);
},

/**
*Searchactionsbyquery
*/
searchActions(query:string):QuickAction[]{
if(!query.trim()){
returnthis.getQuickActions();
}

constactions=this.getQuickActions();
constlowerQuery=query.toLowerCase();

returnactions.filter(
(action)=>
action.title.toLowerCase().includes(lowerQuery)||
action.description.toLowerCase().includes(lowerQuery)||
action.template.toLowerCase().includes(lowerQuery)
);
},

/**
*Clearallstorage(fortestingorreset)
*/
clearStorage():void{
if(typeofwindow==="undefined")return;

try{
localStorage.removeItem(STORAGE_KEYS.FAVORITES);
localStorage.removeItem(STORAGE_KEYS.USAGE_COUNTS);
}catch(error){
console.error("Errorclearingquickactionsstorage:",error);
}
},
};
