/**
***REMOVED*******REMOVED***Service***REMOVED***Worker***REMOVED***registration***REMOVED***utility
***REMOVED*******REMOVED***Handles***REMOVED***PWA***REMOVED***service***REMOVED***worker***REMOVED***lifecycle
***REMOVED****/

export***REMOVED***function***REMOVED***registerServiceWorker()***REMOVED***{
***REMOVED******REMOVED***if***REMOVED***(typeof***REMOVED***window***REMOVED***===***REMOVED***"undefined"***REMOVED***||***REMOVED***!("serviceWorker"***REMOVED***in***REMOVED***navigator))***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***console.log("Service***REMOVED***Worker***REMOVED***not***REMOVED***supported");
***REMOVED******REMOVED******REMOVED******REMOVED***return;
***REMOVED******REMOVED***}
***REMOVED******REMOVED***
***REMOVED******REMOVED***//***REMOVED***Only***REMOVED***register***REMOVED***in***REMOVED***production
***REMOVED******REMOVED***if***REMOVED***(process.env.NODE_ENV***REMOVED***!==***REMOVED***"production")***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***console.log("Service***REMOVED***Worker***REMOVED***registration***REMOVED***skipped***REMOVED***in***REMOVED***development");
***REMOVED******REMOVED******REMOVED******REMOVED***return;
***REMOVED******REMOVED***}
***REMOVED******REMOVED***
***REMOVED******REMOVED***window.addEventListener("load",***REMOVED***async***REMOVED***()***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***try***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***registration***REMOVED***=***REMOVED***await***REMOVED***navigator.serviceWorker.register("/sw.js",***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***scope:***REMOVED***"/",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***});
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***console.log("Service***REMOVED***Worker***REMOVED***registered***REMOVED***successfully:",***REMOVED***registration.scope);
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***//***REMOVED***Check***REMOVED***for***REMOVED***updates***REMOVED***periodically
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***setInterval(()***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***registration.update();
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***},***REMOVED***60000);***REMOVED***//***REMOVED***Check***REMOVED***every***REMOVED***minute
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***//***REMOVED***Handle***REMOVED***updates
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***registration.addEventListener("updatefound",***REMOVED***()***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***newWorker***REMOVED***=***REMOVED***registration.installing;
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***if***REMOVED***(newWorker)***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***newWorker.addEventListener("statechange",***REMOVED***()***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***if***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***newWorker.state***REMOVED***===***REMOVED***"installed"***REMOVED***&&
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***navigator.serviceWorker.controller
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***)***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***//***REMOVED***New***REMOVED***service***REMOVED***worker***REMOVED***available
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***console.log("New***REMOVED***service***REMOVED***worker***REMOVED***available");
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***//***REMOVED***Optionally***REMOVED***notify***REMOVED***user***REMOVED***about***REMOVED***update
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***if***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***confirm(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"A***REMOVED***new***REMOVED***version***REMOVED***of***REMOVED***AURA***REMOVED***is***REMOVED***available.***REMOVED***Reload***REMOVED***to***REMOVED***update?"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***)
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***)***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***newWorker.postMessage({***REMOVED***type:***REMOVED***"SKIP_WAITING"***REMOVED***});
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***window.location.reload();
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***});
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***});
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***//***REMOVED***Handle***REMOVED***controller***REMOVED***change
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***navigator.serviceWorker.addEventListener("controllerchange",***REMOVED***()***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***console.log("Service***REMOVED***Worker***REMOVED***controller***REMOVED***changed");
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***});
***REMOVED******REMOVED******REMOVED******REMOVED***}***REMOVED***catch***REMOVED***(error)***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***console.error("Service***REMOVED***Worker***REMOVED***registration***REMOVED***failed:",***REMOVED***error);
***REMOVED******REMOVED******REMOVED******REMOVED***}
***REMOVED******REMOVED***});
}

/**
***REMOVED*******REMOVED***Unregister***REMOVED***service***REMOVED***worker***REMOVED***(for***REMOVED***development/testing)
***REMOVED****/
export***REMOVED***async***REMOVED***function***REMOVED***unregisterServiceWorker()***REMOVED***{
***REMOVED******REMOVED***if***REMOVED***(typeof***REMOVED***window***REMOVED***===***REMOVED***"undefined"***REMOVED***||***REMOVED***!("serviceWorker"***REMOVED***in***REMOVED***navigator))***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***return;
***REMOVED******REMOVED***}
***REMOVED******REMOVED***
***REMOVED******REMOVED***try***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***registrations***REMOVED***=***REMOVED***await***REMOVED***navigator.serviceWorker.getRegistrations();
***REMOVED******REMOVED******REMOVED******REMOVED***for***REMOVED***(const***REMOVED***registration***REMOVED***of***REMOVED***registrations)***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***await***REMOVED***registration.unregister();
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***console.log("Service***REMOVED***Worker***REMOVED***unregistered");
***REMOVED******REMOVED******REMOVED******REMOVED***}
***REMOVED******REMOVED***}***REMOVED***catch***REMOVED***(error)***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***console.error("Service***REMOVED***Worker***REMOVED***unregistration***REMOVED***failed:",***REMOVED***error);
***REMOVED******REMOVED***}
}

/**
***REMOVED*******REMOVED***Clear***REMOVED***all***REMOVED***caches***REMOVED***(for***REMOVED***development/testing)
***REMOVED****/
export***REMOVED***async***REMOVED***function***REMOVED***clearCaches()***REMOVED***{
***REMOVED******REMOVED***if***REMOVED***(typeof***REMOVED***window***REMOVED***===***REMOVED***"undefined"***REMOVED***||***REMOVED***!("caches"***REMOVED***in***REMOVED***window))***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***return;
***REMOVED******REMOVED***}
***REMOVED******REMOVED***
***REMOVED******REMOVED***try***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***cacheNames***REMOVED***=***REMOVED***await***REMOVED***caches.keys();
***REMOVED******REMOVED******REMOVED******REMOVED***await***REMOVED***Promise.all(cacheNames.map((name)***REMOVED***=>***REMOVED***caches.delete(name)));
***REMOVED******REMOVED******REMOVED******REMOVED***console.log("All***REMOVED***caches***REMOVED***cleared");
***REMOVED******REMOVED***}***REMOVED***catch***REMOVED***(error)***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***console.error("Cache***REMOVED***clearing***REMOVED***failed:",***REMOVED***error);
***REMOVED******REMOVED***}
}
