import***REMOVED***{***REMOVED***SWRConfiguration***REMOVED***}***REMOVED***from***REMOVED***"swr";

/**
***REMOVED*******REMOVED***Global***REMOVED***SWR***REMOVED***configuration***REMOVED***for***REMOVED***API***REMOVED***response***REMOVED***caching
***REMOVED*******REMOVED***Implements***REMOVED***stale-while-revalidate***REMOVED***pattern***REMOVED***for***REMOVED***optimal***REMOVED***performance
***REMOVED****/
export***REMOVED***const***REMOVED***swrConfig:***REMOVED***SWRConfiguration***REMOVED***=***REMOVED***{
***REMOVED******REMOVED***//***REMOVED***Revalidate***REMOVED***on***REMOVED***focus***REMOVED***to***REMOVED***ensure***REMOVED***fresh***REMOVED***data***REMOVED***when***REMOVED***user***REMOVED***returns
***REMOVED******REMOVED***revalidateOnFocus:***REMOVED***true,
***REMOVED******REMOVED***
***REMOVED******REMOVED***//***REMOVED***Revalidate***REMOVED***on***REMOVED***reconnect***REMOVED***after***REMOVED***network***REMOVED***issues
***REMOVED******REMOVED***revalidateOnReconnect:***REMOVED***true,
***REMOVED******REMOVED***
***REMOVED******REMOVED***//***REMOVED***Don't***REMOVED***revalidate***REMOVED***on***REMOVED***mount***REMOVED***if***REMOVED***data***REMOVED***is***REMOVED***fresh
***REMOVED******REMOVED***revalidateIfStale:***REMOVED***true,
***REMOVED******REMOVED***
***REMOVED******REMOVED***//***REMOVED***Dedupe***REMOVED***requests***REMOVED***within***REMOVED***2***REMOVED***seconds
***REMOVED******REMOVED***dedupingInterval:***REMOVED***2000,
***REMOVED******REMOVED***
***REMOVED******REMOVED***//***REMOVED***Retry***REMOVED***on***REMOVED***error***REMOVED***with***REMOVED***exponential***REMOVED***backoff
***REMOVED******REMOVED***errorRetryCount:***REMOVED***3,
***REMOVED******REMOVED***errorRetryInterval:***REMOVED***5000,
***REMOVED******REMOVED***
***REMOVED******REMOVED***//***REMOVED***Keep***REMOVED***data***REMOVED***in***REMOVED***cache***REMOVED***for***REMOVED***5***REMOVED***minutes
***REMOVED******REMOVED***focusThrottleInterval:***REMOVED***5000,
***REMOVED******REMOVED***
***REMOVED******REMOVED***//***REMOVED***Default***REMOVED***fetcher***REMOVED***function
***REMOVED******REMOVED***fetcher:***REMOVED***async***REMOVED***(url:***REMOVED***string)***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***res***REMOVED***=***REMOVED***await***REMOVED***fetch(url);
***REMOVED******REMOVED******REMOVED******REMOVED***
***REMOVED******REMOVED******REMOVED******REMOVED***if***REMOVED***(!res.ok)***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***error:***REMOVED***any***REMOVED***=***REMOVED***new***REMOVED***Error("An***REMOVED***error***REMOVED***occurred***REMOVED***while***REMOVED***fetching***REMOVED***the***REMOVED***data.");
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***error.info***REMOVED***=***REMOVED***await***REMOVED***res.json();
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***error.status***REMOVED***=***REMOVED***res.status;
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***throw***REMOVED***error;
***REMOVED******REMOVED******REMOVED******REMOVED***}
***REMOVED******REMOVED******REMOVED******REMOVED***
***REMOVED******REMOVED******REMOVED******REMOVED***return***REMOVED***res.json();
***REMOVED******REMOVED***},
***REMOVED******REMOVED***
***REMOVED******REMOVED***//***REMOVED***Show***REMOVED***loading***REMOVED***state***REMOVED***for***REMOVED***slow***REMOVED***requests
***REMOVED******REMOVED***loadingTimeout:***REMOVED***3000,
***REMOVED******REMOVED***
***REMOVED******REMOVED***//***REMOVED***Callback***REMOVED***when***REMOVED***error***REMOVED***occurs
***REMOVED******REMOVED***onError:***REMOVED***(error,***REMOVED***key)***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***console.error(`SWR***REMOVED***Error***REMOVED***for***REMOVED***${key}:`,***REMOVED***error);
***REMOVED******REMOVED***},
};

/**
***REMOVED*******REMOVED***Cache***REMOVED***configuration***REMOVED***for***REMOVED***different***REMOVED***data***REMOVED***types
***REMOVED****/
export***REMOVED***const***REMOVED***cacheConfig***REMOVED***=***REMOVED***{
***REMOVED******REMOVED***//***REMOVED***History***REMOVED***data***REMOVED***-***REMOVED***cache***REMOVED***for***REMOVED***5***REMOVED***minutes
***REMOVED******REMOVED***history:***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***dedupingInterval:***REMOVED***5000,
***REMOVED******REMOVED******REMOVED******REMOVED***revalidateOnFocus:***REMOVED***true,
***REMOVED******REMOVED******REMOVED******REMOVED***revalidateOnMount:***REMOVED***false,
***REMOVED******REMOVED***},
***REMOVED******REMOVED***
***REMOVED******REMOVED***//***REMOVED***Quick***REMOVED***actions***REMOVED***-***REMOVED***cache***REMOVED***indefinitely***REMOVED***until***REMOVED***manual***REMOVED***revalidation
***REMOVED******REMOVED***quickActions:***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***dedupingInterval:***REMOVED***60000,
***REMOVED******REMOVED******REMOVED******REMOVED***revalidateOnFocus:***REMOVED***false,
***REMOVED******REMOVED******REMOVED******REMOVED***revalidateOnMount:***REMOVED***false,
***REMOVED******REMOVED***},
***REMOVED******REMOVED***
***REMOVED******REMOVED***//***REMOVED***Auth***REMOVED***status***REMOVED***-***REMOVED***check***REMOVED***frequently
***REMOVED******REMOVED***authStatus:***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***dedupingInterval:***REMOVED***1000,
***REMOVED******REMOVED******REMOVED******REMOVED***revalidateOnFocus:***REMOVED***true,
***REMOVED******REMOVED******REMOVED******REMOVED***refreshInterval:***REMOVED***30000,***REMOVED***//***REMOVED***Check***REMOVED***every***REMOVED***30***REMOVED***seconds
***REMOVED******REMOVED***},
***REMOVED******REMOVED***
***REMOVED******REMOVED***//***REMOVED***Profile***REMOVED***data***REMOVED***-***REMOVED***cache***REMOVED***for***REMOVED***10***REMOVED***minutes
***REMOVED******REMOVED***profile:***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***dedupingInterval:***REMOVED***10000,
***REMOVED******REMOVED******REMOVED******REMOVED***revalidateOnFocus:***REMOVED***false,
***REMOVED******REMOVED***},
};
