/**
***REMOVED*******REMOVED***Base***REMOVED***agent***REMOVED***interface***REMOVED***and***REMOVED***types***REMOVED***for***REMOVED***workflow***REMOVED***execution
***REMOVED****/

/**
***REMOVED*******REMOVED***Execution***REMOVED***context***REMOVED***passed***REMOVED***to***REMOVED***agents***REMOVED***during***REMOVED***workflow***REMOVED***execution
***REMOVED****/
export***REMOVED***interface***REMOVED***ExecutionContext***REMOVED***{
***REMOVED******REMOVED***/*****REMOVED***User***REMOVED***ID***REMOVED***who***REMOVED***owns***REMOVED***the***REMOVED***workflow***REMOVED****/
***REMOVED******REMOVED***userId:***REMOVED***string;
***REMOVED******REMOVED***/*****REMOVED***Workflow***REMOVED***ID***REMOVED***being***REMOVED***executed***REMOVED****/
***REMOVED******REMOVED***workflowId:***REMOVED***string;
***REMOVED******REMOVED***/*****REMOVED***Step***REMOVED***ID***REMOVED***being***REMOVED***executed***REMOVED****/
***REMOVED******REMOVED***stepId:***REMOVED***string;
***REMOVED******REMOVED***/*****REMOVED***Google***REMOVED***OAuth***REMOVED***access***REMOVED***token***REMOVED***for***REMOVED***API***REMOVED***authentication***REMOVED****/
***REMOVED******REMOVED***accessToken:***REMOVED***string;
***REMOVED******REMOVED***/*****REMOVED***Action***REMOVED***name***REMOVED***to***REMOVED***execute***REMOVED****/
***REMOVED******REMOVED***action:***REMOVED***string;
***REMOVED******REMOVED***/*****REMOVED***Action-specific***REMOVED***parameters***REMOVED****/
***REMOVED******REMOVED***parameters:***REMOVED***Record<string,***REMOVED***any>;
}

/**
***REMOVED*******REMOVED***Result***REMOVED***returned***REMOVED***by***REMOVED***agent***REMOVED***execution
***REMOVED****/
export***REMOVED***interface***REMOVED***ExecutionResult***REMOVED***{
***REMOVED******REMOVED***/*****REMOVED***Whether***REMOVED***the***REMOVED***execution***REMOVED***was***REMOVED***successful***REMOVED****/
***REMOVED******REMOVED***success:***REMOVED***boolean;
***REMOVED******REMOVED***/*****REMOVED***Output***REMOVED***data***REMOVED***from***REMOVED***the***REMOVED***execution***REMOVED***(if***REMOVED***successful)***REMOVED****/
***REMOVED******REMOVED***output?:***REMOVED***any;
***REMOVED******REMOVED***/*****REMOVED***Error***REMOVED***message***REMOVED***(if***REMOVED***failed)***REMOVED****/
***REMOVED******REMOVED***error?:***REMOVED***string;
}

/**
***REMOVED*******REMOVED***Base***REMOVED***agent***REMOVED***interface***REMOVED***that***REMOVED***all***REMOVED***specialized***REMOVED***agents***REMOVED***must***REMOVED***implement
***REMOVED****/
export***REMOVED***interface***REMOVED***Agent***REMOVED***{
***REMOVED******REMOVED***/*****REMOVED***Agent***REMOVED***name***REMOVED***(e.g.,***REMOVED***"EmailAgent",***REMOVED***"DriveAgent")***REMOVED****/
***REMOVED******REMOVED***name:***REMOVED***string;
***REMOVED******REMOVED***/*****REMOVED***Execute***REMOVED***an***REMOVED***action***REMOVED***with***REMOVED***the***REMOVED***given***REMOVED***context***REMOVED****/
***REMOVED******REMOVED***execute(context:***REMOVED***ExecutionContext):***REMOVED***Promise<ExecutionResult>;
}
