/**
*Baseagentinterfaceandtypesforworkflowexecution
*/

/**
*Executioncontextpassedtoagentsduringworkflowexecution
*/
exportinterfaceExecutionContext{
/**UserIDwhoownstheworkflow*/
userId:string;
/**WorkflowIDbeingexecuted*/
workflowId:string;
/**StepIDbeingexecuted*/
stepId:string;
/**GoogleOAuthaccesstokenforAPIauthentication*/
accessToken:string;
/**Actionnametoexecute*/
action:string;
/**Action-specificparameters*/
parameters:Record<string,any>;
}

/**
*Resultreturnedbyagentexecution
*/
exportinterfaceExecutionResult{
/**Whethertheexecutionwassuccessful*/
success:boolean;
/**Outputdatafromtheexecution(ifsuccessful)*/
output?:any;
/**Errormessage(iffailed)*/
error?:string;
}

/**
*Baseagentinterfacethatallspecializedagentsmustimplement
*/
exportinterfaceAgent{
/**Agentname(e.g.,"EmailAgent","DriveAgent")*/
name:string;
/**Executeanactionwiththegivencontext*/
execute(context:ExecutionContext):Promise<ExecutionResult>;
}
