"useclient";

import{useSupabaseAuth}from"@/contexts/SupabaseAuthContext";
import{useRouter}from"next/navigation";
import{useEffect}from"react";
import{DashboardLayout}from"@/components/layout/DashboardLayout";
import{Tabs,TabsContent,TabsList,TabsTrigger}from"@/components/ui/tabs";
import{Card,CardContent,CardDescription,CardHeader,CardTitle}from"@/components/ui/card";
import{OAuthStatus}from"@/components/settings/OAuthStatus";
import{ScopesList}from"@/components/settings/ScopesList";
import{DisconnectButton}from"@/components/settings/DisconnectButton";

exportdefaultfunctionSettingsPage(){
const{user,isLoading}=useSupabaseAuth();
constrouter=useRouter();

useEffect(()=>{
//Redirecttologinifnotauthenticated
if(!isLoading&&!user){
router.push("/login");
}
},[user,isLoading,router]);

if(isLoading){
return(
<divclassName="flexmin-h-screenitems-centerjustify-center">
<divclassName="text-center">
<divclassName="mb-4h-8w-8animate-spinrounded-fullborder-4border-gray-300border-t-blue-600mx-auto"></div>
<pclassName="text-gray-600">Loading...</p>
</div>
</div>
);
}

if(!user){
returnnull;//Willredirecttologin
}

return(
<DashboardLayout>
<divclassName="space-y-6">
<div>
<h1className="text-3xlfont-boldtracking-tight">Settings</h1>
<pclassName="text-muted-foregroundmt-2">
Manageyouraccountsettingsandpreferences
</p>
</div>

<TabsdefaultValue="oauth"className="space-y-4">
<TabsList>
<TabsTriggervalue="oauth">OAuth&Permissions</TabsTrigger>
<TabsTriggervalue="preferences">Preferences</TabsTrigger>
<TabsTriggervalue="about">About</TabsTrigger>
</TabsList>

<TabsContentvalue="oauth"className="space-y-4">
<Card>
<CardHeader>
<CardTitle>GoogleAccountConnection</CardTitle>
<CardDescription>
ManageyourGoogleaccountconnectionandOAuthpermissions
</CardDescription>
</CardHeader>
<CardContentclassName="space-y-6">
<OAuthStatus/>
<ScopesList/>
<divclassName="pt-4border-t">
<DisconnectButton/>
</div>
</CardContent>
</Card>
</TabsContent>

<TabsContentvalue="preferences"className="space-y-4">
<Card>
<CardHeader>
<CardTitle>UserPreferences</CardTitle>
<CardDescription>
CustomizeyourAURAexperience
</CardDescription>
</CardHeader>
<CardContent>
<pclassName="text-smtext-muted-foreground">
Preferencessettingscomingsoon...
</p>
</CardContent>
</Card>
</TabsContent>

<TabsContentvalue="about"className="space-y-4">
<Card>
<CardHeader>
<CardTitle>AboutAURA</CardTitle>
<CardDescription>
Versionandsysteminformation
</CardDescription>
</CardHeader>
<CardContent>
<divclassName="space-y-2text-sm">
<divclassName="flexjustify-betweenpy-2border-b">
<spanclassName="font-medium">Version</span>
<spanclassName="text-muted-foreground">1.0.0</span>
</div>
<divclassName="flexjustify-betweenpy-2border-b">
<spanclassName="font-medium">UserID</span>
<spanclassName="text-muted-foreground">{user.id}</span>
</div>
<divclassName="flexjustify-betweenpy-2">
<spanclassName="font-medium">Email</span>
<spanclassName="text-muted-foreground">{user.email}</span>
</div>
</div>
</CardContent>
</Card>
</TabsContent>
</Tabs>
</div>
</DashboardLayout>
);
}
