import***REMOVED***useSWR***REMOVED***from***REMOVED***"swr";
import***REMOVED***useSWRInfinite***REMOVED***from***REMOVED***"swr/infinite";
import***REMOVED***{***REMOVED***cacheConfig***REMOVED***}***REMOVED***from***REMOVED***"@/lib/swr-config";
import***REMOVED***type***REMOVED***{***REMOVED***HistoryItem,***REMOVED***QuickAction,***REMOVED***AuthStatus***REMOVED***}***REMOVED***from***REMOVED***"@/types";

/**
***REMOVED*******REMOVED***Hook***REMOVED***for***REMOVED***fetching***REMOVED***history***REMOVED***with***REMOVED***pagination***REMOVED***and***REMOVED***caching
***REMOVED****/
export***REMOVED***function***REMOVED***useHistoryData(filters?:***REMOVED***{
***REMOVED******REMOVED***dateFrom?:***REMOVED***Date;
***REMOVED******REMOVED***dateTo?:***REMOVED***Date;
***REMOVED******REMOVED***status?:***REMOVED***string;
***REMOVED******REMOVED***agentType?:***REMOVED***string;
***REMOVED******REMOVED***searchQuery?:***REMOVED***string;
})***REMOVED***{
***REMOVED******REMOVED***const***REMOVED***getKey***REMOVED***=***REMOVED***(pageIndex:***REMOVED***number,***REMOVED***previousPageData:***REMOVED***any)***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***//***REMOVED***Reached***REMOVED***the***REMOVED***end
***REMOVED******REMOVED******REMOVED******REMOVED***if***REMOVED***(previousPageData***REMOVED***&&***REMOVED***!previousPageData.hasMore)***REMOVED***return***REMOVED***null;
***REMOVED******REMOVED******REMOVED******REMOVED***
***REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***params***REMOVED***=***REMOVED***new***REMOVED***URLSearchParams({
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***page:***REMOVED***(pageIndex***REMOVED***+***REMOVED***1).toString(),
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***limit:***REMOVED***"20",
***REMOVED******REMOVED******REMOVED******REMOVED***});
***REMOVED******REMOVED******REMOVED******REMOVED***
***REMOVED******REMOVED******REMOVED******REMOVED***if***REMOVED***(filters?.dateFrom)***REMOVED***params.append("dateFrom",***REMOVED***filters.dateFrom.toISOString());
***REMOVED******REMOVED******REMOVED******REMOVED***if***REMOVED***(filters?.dateTo)***REMOVED***params.append("dateTo",***REMOVED***filters.dateTo.toISOString());
***REMOVED******REMOVED******REMOVED******REMOVED***if***REMOVED***(filters?.status)***REMOVED***params.append("status",***REMOVED***filters.status);
***REMOVED******REMOVED******REMOVED******REMOVED***if***REMOVED***(filters?.agentType)***REMOVED***params.append("agentType",***REMOVED***filters.agentType);
***REMOVED******REMOVED******REMOVED******REMOVED***if***REMOVED***(filters?.searchQuery)***REMOVED***params.append("search",***REMOVED***filters.searchQuery);
***REMOVED******REMOVED******REMOVED******REMOVED***
***REMOVED******REMOVED******REMOVED******REMOVED***return***REMOVED***`/api/history?${params.toString()}`;
***REMOVED******REMOVED***};
***REMOVED******REMOVED***
***REMOVED******REMOVED***const***REMOVED***{***REMOVED***data,***REMOVED***error,***REMOVED***size,***REMOVED***setSize,***REMOVED***isLoading,***REMOVED***isValidating,***REMOVED***mutate***REMOVED***}***REMOVED***=***REMOVED***useSWRInfinite(
***REMOVED******REMOVED******REMOVED******REMOVED***getKey,
***REMOVED******REMOVED******REMOVED******REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***...cacheConfig.history,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***revalidateFirstPage:***REMOVED***false,
***REMOVED******REMOVED******REMOVED******REMOVED***}
***REMOVED******REMOVED***);
***REMOVED******REMOVED***
***REMOVED******REMOVED***const***REMOVED***items:***REMOVED***HistoryItem[]***REMOVED***=***REMOVED***data
***REMOVED******REMOVED******REMOVED******REMOVED***?***REMOVED***data.flatMap((page)***REMOVED***=>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***page.items.map((item:***REMOVED***any)***REMOVED***=>***REMOVED***({
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***...item,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***timestamp:***REMOVED***new***REMOVED***Date(item.timestamp),
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***}))
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***)
***REMOVED******REMOVED******REMOVED******REMOVED***:***REMOVED***[];
***REMOVED******REMOVED***
***REMOVED******REMOVED***const***REMOVED***hasMore***REMOVED***=***REMOVED***data***REMOVED***?***REMOVED***data[data.length***REMOVED***-***REMOVED***1]?.hasMore***REMOVED***:***REMOVED***false;
***REMOVED******REMOVED***
***REMOVED******REMOVED***return***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***items,
***REMOVED******REMOVED******REMOVED******REMOVED***error,
***REMOVED******REMOVED******REMOVED******REMOVED***isLoading,
***REMOVED******REMOVED******REMOVED******REMOVED***isValidating,
***REMOVED******REMOVED******REMOVED******REMOVED***hasMore,
***REMOVED******REMOVED******REMOVED******REMOVED***loadMore:***REMOVED***()***REMOVED***=>***REMOVED***setSize(size***REMOVED***+***REMOVED***1),
***REMOVED******REMOVED******REMOVED******REMOVED***refresh:***REMOVED***()***REMOVED***=>***REMOVED***mutate(),
***REMOVED******REMOVED***};
}

/**
***REMOVED*******REMOVED***Hook***REMOVED***for***REMOVED***fetching***REMOVED***quick***REMOVED***actions***REMOVED***with***REMOVED***caching
***REMOVED****/
export***REMOVED***function***REMOVED***useQuickActions()***REMOVED***{
***REMOVED******REMOVED***const***REMOVED***{***REMOVED***data,***REMOVED***error,***REMOVED***isLoading,***REMOVED***mutate***REMOVED***}***REMOVED***=***REMOVED***useSWR<QuickAction[]>(
***REMOVED******REMOVED******REMOVED******REMOVED***"/api/quick-actions",
***REMOVED******REMOVED******REMOVED******REMOVED***cacheConfig.quickActions
***REMOVED******REMOVED***);
***REMOVED******REMOVED***
***REMOVED******REMOVED***return***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***actions:***REMOVED***data***REMOVED***||***REMOVED***[],
***REMOVED******REMOVED******REMOVED******REMOVED***error,
***REMOVED******REMOVED******REMOVED******REMOVED***isLoading,
***REMOVED******REMOVED******REMOVED******REMOVED***refresh:***REMOVED***()***REMOVED***=>***REMOVED***mutate(),
***REMOVED******REMOVED***};
}

/**
***REMOVED*******REMOVED***Hook***REMOVED***for***REMOVED***fetching***REMOVED***auth***REMOVED***status***REMOVED***with***REMOVED***frequent***REMOVED***revalidation
***REMOVED****/
export***REMOVED***function***REMOVED***useAuthStatus()***REMOVED***{
***REMOVED******REMOVED***const***REMOVED***{***REMOVED***data,***REMOVED***error,***REMOVED***isLoading,***REMOVED***mutate***REMOVED***}***REMOVED***=***REMOVED***useSWR<AuthStatus>(
***REMOVED******REMOVED******REMOVED******REMOVED***"/api/auth/status",
***REMOVED******REMOVED******REMOVED******REMOVED***cacheConfig.authStatus
***REMOVED******REMOVED***);
***REMOVED******REMOVED***
***REMOVED******REMOVED***return***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***authStatus:***REMOVED***data,
***REMOVED******REMOVED******REMOVED******REMOVED***error,
***REMOVED******REMOVED******REMOVED******REMOVED***isLoading,
***REMOVED******REMOVED******REMOVED******REMOVED***refresh:***REMOVED***()***REMOVED***=>***REMOVED***mutate(),
***REMOVED******REMOVED***};
}

/**
***REMOVED*******REMOVED***Hook***REMOVED***for***REMOVED***fetching***REMOVED***user***REMOVED***profile***REMOVED***with***REMOVED***caching
***REMOVED****/
export***REMOVED***function***REMOVED***useProfile()***REMOVED***{
***REMOVED******REMOVED***const***REMOVED***{***REMOVED***data,***REMOVED***error,***REMOVED***isLoading,***REMOVED***mutate***REMOVED***}***REMOVED***=***REMOVED***useSWR(
***REMOVED******REMOVED******REMOVED******REMOVED***"/api/profile",
***REMOVED******REMOVED******REMOVED******REMOVED***cacheConfig.profile
***REMOVED******REMOVED***);
***REMOVED******REMOVED***
***REMOVED******REMOVED***return***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***profile:***REMOVED***data,
***REMOVED******REMOVED******REMOVED******REMOVED***error,
***REMOVED******REMOVED******REMOVED******REMOVED***isLoading,
***REMOVED******REMOVED******REMOVED******REMOVED***refresh:***REMOVED***()***REMOVED***=>***REMOVED***mutate(),
***REMOVED******REMOVED***};
}

/**
***REMOVED*******REMOVED***Hook***REMOVED***for***REMOVED***fetching***REMOVED***task***REMOVED***detail***REMOVED***with***REMOVED***caching
***REMOVED****/
export***REMOVED***function***REMOVED***useTaskDetail(taskId:***REMOVED***string***REMOVED***|***REMOVED***null)***REMOVED***{
***REMOVED******REMOVED***const***REMOVED***{***REMOVED***data,***REMOVED***error,***REMOVED***isLoading,***REMOVED***mutate***REMOVED***}***REMOVED***=***REMOVED***useSWR(
***REMOVED******REMOVED******REMOVED******REMOVED***taskId***REMOVED***?***REMOVED***`/api/history/${taskId}`***REMOVED***:***REMOVED***null,
***REMOVED******REMOVED******REMOVED******REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***dedupingInterval:***REMOVED***10000,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***revalidateOnFocus:***REMOVED***false,
***REMOVED******REMOVED******REMOVED******REMOVED***}
***REMOVED******REMOVED***);
***REMOVED******REMOVED***
***REMOVED******REMOVED***//***REMOVED***Convert***REMOVED***date***REMOVED***strings***REMOVED***to***REMOVED***Date***REMOVED***objects
***REMOVED******REMOVED***const***REMOVED***taskDetail***REMOVED***=***REMOVED***data
***REMOVED******REMOVED******REMOVED******REMOVED***?***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***...data,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***createdAt:***REMOVED***new***REMOVED***Date(data.createdAt),
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***updatedAt:***REMOVED***new***REMOVED***Date(data.updatedAt),
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***workflowState:***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***...data.workflowState,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***startTime:***REMOVED***data.workflowState.startTime
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***?***REMOVED***new***REMOVED***Date(data.workflowState.startTime)
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***:***REMOVED***undefined,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***endTime:***REMOVED***data.workflowState.endTime
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***?***REMOVED***new***REMOVED***Date(data.workflowState.endTime)
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***:***REMOVED***undefined,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***steps:***REMOVED***data.workflowState.steps.map((step:***REMOVED***any)***REMOVED***=>***REMOVED***({
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***...step,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***startTime:***REMOVED***step.startTime***REMOVED***?***REMOVED***new***REMOVED***Date(step.startTime)***REMOVED***:***REMOVED***undefined,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***endTime:***REMOVED***step.endTime***REMOVED***?***REMOVED***new***REMOVED***Date(step.endTime)***REMOVED***:***REMOVED***undefined,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***})),
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***},
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***}
***REMOVED******REMOVED******REMOVED******REMOVED***:***REMOVED***null;
***REMOVED******REMOVED***
***REMOVED******REMOVED***return***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***taskDetail,
***REMOVED******REMOVED******REMOVED******REMOVED***error,
***REMOVED******REMOVED******REMOVED******REMOVED***isLoading,
***REMOVED******REMOVED******REMOVED******REMOVED***refresh:***REMOVED***()***REMOVED***=>***REMOVED***mutate(),
***REMOVED******REMOVED***};
}
