"use***REMOVED***client";

import***REMOVED***{
***REMOVED******REMOVED***Dialog,
***REMOVED******REMOVED***DialogContent,
***REMOVED******REMOVED***DialogDescription,
***REMOVED******REMOVED***DialogHeader,
***REMOVED******REMOVED***DialogTitle,
}***REMOVED***from***REMOVED***"@/components/ui/dialog";
import***REMOVED***{***REMOVED***Keyboard***REMOVED***}***REMOVED***from***REMOVED***"lucide-react";

interface***REMOVED***KeyboardShortcut***REMOVED***{
***REMOVED******REMOVED***keys:***REMOVED***string[];
***REMOVED******REMOVED***description:***REMOVED***string;
***REMOVED******REMOVED***category:***REMOVED***string;
}

interface***REMOVED***KeyboardShortcutsModalProps***REMOVED***{
***REMOVED******REMOVED***open:***REMOVED***boolean;
***REMOVED******REMOVED***onOpenChange:***REMOVED***(open:***REMOVED***boolean)***REMOVED***=>***REMOVED***void;
}

const***REMOVED***SHORTCUTS:***REMOVED***KeyboardShortcut[]***REMOVED***=***REMOVED***[
***REMOVED******REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***keys:***REMOVED***["Ctrl",***REMOVED***"Enter"],
***REMOVED******REMOVED******REMOVED******REMOVED***description:***REMOVED***"Submit***REMOVED***command",
***REMOVED******REMOVED******REMOVED******REMOVED***category:***REMOVED***"Command***REMOVED***Input",
***REMOVED******REMOVED***},
***REMOVED******REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***keys:***REMOVED***["Ctrl",***REMOVED***"K"],
***REMOVED******REMOVED******REMOVED******REMOVED***description:***REMOVED***"Focus***REMOVED***command***REMOVED***input",
***REMOVED******REMOVED******REMOVED******REMOVED***category:***REMOVED***"Navigation",
***REMOVED******REMOVED***},
***REMOVED******REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***keys:***REMOVED***["Esc"],
***REMOVED******REMOVED******REMOVED******REMOVED***description:***REMOVED***"Close***REMOVED***modals***REMOVED***and***REMOVED***dialogs",
***REMOVED******REMOVED******REMOVED******REMOVED***category:***REMOVED***"Navigation",
***REMOVED******REMOVED***},
***REMOVED******REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***keys:***REMOVED***["Tab"],
***REMOVED******REMOVED******REMOVED******REMOVED***description:***REMOVED***"Navigate***REMOVED***between***REMOVED***elements",
***REMOVED******REMOVED******REMOVED******REMOVED***category:***REMOVED***"Navigation",
***REMOVED******REMOVED***},
***REMOVED******REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***keys:***REMOVED***["Shift",***REMOVED***"Tab"],
***REMOVED******REMOVED******REMOVED******REMOVED***description:***REMOVED***"Navigate***REMOVED***backwards",
***REMOVED******REMOVED******REMOVED******REMOVED***category:***REMOVED***"Navigation",
***REMOVED******REMOVED***},
];

function***REMOVED***KeyBadge({***REMOVED***keyName***REMOVED***}:***REMOVED***{***REMOVED***keyName:***REMOVED***string***REMOVED***})***REMOVED***{
***REMOVED******REMOVED***const***REMOVED***isMac***REMOVED***=***REMOVED***typeof***REMOVED***navigator***REMOVED***!==***REMOVED***"undefined"***REMOVED***&&***REMOVED***navigator.platform.includes("Mac");
***REMOVED******REMOVED***
***REMOVED******REMOVED***//***REMOVED***Replace***REMOVED***key***REMOVED***names***REMOVED***for***REMOVED***Mac
***REMOVED******REMOVED***const***REMOVED***displayKey***REMOVED***=***REMOVED***isMac
***REMOVED******REMOVED******REMOVED******REMOVED***?***REMOVED***keyName.replace("Ctrl",***REMOVED***"⌘").replace("Alt",***REMOVED***"⌥").replace("Shift",***REMOVED***"⇧")
***REMOVED******REMOVED******REMOVED******REMOVED***:***REMOVED***keyName;

***REMOVED******REMOVED***return***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED***<kbd***REMOVED***className="px-2***REMOVED***py-1***REMOVED***text-xs***REMOVED***font-semibold***REMOVED***text-foreground***REMOVED***bg-muted***REMOVED***border***REMOVED***border-border***REMOVED***rounded">
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{displayKey}
***REMOVED******REMOVED******REMOVED******REMOVED***</kbd>
***REMOVED******REMOVED***);
}

export***REMOVED***function***REMOVED***KeyboardShortcutsModal({***REMOVED***open,***REMOVED***onOpenChange***REMOVED***}:***REMOVED***KeyboardShortcutsModalProps)***REMOVED***{
***REMOVED******REMOVED***//***REMOVED***Group***REMOVED***shortcuts***REMOVED***by***REMOVED***category
***REMOVED******REMOVED***const***REMOVED***shortcutsByCategory***REMOVED***=***REMOVED***SHORTCUTS.reduce((acc,***REMOVED***shortcut)***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***if***REMOVED***(!acc[shortcut.category])***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***acc[shortcut.category]***REMOVED***=***REMOVED***[];
***REMOVED******REMOVED******REMOVED******REMOVED***}
***REMOVED******REMOVED******REMOVED******REMOVED***acc[shortcut.category].push(shortcut);
***REMOVED******REMOVED******REMOVED******REMOVED***return***REMOVED***acc;
***REMOVED******REMOVED***},***REMOVED***{}***REMOVED***as***REMOVED***Record<string,***REMOVED***KeyboardShortcut[]>);

***REMOVED******REMOVED***const***REMOVED***categories***REMOVED***=***REMOVED***Object.keys(shortcutsByCategory);

***REMOVED******REMOVED***return***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED***<Dialog***REMOVED***open={open}***REMOVED***onOpenChange={onOpenChange}>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<DialogContent***REMOVED***
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className="max-w-2xl***REMOVED***max-h-[80vh]***REMOVED***overflow-y-auto"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***aria-describedby="keyboard-shortcuts-description"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<DialogHeader>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<DialogTitle***REMOVED***className="flex***REMOVED***items-center***REMOVED***gap-2">
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<Keyboard***REMOVED***className="size-5"***REMOVED***aria-hidden="true"***REMOVED***/>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***Keyboard***REMOVED***Shortcuts
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</DialogTitle>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<DialogDescription***REMOVED***id="keyboard-shortcuts-description">
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***Use***REMOVED***these***REMOVED***keyboard***REMOVED***shortcuts***REMOVED***to***REMOVED***navigate***REMOVED***and***REMOVED***interact***REMOVED***with***REMOVED***AURA***REMOVED***more***REMOVED***efficiently
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</DialogDescription>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</DialogHeader>

***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<div***REMOVED***className="space-y-6***REMOVED***mt-4">
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{categories.map((category)***REMOVED***=>***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<div***REMOVED***key={category}>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<h3***REMOVED***className="text-sm***REMOVED***font-semibold***REMOVED***text-muted-foreground***REMOVED***uppercase***REMOVED***mb-3">
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{category}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</h3>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<div***REMOVED***className="space-y-2">
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{shortcutsByCategory[category].map((shortcut,***REMOVED***index)***REMOVED***=>***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<div
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***key={index}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className="flex***REMOVED***items-center***REMOVED***justify-between***REMOVED***py-2***REMOVED***px-3***REMOVED***rounded-md***REMOVED***hover:bg-muted/50***REMOVED***transition-colors"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<span***REMOVED***className="text-sm">{shortcut.description}</span>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<div***REMOVED***className="flex***REMOVED***items-center***REMOVED***gap-1">
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{shortcut.keys.map((key,***REMOVED***keyIndex)***REMOVED***=>***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<span***REMOVED***key={keyIndex}***REMOVED***className="flex***REMOVED***items-center***REMOVED***gap-1">
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<KeyBadge***REMOVED***keyName={key}***REMOVED***/>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{keyIndex***REMOVED***<***REMOVED***shortcut.keys.length***REMOVED***-***REMOVED***1***REMOVED***&&***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<span***REMOVED***className="text-muted-foreground***REMOVED***text-xs">+</span>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***)}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</span>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***))}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</div>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</div>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***))}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</div>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</div>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***))}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</div>

***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<div***REMOVED***className="mt-6***REMOVED***pt-4***REMOVED***border-t">
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<p***REMOVED***className="text-xs***REMOVED***text-muted-foreground***REMOVED***text-center">
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***Press{"***REMOVED***"}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<kbd***REMOVED***className="px-1.5***REMOVED***py-0.5***REMOVED***text-[10px]***REMOVED***font-semibold***REMOVED***bg-muted***REMOVED***border***REMOVED***rounded">
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***?
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</kbd>{"***REMOVED***"}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***to***REMOVED***open***REMOVED***this***REMOVED***dialog***REMOVED***anytime
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</p>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</div>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</DialogContent>
***REMOVED******REMOVED******REMOVED******REMOVED***</Dialog>
***REMOVED******REMOVED***);
}
