"useclient";

import{
Dialog,
DialogContent,
DialogDescription,
DialogHeader,
DialogTitle,
}from"@/components/ui/dialog";
import{Keyboard}from"lucide-react";

interfaceKeyboardShortcut{
keys:string[];
description:string;
category:string;
}

interfaceKeyboardShortcutsModalProps{
open:boolean;
onOpenChange:(open:boolean)=>void;
}

constSHORTCUTS:KeyboardShortcut[]=[
{
keys:["Ctrl","Enter"],
description:"Submitcommand",
category:"CommandInput",
},
{
keys:["Ctrl","K"],
description:"Focuscommandinput",
category:"Navigation",
},
{
keys:["Esc"],
description:"Closemodalsanddialogs",
category:"Navigation",
},
{
keys:["Tab"],
description:"Navigatebetweenelements",
category:"Navigation",
},
{
keys:["Shift","Tab"],
description:"Navigatebackwards",
category:"Navigation",
},
];

functionKeyBadge({keyName}:{keyName:string}){
constisMac=typeofnavigator!=="undefined"&&navigator.platform.includes("Mac");

//ReplacekeynamesforMac
constdisplayKey=isMac
?keyName.replace("Ctrl","⌘").replace("Alt","⌥").replace("Shift","⇧")
:keyName;

return(
<kbdclassName="px-2py-1text-xsfont-semiboldtext-foregroundbg-mutedborderborder-borderrounded">
{displayKey}
</kbd>
);
}

exportfunctionKeyboardShortcutsModal({open,onOpenChange}:KeyboardShortcutsModalProps){
//Groupshortcutsbycategory
constshortcutsByCategory=SHORTCUTS.reduce((acc,shortcut)=>{
if(!acc[shortcut.category]){
acc[shortcut.category]=[];
}
acc[shortcut.category].push(shortcut);
returnacc;
},{}asRecord<string,KeyboardShortcut[]>);

constcategories=Object.keys(shortcutsByCategory);

return(
<Dialogopen={open}onOpenChange={onOpenChange}>
<DialogContent
className="max-w-2xlmax-h-[80vh]overflow-y-auto"
aria-describedby="keyboard-shortcuts-description"
>
<DialogHeader>
<DialogTitleclassName="flexitems-centergap-2">
<KeyboardclassName="size-5"aria-hidden="true"/>
KeyboardShortcuts
</DialogTitle>
<DialogDescriptionid="keyboard-shortcuts-description">
UsethesekeyboardshortcutstonavigateandinteractwithAURAmoreefficiently
</DialogDescription>
</DialogHeader>

<divclassName="space-y-6mt-4">
{categories.map((category)=>(
<divkey={category}>
<h3className="text-smfont-semiboldtext-muted-foregrounduppercasemb-3">
{category}
</h3>
<divclassName="space-y-2">
{shortcutsByCategory[category].map((shortcut,index)=>(
<div
key={index}
className="flexitems-centerjustify-betweenpy-2px-3rounded-mdhover:bg-muted/50transition-colors"
>
<spanclassName="text-sm">{shortcut.description}</span>
<divclassName="flexitems-centergap-1">
{shortcut.keys.map((key,keyIndex)=>(
<spankey={keyIndex}className="flexitems-centergap-1">
<KeyBadgekeyName={key}/>
{keyIndex<shortcut.keys.length-1&&(
<spanclassName="text-muted-foregroundtext-xs">+</span>
)}
</span>
))}
</div>
</div>
))}
</div>
</div>
))}
</div>

<divclassName="mt-6pt-4border-t">
<pclassName="text-xstext-muted-foregroundtext-center">
Press{""}
<kbdclassName="px-1.5py-0.5text-[10px]font-semiboldbg-mutedborderrounded">
?
</kbd>{""}
toopenthisdialoganytime
</p>
</div>
</DialogContent>
</Dialog>
);
}
