"use***REMOVED***client";

import***REMOVED***{***REMOVED***useState***REMOVED***}***REMOVED***from***REMOVED***"react";
import***REMOVED***{
***REMOVED******REMOVED***DropdownMenu,
***REMOVED******REMOVED***DropdownMenuContent,
***REMOVED******REMOVED***DropdownMenuGroup,
***REMOVED******REMOVED***DropdownMenuItem,
***REMOVED******REMOVED***DropdownMenuLabel,
***REMOVED******REMOVED***DropdownMenuSeparator,
***REMOVED******REMOVED***DropdownMenuTrigger,
}***REMOVED***from***REMOVED***"@/components/ui/dropdown-menu";
import***REMOVED***{***REMOVED***Button***REMOVED***}***REMOVED***from***REMOVED***"@/components/ui/button";
import***REMOVED***{***REMOVED***ChevronDown,***REMOVED***Mail,***REMOVED***FileText,***REMOVED***Calendar,***REMOVED***BarChart,***REMOVED***Sparkles***REMOVED***}***REMOVED***from***REMOVED***"lucide-react";
import***REMOVED***{***REMOVED***QuickActionCategory***REMOVED***}***REMOVED***from***REMOVED***"@/types";

export***REMOVED***interface***REMOVED***PromptTemplate***REMOVED***{
***REMOVED******REMOVED***id:***REMOVED***string;
***REMOVED******REMOVED***title:***REMOVED***string;
***REMOVED******REMOVED***description:***REMOVED***string;
***REMOVED******REMOVED***template:***REMOVED***string;
***REMOVED******REMOVED***category:***REMOVED***QuickActionCategory;
}

interface***REMOVED***PromptTemplatesProps***REMOVED***{
***REMOVED******REMOVED***onSelect:***REMOVED***(template:***REMOVED***string)***REMOVED***=>***REMOVED***void;
***REMOVED******REMOVED***disabled?:***REMOVED***boolean;
}

//***REMOVED***Default***REMOVED***prompt***REMOVED***templates***REMOVED***organized***REMOVED***by***REMOVED***category
const***REMOVED***DEFAULT_TEMPLATES:***REMOVED***PromptTemplate[]***REMOVED***=***REMOVED***[
***REMOVED******REMOVED***//***REMOVED***Email***REMOVED***templates
***REMOVED******REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***id:***REMOVED***"email-summary",
***REMOVED******REMOVED******REMOVED******REMOVED***title:***REMOVED***"Summarize***REMOVED***Recent***REMOVED***Emails",
***REMOVED******REMOVED******REMOVED******REMOVED***description:***REMOVED***"Get***REMOVED***a***REMOVED***summary***REMOVED***of***REMOVED***unread***REMOVED***emails***REMOVED***from***REMOVED***the***REMOVED***last***REMOVED***24***REMOVED***hours",
***REMOVED******REMOVED******REMOVED******REMOVED***template:***REMOVED***"Summarize***REMOVED***all***REMOVED***unread***REMOVED***emails***REMOVED***from***REMOVED***the***REMOVED***last***REMOVED***24***REMOVED***hours***REMOVED***and***REMOVED***highlight***REMOVED***any***REMOVED***urgent***REMOVED***items",
***REMOVED******REMOVED******REMOVED******REMOVED***category:***REMOVED***"email",
***REMOVED******REMOVED***},
***REMOVED******REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***id:***REMOVED***"email-draft",
***REMOVED******REMOVED******REMOVED******REMOVED***title:***REMOVED***"Draft***REMOVED***Professional***REMOVED***Email",
***REMOVED******REMOVED******REMOVED******REMOVED***description:***REMOVED***"Create***REMOVED***a***REMOVED***professional***REMOVED***email***REMOVED***draft",
***REMOVED******REMOVED******REMOVED******REMOVED***template:***REMOVED***"Draft***REMOVED***a***REMOVED***professional***REMOVED***email***REMOVED***to***REMOVED***[recipient]***REMOVED***about***REMOVED***[topic]***REMOVED***with***REMOVED***a***REMOVED***[tone]***REMOVED***tone",
***REMOVED******REMOVED******REMOVED******REMOVED***category:***REMOVED***"email",
***REMOVED******REMOVED***},
***REMOVED******REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***id:***REMOVED***"email-follow-up",
***REMOVED******REMOVED******REMOVED******REMOVED***title:***REMOVED***"Follow-up***REMOVED***Email",
***REMOVED******REMOVED******REMOVED******REMOVED***description:***REMOVED***"Create***REMOVED***a***REMOVED***follow-up***REMOVED***email***REMOVED***for***REMOVED***pending***REMOVED***responses",
***REMOVED******REMOVED******REMOVED******REMOVED***template:***REMOVED***"Find***REMOVED***emails***REMOVED***I***REMOVED***sent***REMOVED***in***REMOVED***the***REMOVED***last***REMOVED***week***REMOVED***that***REMOVED***haven't***REMOVED***received***REMOVED***a***REMOVED***response***REMOVED***and***REMOVED***draft***REMOVED***polite***REMOVED***follow-ups",
***REMOVED******REMOVED******REMOVED******REMOVED***category:***REMOVED***"email",
***REMOVED******REMOVED***},
***REMOVED******REMOVED***
***REMOVED******REMOVED***//***REMOVED***Document***REMOVED***templates
***REMOVED******REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***id:***REMOVED***"doc-meeting-notes",
***REMOVED******REMOVED******REMOVED******REMOVED***title:***REMOVED***"Create***REMOVED***Meeting***REMOVED***Notes",
***REMOVED******REMOVED******REMOVED******REMOVED***description:***REMOVED***"Generate***REMOVED***structured***REMOVED***meeting***REMOVED***notes***REMOVED***document",
***REMOVED******REMOVED******REMOVED******REMOVED***template:***REMOVED***"Create***REMOVED***a***REMOVED***meeting***REMOVED***notes***REMOVED***document***REMOVED***for***REMOVED***[meeting***REMOVED***topic]***REMOVED***with***REMOVED***sections***REMOVED***for***REMOVED***attendees,***REMOVED***agenda,***REMOVED***discussion***REMOVED***points,***REMOVED***and***REMOVED***action***REMOVED***items",
***REMOVED******REMOVED******REMOVED******REMOVED***category:***REMOVED***"docs",
***REMOVED******REMOVED***},
***REMOVED******REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***id:***REMOVED***"doc-report",
***REMOVED******REMOVED******REMOVED******REMOVED***title:***REMOVED***"Generate***REMOVED***Report",
***REMOVED******REMOVED******REMOVED******REMOVED***description:***REMOVED***"Create***REMOVED***a***REMOVED***comprehensive***REMOVED***report***REMOVED***from***REMOVED***data",
***REMOVED******REMOVED******REMOVED******REMOVED***template:***REMOVED***"Generate***REMOVED***a***REMOVED***report***REMOVED***analyzing***REMOVED***[data***REMOVED***source]***REMOVED***with***REMOVED***key***REMOVED***insights,***REMOVED***trends,***REMOVED***and***REMOVED***recommendations",
***REMOVED******REMOVED******REMOVED******REMOVED***category:***REMOVED***"docs",
***REMOVED******REMOVED***},
***REMOVED******REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***id:***REMOVED***"doc-organize",
***REMOVED******REMOVED******REMOVED******REMOVED***title:***REMOVED***"Organize***REMOVED***Documents",
***REMOVED******REMOVED******REMOVED******REMOVED***description:***REMOVED***"Organize***REMOVED***files***REMOVED***in***REMOVED***Google***REMOVED***Drive",
***REMOVED******REMOVED******REMOVED******REMOVED***template:***REMOVED***"Organize***REMOVED***documents***REMOVED***in***REMOVED***my***REMOVED***Drive***REMOVED***by***REMOVED***creating***REMOVED***folders***REMOVED***for***REMOVED***[categories]***REMOVED***and***REMOVED***moving***REMOVED***relevant***REMOVED***files",
***REMOVED******REMOVED******REMOVED******REMOVED***category:***REMOVED***"docs",
***REMOVED******REMOVED***},
***REMOVED******REMOVED***
***REMOVED******REMOVED***//***REMOVED***Calendar***REMOVED***templates
***REMOVED******REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***id:***REMOVED***"calendar-schedule",
***REMOVED******REMOVED******REMOVED******REMOVED***title:***REMOVED***"Schedule***REMOVED***Meeting",
***REMOVED******REMOVED******REMOVED******REMOVED***description:***REMOVED***"Find***REMOVED***time***REMOVED***and***REMOVED***schedule***REMOVED***a***REMOVED***meeting",
***REMOVED******REMOVED******REMOVED******REMOVED***template:***REMOVED***"Find***REMOVED***available***REMOVED***time***REMOVED***slots***REMOVED***this***REMOVED***week***REMOVED***for***REMOVED***a***REMOVED***[duration]***REMOVED***meeting***REMOVED***with***REMOVED***[attendees]***REMOVED***and***REMOVED***send***REMOVED***calendar***REMOVED***invites",
***REMOVED******REMOVED******REMOVED******REMOVED***category:***REMOVED***"calendar",
***REMOVED******REMOVED***},
***REMOVED******REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***id:***REMOVED***"calendar-summary",
***REMOVED******REMOVED******REMOVED******REMOVED***title:***REMOVED***"Daily***REMOVED***Schedule***REMOVED***Summary",
***REMOVED******REMOVED******REMOVED******REMOVED***description:***REMOVED***"Get***REMOVED***today's***REMOVED***schedule***REMOVED***overview",
***REMOVED******REMOVED******REMOVED******REMOVED***template:***REMOVED***"Summarize***REMOVED***my***REMOVED***calendar***REMOVED***for***REMOVED***today***REMOVED***including***REMOVED***meeting***REMOVED***times,***REMOVED***attendees,***REMOVED***and***REMOVED***any***REMOVED***preparation***REMOVED***needed",
***REMOVED******REMOVED******REMOVED******REMOVED***category:***REMOVED***"calendar",
***REMOVED******REMOVED***},
***REMOVED******REMOVED***
***REMOVED******REMOVED***//***REMOVED***Analysis***REMOVED***templates
***REMOVED******REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***id:***REMOVED***"analysis-data",
***REMOVED******REMOVED******REMOVED******REMOVED***title:***REMOVED***"Analyze***REMOVED***Spreadsheet***REMOVED***Data",
***REMOVED******REMOVED******REMOVED******REMOVED***description:***REMOVED***"Perform***REMOVED***data***REMOVED***analysis***REMOVED***on***REMOVED***a***REMOVED***sheet",
***REMOVED******REMOVED******REMOVED******REMOVED***template:***REMOVED***"Analyze***REMOVED***the***REMOVED***data***REMOVED***in***REMOVED***[spreadsheet***REMOVED***name]***REMOVED***and***REMOVED***create***REMOVED***visualizations***REMOVED***showing***REMOVED***[metrics]***REMOVED***with***REMOVED***insights",
***REMOVED******REMOVED******REMOVED******REMOVED***category:***REMOVED***"analysis",
***REMOVED******REMOVED***},
***REMOVED******REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***id:***REMOVED***"analysis-trends",
***REMOVED******REMOVED******REMOVED******REMOVED***title:***REMOVED***"Identify***REMOVED***Trends",
***REMOVED******REMOVED******REMOVED******REMOVED***description:***REMOVED***"Find***REMOVED***patterns***REMOVED***in***REMOVED***your***REMOVED***data",
***REMOVED******REMOVED******REMOVED******REMOVED***template:***REMOVED***"Review***REMOVED***[data***REMOVED***source]***REMOVED***from***REMOVED***the***REMOVED***past***REMOVED***[time***REMOVED***period]***REMOVED***and***REMOVED***identify***REMOVED***key***REMOVED***trends,***REMOVED***patterns,***REMOVED***and***REMOVED***anomalies",
***REMOVED******REMOVED******REMOVED******REMOVED***category:***REMOVED***"analysis",
***REMOVED******REMOVED***},
];

const***REMOVED***CATEGORY_ICONS:***REMOVED***Record<QuickActionCategory,***REMOVED***typeof***REMOVED***Mail>***REMOVED***=***REMOVED***{
***REMOVED******REMOVED***email:***REMOVED***Mail,
***REMOVED******REMOVED***docs:***REMOVED***FileText,
***REMOVED******REMOVED***calendar:***REMOVED***Calendar,
***REMOVED******REMOVED***analysis:***REMOVED***BarChart,
};

const***REMOVED***CATEGORY_LABELS:***REMOVED***Record<QuickActionCategory,***REMOVED***string>***REMOVED***=***REMOVED***{
***REMOVED******REMOVED***email:***REMOVED***"Email",
***REMOVED******REMOVED***docs:***REMOVED***"Documents",
***REMOVED******REMOVED***calendar:***REMOVED***"Calendar",
***REMOVED******REMOVED***analysis:***REMOVED***"Analysis",
};

export***REMOVED***function***REMOVED***PromptTemplates({***REMOVED***onSelect,***REMOVED***disabled***REMOVED***=***REMOVED***false***REMOVED***}:***REMOVED***PromptTemplatesProps)***REMOVED***{
***REMOVED******REMOVED***const***REMOVED***[open,***REMOVED***setOpen]***REMOVED***=***REMOVED***useState(false);

***REMOVED******REMOVED***const***REMOVED***handleSelect***REMOVED***=***REMOVED***(template:***REMOVED***string)***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***onSelect(template);
***REMOVED******REMOVED******REMOVED******REMOVED***setOpen(false);
***REMOVED******REMOVED***};

***REMOVED******REMOVED***//***REMOVED***Group***REMOVED***templates***REMOVED***by***REMOVED***category
***REMOVED******REMOVED***const***REMOVED***templatesByCategory***REMOVED***=***REMOVED***DEFAULT_TEMPLATES.reduce((acc,***REMOVED***template)***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***if***REMOVED***(!acc[template.category])***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***acc[template.category]***REMOVED***=***REMOVED***[];
***REMOVED******REMOVED******REMOVED******REMOVED***}
***REMOVED******REMOVED******REMOVED******REMOVED***acc[template.category].push(template);
***REMOVED******REMOVED******REMOVED******REMOVED***return***REMOVED***acc;
***REMOVED******REMOVED***},***REMOVED***{}***REMOVED***as***REMOVED***Record<QuickActionCategory,***REMOVED***PromptTemplate[]>);

***REMOVED******REMOVED***const***REMOVED***categories***REMOVED***=***REMOVED***Object.keys(templatesByCategory)***REMOVED***as***REMOVED***QuickActionCategory[];

***REMOVED******REMOVED***return***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED***<DropdownMenu***REMOVED***open={open}***REMOVED***onOpenChange={setOpen}>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<DropdownMenuTrigger***REMOVED***asChild>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<Button
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***variant="outline"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***disabled={disabled}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className="gap-2"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***aria-label="Select***REMOVED***prompt***REMOVED***template"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<Sparkles***REMOVED***className="size-4"***REMOVED***/>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***Templates
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<ChevronDown***REMOVED***className="size-4***REMOVED***opacity-50"***REMOVED***/>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</Button>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</DropdownMenuTrigger>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<DropdownMenuContent***REMOVED***align="start"***REMOVED***className="w-[320px]***REMOVED***max-h-[500px]***REMOVED***overflow-y-auto">
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<DropdownMenuLabel***REMOVED***className="flex***REMOVED***items-center***REMOVED***gap-2">
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<Sparkles***REMOVED***className="size-4"***REMOVED***/>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***Prompt***REMOVED***Templates
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</DropdownMenuLabel>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<DropdownMenuSeparator***REMOVED***/>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{categories.map((category,***REMOVED***categoryIndex)***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***Icon***REMOVED***=***REMOVED***CATEGORY_ICONS[category];
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***templates***REMOVED***=***REMOVED***templatesByCategory[category];
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***return***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<div***REMOVED***key={category}>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<DropdownMenuGroup>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<DropdownMenuLabel***REMOVED***className="flex***REMOVED***items-center***REMOVED***gap-2***REMOVED***text-xs***REMOVED***font-semibold***REMOVED***text-muted-foreground***REMOVED***uppercase">
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<Icon***REMOVED***className="size-3.5"***REMOVED***/>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{CATEGORY_LABELS[category]}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</DropdownMenuLabel>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{templates.map((template)***REMOVED***=>***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<DropdownMenuItem
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***key={template.id}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***onClick={()***REMOVED***=>***REMOVED***handleSelect(template.template)}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className="flex***REMOVED***flex-col***REMOVED***items-start***REMOVED***gap-1***REMOVED***py-2***REMOVED***cursor-pointer"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<div***REMOVED***className="font-medium***REMOVED***text-sm">{template.title}</div>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<div***REMOVED***className="text-xs***REMOVED***text-muted-foreground***REMOVED***line-clamp-2">
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{template.description}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</div>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</DropdownMenuItem>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***))}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</DropdownMenuGroup>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{categoryIndex***REMOVED***<***REMOVED***categories.length***REMOVED***-***REMOVED***1***REMOVED***&&***REMOVED***<DropdownMenuSeparator***REMOVED***/>}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</div>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***);
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***})}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</DropdownMenuContent>
***REMOVED******REMOVED******REMOVED******REMOVED***</DropdownMenu>
***REMOVED******REMOVED***);
}

export***REMOVED***{***REMOVED***DEFAULT_TEMPLATES***REMOVED***};
