"useclient";

import{useSupabaseAuth}from"@/contexts/SupabaseAuthContext";
import{Badge}from"@/components/ui/badge";
import{CheckCircle2,XCircle,Clock}from"lucide-react";
import{formatDistanceToNow}from"date-fns";

exportfunctionOAuthStatus(){
const{user,googleOAuthStatus}=useSupabaseAuth();

if(!user){
returnnull;
}

constisConnected=googleOAuthStatus.isConnected;
constexpiresAt=googleOAuthStatus.expiresAt;
constnow=newDate();
constisExpiringSoon=expiresAt?expiresAt.getTime()-now.getTime()<24*60*60*1000:false;

return(
<divclassName="space-y-4">
<divclassName="flexitems-centerjustify-between">
<divclassName="space-y-1">
<h3className="text-smfont-medium">ConnectionStatus</h3>
<pclassName="text-smtext-muted-foreground">
YourGoogleaccountconnectionstate
</p>
</div>
<Badge
variant={isConnected?"default":"destructive"}
className="flexitems-centergap-1.5"
>
{isConnected?(
<>
<CheckCircle2className="h-3.5w-3.5"/>
Connected
</>
):(
<>
<XCircleclassName="h-3.5w-3.5"/>
Disconnected
</>
)}
</Badge>
</div>

{isConnected&&(
<divclassName="space-y-3rounded-lgborderbg-muted/50p-4">
<divclassName="flexitems-startjustify-betweengap-4">
<divclassName="space-y-1flex-1">
<pclassName="text-smfont-medium">ConnectedAccount</p>
<pclassName="text-smtext-muted-foreground">
{user.email}
</p>
</div>
</div>

{expiresAt&&(
<divclassName="flexitems-startjustify-betweengap-4pt-3border-t">
<divclassName="space-y-1flex-1">
<pclassName="text-smfont-mediumflexitems-centergap-2">
<ClockclassName="h-4w-4"/>
TokenExpiration
</p>
<pclassName="text-smtext-muted-foreground">
{isExpiringSoon?(
<spanclassName="text-orange-600dark:text-orange-400font-medium">
Expires{formatDistanceToNow(expiresAt,{addSuffix:true})}
</span>
):(
<span>
Expires{formatDistanceToNow(expiresAt,{addSuffix:true})}
</span>
)}
</p>
<pclassName="text-xstext-muted-foreground">
{expiresAt.toLocaleString()}
</p>
</div>
</div>
)}
</div>
)}

{!isConnected&&(
<divclassName="rounded-lgborderborder-destructive/50bg-destructive/10p-4">
<pclassName="text-smtext-muted-foreground">
YourGoogleaccountisnotconnected.PleasereconnecttouseAURA'sfeatures.
</p>
</div>
)}
</div>
);
}
