"useclient";

import{useSupabaseAuth}from"@/contexts/SupabaseAuthContext";
import{Badge}from"@/components/ui/badge";
import{
Tooltip,
TooltipContent,
TooltipProvider,
TooltipTrigger,
}from"@/components/ui/tooltip";
import{CheckCircle2,Info}from"lucide-react";

//MappingofOAuthscopestouser-friendlydescriptions
constSCOPE_DESCRIPTIONS:Record<string,{name:string;description:string}>={
"https://www.googleapis.com/auth/gmail.modify":{
name:"GmailAccess",
description:"Read,compose,send,andmanageyouremailmessagesandsettings",
},
"https://www.googleapis.com/auth/drive.file":{
name:"GoogleDriveFiles",
description:"ViewandmanageGoogleDrivefilesthatyouhaveopenedorcreatedwiththisapp",
},
"https://www.googleapis.com/auth/documents":{
name:"GoogleDocs",
description:"ViewandmanageyourGoogleDocsdocuments",
},
"https://www.googleapis.com/auth/spreadsheets":{
name:"GoogleSheets",
description:"ViewandmanageyourGoogleSheetsspreadsheets",
},
"https://www.googleapis.com/auth/calendar":{
name:"GoogleCalendar",
description:"Viewandmanageyourcalendarevents",
},
"https://www.googleapis.com/auth/userinfo.email":{
name:"EmailAddress",
description:"Viewyouremailaddress",
},
"https://www.googleapis.com/auth/userinfo.profile":{
name:"ProfileInformation",
description:"Viewyourbasicprofileinformation",
},
"openid":{
name:"OpenID",
description:"Authenticateyouridentity",
},
};

exportfunctionScopesList(){
const{user,googleOAuthStatus}=useSupabaseAuth();

if(!user){
returnnull;
}

constgrantedScopes=googleOAuthStatus.scopes||[];

//Getallrequestedscopes(fromtheloginfunction)
constrequestedScopes=[
"https://www.googleapis.com/auth/gmail.modify",
"https://www.googleapis.com/auth/drive.file",
"https://www.googleapis.com/auth/documents",
"https://www.googleapis.com/auth/spreadsheets",
"https://www.googleapis.com/auth/calendar",
];

return(
<divclassName="space-y-4">
<divclassName="space-y-1">
<h3className="text-smfont-medium">OAuthPermissions</h3>
<pclassName="text-smtext-muted-foreground">
PermissionsgrantedtoAURAforaccessingyourGoogleservices
</p>
</div>

<divclassName="space-y-2">
{requestedScopes.map((scope)=>{
constscopeInfo=SCOPE_DESCRIPTIONS[scope]||{
name:scope,
description:"AccesstoGoogleservices",
};
constisGranted=grantedScopes.includes(scope);

return(
<div
key={scope}
className="flexitems-startgap-3rounded-lgborderp-4hover:bg-muted/50transition-colors"
>
<divclassName="flex-shrink-0mt-0.5">
{isGranted?(
<CheckCircle2className="h-5w-5text-green-600dark:text-green-400"/>
):(
<divclassName="h-5w-5rounded-fullborder-2border-muted-foreground/30"/>
)}
</div>

<divclassName="flex-1space-y-1">
<divclassName="flexitems-centergap-2">
<pclassName="text-smfont-medium">{scopeInfo.name}</p>
{isGranted&&(
<Badgevariant="outline"className="text-xs">
Granted
</Badge>
)}
</div>
<pclassName="text-smtext-muted-foreground">
{scopeInfo.description}
</p>
</div>

<TooltipProvider>
<Tooltip>
<TooltipTriggerasChild>
<button
className="flex-shrink-0text-muted-foregroundhover:text-foregroundtransition-colors"
aria-label="Moreinformation"
>
<InfoclassName="h-4w-4"/>
</button>
</TooltipTrigger>
<TooltipContentclassName="max-w-xs">
<pclassName="text-xs">{scope}</p>
</TooltipContent>
</Tooltip>
</TooltipProvider>
</div>
);
})}
</div>

{grantedScopes.length>0&&(
<divclassName="rounded-lgbg-muted/50p-4">
<pclassName="text-xstext-muted-foreground">
{grantedScopes.length}of{requestedScopes.length}requestedpermissionsgranted
</p>
</div>
)}
</div>
);
}
