"use***REMOVED***client";

import***REMOVED***{***REMOVED***useAuth***REMOVED***}***REMOVED***from***REMOVED***"@/contexts/AuthContext";
import***REMOVED***{***REMOVED***Badge***REMOVED***}***REMOVED***from***REMOVED***"@/components/ui/badge";
import***REMOVED***{
***REMOVED******REMOVED***Tooltip,
***REMOVED******REMOVED***TooltipContent,
***REMOVED******REMOVED***TooltipProvider,
***REMOVED******REMOVED***TooltipTrigger,
}***REMOVED***from***REMOVED***"@/components/ui/tooltip";
import***REMOVED***{***REMOVED***CheckCircle2,***REMOVED***Info***REMOVED***}***REMOVED***from***REMOVED***"lucide-react";

//***REMOVED***Mapping***REMOVED***of***REMOVED***OAuth***REMOVED***scopes***REMOVED***to***REMOVED***user-friendly***REMOVED***descriptions
const***REMOVED***SCOPE_DESCRIPTIONS:***REMOVED***Record<string,***REMOVED***{***REMOVED***name:***REMOVED***string;***REMOVED***description:***REMOVED***string***REMOVED***}>***REMOVED***=***REMOVED***{
***REMOVED******REMOVED***"https://www.googleapis.com/auth/gmail.modify":***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***name:***REMOVED***"Gmail***REMOVED***Access",
***REMOVED******REMOVED******REMOVED******REMOVED***description:***REMOVED***"Read,***REMOVED***compose,***REMOVED***send,***REMOVED***and***REMOVED***manage***REMOVED***your***REMOVED***email***REMOVED***messages***REMOVED***and***REMOVED***settings",
***REMOVED******REMOVED***},
***REMOVED******REMOVED***"https://www.googleapis.com/auth/drive.file":***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***name:***REMOVED***"Google***REMOVED***Drive***REMOVED***Files",
***REMOVED******REMOVED******REMOVED******REMOVED***description:***REMOVED***"View***REMOVED***and***REMOVED***manage***REMOVED***Google***REMOVED***Drive***REMOVED***files***REMOVED***that***REMOVED***you***REMOVED***have***REMOVED***opened***REMOVED***or***REMOVED***created***REMOVED***with***REMOVED***this***REMOVED***app",
***REMOVED******REMOVED***},
***REMOVED******REMOVED***"https://www.googleapis.com/auth/documents":***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***name:***REMOVED***"Google***REMOVED***Docs",
***REMOVED******REMOVED******REMOVED******REMOVED***description:***REMOVED***"View***REMOVED***and***REMOVED***manage***REMOVED***your***REMOVED***Google***REMOVED***Docs***REMOVED***documents",
***REMOVED******REMOVED***},
***REMOVED******REMOVED***"https://www.googleapis.com/auth/spreadsheets":***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***name:***REMOVED***"Google***REMOVED***Sheets",
***REMOVED******REMOVED******REMOVED******REMOVED***description:***REMOVED***"View***REMOVED***and***REMOVED***manage***REMOVED***your***REMOVED***Google***REMOVED***Sheets***REMOVED***spreadsheets",
***REMOVED******REMOVED***},
***REMOVED******REMOVED***"https://www.googleapis.com/auth/calendar":***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***name:***REMOVED***"Google***REMOVED***Calendar",
***REMOVED******REMOVED******REMOVED******REMOVED***description:***REMOVED***"View***REMOVED***and***REMOVED***manage***REMOVED***your***REMOVED***calendar***REMOVED***events",
***REMOVED******REMOVED***},
***REMOVED******REMOVED***"https://www.googleapis.com/auth/userinfo.email":***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***name:***REMOVED***"Email***REMOVED***Address",
***REMOVED******REMOVED******REMOVED******REMOVED***description:***REMOVED***"View***REMOVED***your***REMOVED***email***REMOVED***address",
***REMOVED******REMOVED***},
***REMOVED******REMOVED***"https://www.googleapis.com/auth/userinfo.profile":***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***name:***REMOVED***"Profile***REMOVED***Information",
***REMOVED******REMOVED******REMOVED******REMOVED***description:***REMOVED***"View***REMOVED***your***REMOVED***basic***REMOVED***profile***REMOVED***information",
***REMOVED******REMOVED***},
***REMOVED******REMOVED***"openid":***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***name:***REMOVED***"OpenID",
***REMOVED******REMOVED******REMOVED******REMOVED***description:***REMOVED***"Authenticate***REMOVED***your***REMOVED***identity",
***REMOVED******REMOVED***},
};

export***REMOVED***function***REMOVED***ScopesList()***REMOVED***{
***REMOVED******REMOVED***const***REMOVED***{***REMOVED***session***REMOVED***}***REMOVED***=***REMOVED***useAuth();

***REMOVED******REMOVED***if***REMOVED***(!session)***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***return***REMOVED***null;
***REMOVED******REMOVED***}

***REMOVED******REMOVED***const***REMOVED***{***REMOVED***oauthStatus***REMOVED***}***REMOVED***=***REMOVED***session;
***REMOVED******REMOVED***const***REMOVED***grantedScopes***REMOVED***=***REMOVED***oauthStatus.scopes***REMOVED***||***REMOVED***[];

***REMOVED******REMOVED***//***REMOVED***Get***REMOVED***all***REMOVED***requested***REMOVED***scopes***REMOVED***(from***REMOVED***the***REMOVED***login***REMOVED***function)
***REMOVED******REMOVED***const***REMOVED***requestedScopes***REMOVED***=***REMOVED***[
***REMOVED******REMOVED******REMOVED******REMOVED***"https://www.googleapis.com/auth/gmail.modify",
***REMOVED******REMOVED******REMOVED******REMOVED***"https://www.googleapis.com/auth/drive.file",
***REMOVED******REMOVED******REMOVED******REMOVED***"https://www.googleapis.com/auth/documents",
***REMOVED******REMOVED******REMOVED******REMOVED***"https://www.googleapis.com/auth/spreadsheets",
***REMOVED******REMOVED******REMOVED******REMOVED***"https://www.googleapis.com/auth/calendar",
***REMOVED******REMOVED***];

***REMOVED******REMOVED***return***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED***<div***REMOVED***className="space-y-4">
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<div***REMOVED***className="space-y-1">
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<h3***REMOVED***className="text-sm***REMOVED***font-medium">OAuth***REMOVED***Permissions</h3>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<p***REMOVED***className="text-sm***REMOVED***text-muted-foreground">
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***Permissions***REMOVED***granted***REMOVED***to***REMOVED***AURA***REMOVED***for***REMOVED***accessing***REMOVED***your***REMOVED***Google***REMOVED***services
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</p>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</div>

***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<div***REMOVED***className="space-y-2">
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{requestedScopes.map((scope)***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***scopeInfo***REMOVED***=***REMOVED***SCOPE_DESCRIPTIONS[scope]***REMOVED***||***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***name:***REMOVED***scope,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***description:***REMOVED***"Access***REMOVED***to***REMOVED***Google***REMOVED***services",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***};
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***isGranted***REMOVED***=***REMOVED***grantedScopes.includes(scope);

***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***return***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<div
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***key={scope}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className="flex***REMOVED***items-start***REMOVED***gap-3***REMOVED***rounded-lg***REMOVED***border***REMOVED***p-4***REMOVED***hover:bg-muted/50***REMOVED***transition-colors"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<div***REMOVED***className="flex-shrink-0***REMOVED***mt-0.5">
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{isGranted***REMOVED***?***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<CheckCircle2***REMOVED***className="h-5***REMOVED***w-5***REMOVED***text-green-600***REMOVED***dark:text-green-400"***REMOVED***/>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***)***REMOVED***:***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<div***REMOVED***className="h-5***REMOVED***w-5***REMOVED***rounded-full***REMOVED***border-2***REMOVED***border-muted-foreground/30"***REMOVED***/>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***)}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</div>

***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<div***REMOVED***className="flex-1***REMOVED***space-y-1">
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<div***REMOVED***className="flex***REMOVED***items-center***REMOVED***gap-2">
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<p***REMOVED***className="text-sm***REMOVED***font-medium">{scopeInfo.name}</p>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{isGranted***REMOVED***&&***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<Badge***REMOVED***variant="outline"***REMOVED***className="text-xs">
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***Granted
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</Badge>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***)}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</div>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<p***REMOVED***className="text-sm***REMOVED***text-muted-foreground">
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{scopeInfo.description}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</p>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</div>

***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<TooltipProvider>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<Tooltip>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<TooltipTrigger***REMOVED***asChild>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<button
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***className="flex-shrink-0***REMOVED***text-muted-foreground***REMOVED***hover:text-foreground***REMOVED***transition-colors"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***aria-label="More***REMOVED***information"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<Info***REMOVED***className="h-4***REMOVED***w-4"***REMOVED***/>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</button>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</TooltipTrigger>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<TooltipContent***REMOVED***className="max-w-xs">
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<p***REMOVED***className="text-xs">{scope}</p>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</TooltipContent>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</Tooltip>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</TooltipProvider>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</div>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***);
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***})}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</div>

***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{grantedScopes.length***REMOVED***>***REMOVED***0***REMOVED***&&***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<div***REMOVED***className="rounded-lg***REMOVED***bg-muted/50***REMOVED***p-4">
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<p***REMOVED***className="text-xs***REMOVED***text-muted-foreground">
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{grantedScopes.length}***REMOVED***of***REMOVED***{requestedScopes.length}***REMOVED***requested***REMOVED***permissions***REMOVED***granted
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</p>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</div>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***)}
***REMOVED******REMOVED******REMOVED******REMOVED***</div>
***REMOVED******REMOVED***);
}
