//DatabasetypesforSupabase
//Thisfilewillbeauto-generatedusing:npxsupabasegentypestypescript--project-idYOUR_PROJECT_ID>lib/supabase/database.types.ts

exporttypeJson=
|string
|number
|boolean
|null
|{[key:string]:Json|undefined}
|Json[]

exportinterfaceDatabase{
public:{
Tables:{
profiles:{
Row:{
id:string
email:string
full_name:string|null
avatar_url:string|null
preferences:Json|null
google_access_token:string|null
google_refresh_token:string|null
google_token_expires_at:string|null
google_scopes:string[]|null
created_at:string
updated_at:string
}
Insert:{
id:string
email:string
full_name?:string|null
avatar_url?:string|null
preferences?:Json|null
google_access_token?:string|null
google_refresh_token?:string|null
google_token_expires_at?:string|null
google_scopes?:string[]|null
created_at?:string
updated_at?:string
}
Update:{
id?:string
email?:string
full_name?:string|null
avatar_url?:string|null
preferences?:Json|null
google_access_token?:string|null
google_refresh_token?:string|null
google_token_expires_at?:string|null
google_scopes?:string[]|null
created_at?:string
updated_at?:string
}
}
oauth_tokens:{
Row:{
id:string
user_id:string
provider:string
access_token:string
refresh_token:string|null
token_type:string
expires_at:string|null
scopes:string[]|null
created_at:string
updated_at:string
}
Insert:{
id?:string
user_id:string
provider?:string
access_token:string
refresh_token?:string|null
token_type?:string
expires_at?:string|null
scopes?:string[]|null
created_at?:string
updated_at?:string
}
Update:{
id?:string
user_id?:string
provider?:string
access_token?:string
refresh_token?:string|null
token_type?:string
expires_at?:string|null
scopes?:string[]|null
created_at?:string
updated_at?:string
}
}
workflows:{
Row:{
id:string
user_id:string
command:string
status:"planning"|"executing"|"completed"|"failed"|"cancelled"
steps:Json
results:Json
error:string|null
start_time:string
end_time:string|null
created_at:string
updated_at:string
}
Insert:{
id?:string
user_id:string
command:string
status?:"planning"|"executing"|"completed"|"failed"|"cancelled"
steps?:Json
results?:Json
error?:string|null
start_time?:string
end_time?:string|null
created_at?:string
updated_at?:string
}
Update:{
id?:string
user_id?:string
command?:string
status?:"planning"|"executing"|"completed"|"failed"|"cancelled"
steps?:Json
results?:Json
error?:string|null
start_time?:string
end_time?:string|null
created_at?:string
updated_at?:string
}
}
workflow_history:{
Row:{
id:string
user_id:string
workflow_id:string
command:string
status:string
executed_at:string
created_at:string
}
Insert:{
id?:string
user_id:string
workflow_id:string
command:string
status:string
executed_at?:string
created_at?:string
}
Update:{
id?:string
user_id?:string
workflow_id?:string
command?:string
status?:string
executed_at?:string
created_at?:string
}
}
}
Views:{
[_innever]:never
}
Functions:{
[_innever]:never
}
Enums:{
workflow_status:"planning"|"executing"|"completed"|"failed"|"cancelled"
}
}
}
