import***REMOVED***{***REMOVED***createServerClient***REMOVED***}***REMOVED***from***REMOVED***"@supabase/ssr";
import***REMOVED***{***REMOVED***cookies***REMOVED***}***REMOVED***from***REMOVED***"next/headers";

export***REMOVED***async***REMOVED***function***REMOVED***createClient()***REMOVED***{
***REMOVED******REMOVED***const***REMOVED***cookieStore***REMOVED***=***REMOVED***await***REMOVED***cookies();

***REMOVED******REMOVED***return***REMOVED***createServerClient(
***REMOVED******REMOVED******REMOVED******REMOVED***process.env.NEXT_PUBLIC_SUPABASE_URL!,
***REMOVED******REMOVED******REMOVED******REMOVED***process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
***REMOVED******REMOVED******REMOVED******REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***cookies:***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***getAll()***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***return***REMOVED***cookieStore.getAll();
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***},
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***setAll(cookiesToSet)***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***try***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***cookiesToSet.forEach(({***REMOVED***name,***REMOVED***value,***REMOVED***options***REMOVED***})***REMOVED***=>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***cookieStore.set(name,***REMOVED***value,***REMOVED***options)
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***);
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***}***REMOVED***catch***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***//***REMOVED***The***REMOVED***`setAll`***REMOVED***method***REMOVED***was***REMOVED***called***REMOVED***from***REMOVED***a***REMOVED***Server***REMOVED***Component.
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***//***REMOVED***This***REMOVED***can***REMOVED***be***REMOVED***ignored***REMOVED***if***REMOVED***you***REMOVED***have***REMOVED***middleware***REMOVED***refreshing
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***//***REMOVED***user***REMOVED***sessions.
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***},
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***},
***REMOVED******REMOVED******REMOVED******REMOVED***}
***REMOVED******REMOVED***);
}
