import{createServerClient}from"@supabase/ssr";
import{cookies}from"next/headers";

/**
*CreatesaSupabaseclientforserver-sideoperationswithanonkey.
*ThisclientissubjecttoRowLevelSecurity(RLS)policies.
*UseforuserauthenticationandoperationsthatshouldrespectRLS.
*/
exportasyncfunctioncreateClient(){
constcookieStore=awaitcookies();

returncreateServerClient(
process.env.NEXT_PUBLIC_SUPABASE_URL!,
process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
{
cookies:{
getAll(){
returncookieStore.getAll();
},
setAll(cookiesToSet){
try{
cookiesToSet.forEach(({name,value,options})=>
cookieStore.set(name,value,options)
);
}catch{
//The`setAll`methodwascalledfromaServerComponent.
//Thiscanbeignoredifyouhavemiddlewarerefreshing
//usersessions.
}
},
},
}
);
}

/**
*CreatesaSupabaseclientwithserviceroleprivileges.
*ThisclientbypassesRowLevelSecurity(RLS)policies.
*UseONLYforserver-sidesystemoperationsthatrequireelevatedpermissions.
*
*WARNING:Neverexposethisclientoritskeytoclient-sidecode.
*OnlyuseinAPIroutesandserver-sidefunctions.
*/
exportfunctioncreateServiceClient(){
returncreateServerClient(
process.env.NEXT_PUBLIC_SUPABASE_URL!,
process.env.SUPABASE_SERVICE_ROLE_KEY!,
{
cookies:{
getAll:()=>[],
setAll:()=>{},
},
}
);
}
